### ISSUE TITLE
Navigation in "Access Control/Groups" breaks search page

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1028]
OK scenario :
1. As Admin user go to "Access Control" "Groups"
2. From that screen perform any global search or just double click global search button
3. Search seems to work fine

Broken scenario : 
1. As Admin user go to "Access Control" "Groups"
2. Navigate around the list of groups with paginator
3. From that screen perform any global search or just double click global search button
4. Search form is corupted - "Loading search results" never ends

**Comment by tdonohue** [comment]
Good catch, @MarisArins !  I'm able to reproduce this.  Moving this into 7.0 Beta 5 for further analysis.

@artlowel , could you provide an estimate for this?  It sounds somewhat similar to #1016, which was recently fixed by your team in #1022.  It seems, to me, like something from the Groups pagination/search is carrying over into the main search results & causing issues.

**Comment by artlowel** [comment]
This should be fixed by #1048
