### ISSUE TITLE
Several bugs on collection's item template 

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1034]
**Describe the bug**
There are several issue while handling a collection's item template : 
- after generating a template item for a collection the system redirect you on the template edit page. If you go back directly to the collection edit page the new template item is not yet displayed, but you have to refresh the page to have it. I suppose it's only a cache issue. 
- when generating a template item for a collection the template item edit page show the metadata belonging to the related collection. This can be seen quickly by opening the browser developer tool and looking for the creation request : 

![Schermata da 2021-02-24 09-05-01](https://user-images.githubusercontent.com/2486489/108968109-a4572c80-7680-11eb-8e37-97649edfb9f6.png)

- trying to remove displayed metadata doesn't work because they don't really belong to the item template object, but are collection's metadata
- trying to add a new metadata returns a 404 error.
- when deleting the item template the interface show both a success and an error notification, but it seems it has been deleted successfully. indeed if you refresh the page item template no longer exists
![Schermata da 2021-02-24 09-20-31](https://user-images.githubusercontent.com/2486489/108969034-d321d280-7681-11eb-8e67-64146633a4aa.png)

**Comment by tdonohue** [comment]
@artlowel : Could you (or someone on your team) provide an estimate for these fixes?  It looks like the initial implementation was in #749

**Comment by artlowel** [comment]
All issues, except the dual notification error are due to the fact that the item template editor shares code with the item metadata editor, and _it_ will know which item to work on by using the dso resolved in the route. For item templates, that dso is the collection. So the ItemMetadataComponent will need to be refactored to get its item from an input.

The dual notification issue is separate and is likely due to the notification not waiting for the remotedata to be resolved. So it shows a failed notification while it's loading and a succeeded notification as it completes

Fixing these issues will take an estimated **6h**
