### ISSUE TITLE
Unable to login/create session when dspace 7 angular is in production mode

### ISSUE THREAD

**Issue by vahem2lu** [DSpace/dspace-angular#1036]
Using **backend** DSpace 7.0-beta5-SNAPSHOT and DSpace 7.0-beta4 and frontend **dspace-angular** beta4 release or main branch from git it occurs when angular is ran in production mode `dsAuthInfo` cookie is not properly saved. And therefore login is not made.

As username and password is correct (because login is accepted and HAL browser (from 8080 port) confirms that those are accepted credentials) there seems to be "hard refresh" on page which causes session/cookie to destroy. I can see that this cookie appears for a limited of time between reload/refresh.

Same thing happens when registering as new user from frontend - after clicking link from email, I'm logged in, but as soon as I "refresh" the page, session is destroyed.

**Software**
- Arch Linux
- npm 6.14.11
- nodejs 12.20.1
- yarn 1.22.10

**To Reproduce**
1. fresh clone from git
2. create `src/environments/environment.prod.ts` file and edit ui/rest settings and set production to true
3. environment.prod.ts file
```
export const environment = {

  production: true,
  ui: {
    ssl: false,
    host: 'localhost',
    port: 4000,
    nameSpace: '/',
  },

  rest: {
    ssl: false,
    host: 'localhost',
    port: 8080,
    // NOTE: Space is capitalized because 'namespace' is a reserved string in TypeScript
    nameSpace: '/server'
  },
```
4. run `yarn run build:prod`
5. start server with `yarn run serve:ssr`
6. unsuccessful login is made

But, if you just edit `environment.common.ts` and start with `yarn run start:dev`, then login works properly.

It seems like some compile issue, because when I edit `dist/server.js` and `dist/server/main.js` after compile and set `production: false`, then login does not work as well.

**Expected behavior**
Login should be successful and session should be set.

**Related work**
Discussion in Google Groups may suggest that it's a bug
https://groups.google.com/g/dspace-tech/c/uJs4tBkaxZM

**Comment by tdonohue** [comment]
@vahem2lu : I just responded to your thread in Google Groups (before seeing you created a ticket)

Unfortunately, I think we'd need more information to help debug this. 
* What's the exact error you are seeing?  
    * If you are using a browser like Chrome, you could also open up "DevTools" (More Tools -> Developer Tools) and look at the "Network" tab right before you try to login.  Then attempt to login & it may give you a more detailed error message.
    * You also could check the (backend) logs to see if it gives additional details
* As we are in very active​ development right now, I'd highly encourage updating to the latest "main" GitHub branch (both for Angular UI and the backend).  Because we are merging new fixes daily/weekly, if one of the two is outdated, you might hit odd issues.  (Additionally, sometimes we merge fixes to both the frontend & backend simultaneously because you need both fixes together​ to fix some bugs.)
* I'd also highly recommend double checking that the URLs in the "dspace.server.url" and "dspace.ui.url" (in the backend local.cfg) match up with the URL parts in your "environment.*.ts" configuration in Angular UI.  If those don't match​, then the frontend may not trust​ the backend and will refuse to allow you to login.

**Comment by vahem2lu** [comment]
Thanks for the feedback!

The thing is that there's no "error" in dspace.log, tomcat9 logs, nor in verbose angular mode or in dev tools in Chrome/Firefox. I've tested Safari as well, so it does not seem like browser issue.

I've used git version of DSpace and dspace-angular for 1.5 week now and there's no difference. Also, latest upgrade for me was yesterday some hour before posting here.

environment.prod.ts and environment.common.ts (for `yarn run start:dev`) is in sync with dpsace `local.cfg` file.

DSpace runs on 8080 port (http) and angular in 4000 (http).

There's also third person in dspace-community having same issue: https://groups.google.com/g/dspace-community/c/1ZuaiuU09jo/m/l3r2wg0eAAAJ

**Comment by tdonohue** [comment]
@vahem2lu : Could you share the exact error message returned by the REST API when a login fails?  Is it a 401 or a 403 response code (You should be able to see this on the Network Tab in Chrome DevTools)?  Any additional information provided in that 401/403 response code?

You noted that this works when you modify `environment.common.ts` and do `yarn run start:dev`.   Are the changes you are making to `environment.prod.ts` **identical** to those that work in `environment.common.ts`?   If not, it'd be useful to know what differences there are.  You also might try (temporarily) removing the `environment.prod.ts`, add tweaks directly to `environment.common.ts` and try `yarn start` -- this will still build for "production" but will use `environment.common.ts`.  It might help narrow down if something in your `environment.prod.ts` is the problem here.

**Comment by tdonohue** [comment]
I should also mention, this point from your initial description is very odd to me:
> there seems to be "hard refresh" on page which causes session/cookie to destroy. I can see that this cookie appears for a limited of time between reload/refresh.

I can confirm there is a *purposeful* hard refresh after you login (or logout).  That is done on purpose to refresh/reload all components based on your authenticated user (as you may be able to "see" more content or options once authenticated).  This "hard refresh" _should not_ be destroying the `dsAuthInfo` cookie though -- I've never seen that locally or on our demo site (https://demo7.dspace.org/) -- so, that is very odd behavior.  I'm not exactly sure what would cause that, as I've never seen that before.  Is there any chance the URL is somehow changing in your browser during that "hard refresh" (as that would cause the browser to perhaps throw out the cookie since a cookie is associated to the URL that created it)?  Or any other hints as to what might be different in your scenario (do you have a proxy? or something installed in your browser that might be blocking some cookies?)

**Comment by vahem2lu** [comment]
There seems no error codes or failed requests and my guess is that there's no error code, as login does not "fail", because when I literally enter wrong password, then I get error in angular AND error code 401 from server POST request as well.
![Screenshot 2021-02-26 at 17 58 06](https://user-images.githubusercontent.com/15649157/109323712-70386300-785c-11eb-970b-4c6fddd82a95.png)

> Are the changes you are making to environment.prod.ts identical to those that work in environment.common.ts?

Yes, only difference is "production". I've tried editing languages as well, but this does not seem to have effect, anyway I will leave here for whole file setup (I've tried without them as well).

`src/environments/environment.prod.ts` file based on environment.template.ts
```
export const environment = {

  production: true,

  ui: {
    ssl: false,
    host: 'server_internal_network_ip_here',
    port: 4000,
    nameSpace: '/',
  },

  rest: {
    ssl: false,
    host: 'same_server_internal_network_ip_here',
    port: 8080,
    // NOTE: Space is capitalized because 'namespace' is a reserved string in TypeScript
    nameSpace: '/server'
  },

  debug: false,
  // Default Language in which the UI will be rendered if the user's browser language is not an active language
  defaultLanguage: 'en',
  // Languages. DSpace Angular holds a message catalog for each of the following languages.
  // When set to active, users will be able to switch to the use of this language in the user interface.
  languages: [{
    code: 'en',
    label: 'English',
    active: true,
  }, {
    code: 'de',
    label: 'Deutsch',
    active: false,
  }, {
    code: 'cs',
    label: 'Čeština',
    active: false,
  }, {
    code: 'nl',
    label: 'Nederlands',
    active: false,
  }, {
    code: 'pt',
    label: 'Português',
    active: false,
  }, {
    code: 'fr',
    label: 'Français',
    active: false,
  }, {
    code: 'lv',
    label: 'Latviešu',
    active: false,
  },{
    code: 'fi',
    label: 'Suomi',
    active: false,
  },{
    code: 'hu',
    label: 'magyar',
    active: false,
  }]
};
```

There's no proxy (yet, Apache is planned) and DSpace and dspace-angular are running without SSL on default ports, as stated before.

Only thing different than others (and pardon my joke): First rule of Arch Linux is that you tell everyone you use Arch Linux. 😄 
Something what I'm doing differently is that for production I build & compile with `yarn run build:prod` and then serve with `yarn run serve:ssr`. For development I use `yarn run start:dev`. But this should be okay, as files for angular are not changed meanwhile, so I don't need to compile 10-20 minutes every time I start my application.

URL is changing, but only `/reload/timestamp-or-something-...`
See short [video](https://aus.veebiaken.ee/cookiemonster.mov) for `dsAuthInfo` cookie to come and go after pushing login button. 😄 

I've tried different browsers and in incognito without ad-blocking extensions. As stated, when running in dev mode with same browsers and same server, even same build (I haven't updated git for a day now) - login works.

**Comment by tdonohue** [comment]
@vahem2lu : Thanks for the additional info.  A few of us were talking on Slack & a new idea came up. 

Could you try something for us?  In your *backend* configuration, can you add the following to your `local.cfg` configuration:

```
# This defaults to just "dspace.ui.url" (public URL), but it might also need localhost:4000 (private URL) for requests that come directly from the Node server to the backend.
rest.cors.allowed-origins = ${dspace.ui.url}, http://localhost:4000

# This has no defaults, but might be getting in the way
proxies.trusted.ipranges = [add-IP-address-of-your-UI-server]
```

Then, restart your backend & try to login again.  We're wondering if either CORS or these proxy settings are "getting in the way" here and blocking you.  If **so**, then this may be a bug in that our default settings are not working properly for Production-like setups.

**Comment by vahem2lu** [comment]
Thank you for thinking along!

I've tried CORS before as well, this came up to my mind as well, even I thought that maybe somehow angular does not like http (port 80) login POST or something like that in "prod" mode...

Anyway, your solution worked, and:

*Tried both*: worked

*tried only CORS with*
`rest.cors.allowed-origins = ${dspace.ui.url}, http://internal_ip:4000`
did not work (CORS was default before).

*tried proxies ipranges* with
`proxies.trusted.ipranges = just_internal_ip_without_port`
(As rest/dspace works on internal IP, not "localhost" hostname)
And it works! Hard refresh is still there, but cookie is there and session is made! :tada:

**Comment by tdonohue** [comment]
@vahem2lu : Thanks for your help in testing this out.  It *sounds like* `proxies.trusted.ipranges` is to blame then, and this also sounds like a **bug** to me.  I'm going to move this over into our Beta 5 work board & start to figure out a way to fix this -- it's unexpected that `proxies.trusted.ipranges` is required...it should NOT be.

**Comment by tdonohue** [comment]
And, I just realized this bug is also described in #2984 (which I found months ago and forgot about).  In any case, I'll get these scheduled for analysis & fixing.

**Comment by vahem2lu** [comment]
I even saw this but did not think it was a deal, as I focused on angular (because on DSpace backend, port 8080 (HAL) login worked).

**Comment by tesema** [comment]
I am a problem with DSpace backend install directory problem and confusion. How could I install dspace bankend in the same installation.

**Comment by juanc1979** [comment]
Hi i´m having the same problem, when i run dspace 7 ui with yarn start:dev i can enter as an administrator but when i run yarn run server:ssr i access the ui as a normal user, if i go to my user i can see that it´s in the administrator group but still can´t login as administrator in production mode. 
I´ve made the changes you suggested 
# This defaults to just "dspace.ui.url" (public URL), but it might also need localhost:4000 (private URL) for requests that come directly from the Node server to the backend.
rest.cors.allowed-origins = ${dspace.ui.url}, http://localhost:4000

# This has no defaults, but might be getting in the way
proxies.trusted.ipranges = [add-IP-address-of-your-UI-server]
But stil can´t login as an administrator.

**Comment by tdonohue** [comment]
This is a very old bug ticket and it is not applicable anymore for DSpace 7.3 or above. If you continue to have issues of this type, make sure you locate the *underlying error* using our Troubleshooting Guide: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

Chances are you'll find the underlying error is one of the common installation issues listed here: https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-CommonInstallationIssues

If you cannot figure it out, send the underlying error and steps you've tried to one of our support channels: https://wiki.lyrasis.org/display/DSPACE/Support

**Comment by juanc1979** [comment]
Thank you!!!
