### ISSUE TITLE
Firefox: Unstyled scrollbars in admin sidebar

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1039]
**Describe the bug**
On smaller viewports in Firefox, the admin sidebar scrollbars clash with the overall theme.

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/31547038/109290391-d787f000-7827-11eb-833a-f2a8e6569b43.png">

Compared to Chrome:

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/31547038/109290454-ea022980-7827-11eb-9d46-bf54721141b5.png">

**To Reproduce**
1. Open a DSpace Angular page in Firefox
2. Then this...

**Expected behavior**
Scrollbars should be styled according to the theme

**Comment by tdonohue** [comment]
This appears (to me) to be solved in Beta 5.  Just tested on https://demo7.dspace.org

While the style of the scrollbar is not 100% identical between Chrome & Firefox, both of them now show a dark background that matches the sidebar color scheme.  So, I no longer see the white/light background in Firefox (as shown in the first screenshot).

Therefore, closing this as fixed in Beta 5.
