### ISSUE TITLE
MyDSpace page should use the same components as other search results pages & should not have custom object swapping/reloading functionality

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1044]
**Describe the bug**

The changes made in #978 to fix #721 were not ideal as they treat the MyDSpace page's search results differently from other search results listing.  These changes however were deemed necessary because the MyDSpace page doesn't use the same components as other search results...see @atarix83's [comment here](https://github.com/DSpace/dspace-angular/pull/978#issuecomment-791450504).  This resulted in a need to refresh individual components within an existing list of results.

Ideally, we would NOT be refreshing/swapping individual objects in a list, and instead update the list while ensuring you "follow" or remain with the updated item in that list.  One way to possibly achieve this is described by @artlowel in [this comment](https://github.com/DSpace/dspace-angular/pull/978#issuecomment-790800076).

Unfortunately, we were not able to easily solve this in 7.0 without a larger refactor (as described in related tickets below).  Therefore, this work may need to be completed in conjunction with those related tickets.

**Related work**

* Discovered in review of #978 (and fixing this ticket will likely require removing or refactoring the work of the prior PR)
* Relates directly to #773 
* Also seems related to #741 (as that involves updating/deleting objects in lists)

**Comment by atarix83** [comment]
The work that should be done here is an huge refactoring of all components involved in the search functionality. Currently there isn't an unique root search component that deal with the search state and propagate the information needed to the children, and the result is any changes to the functionality are hard to manage (see for example the workaround that we needed to implement  https://github.com/DSpace/dspace-angular/issues/721).

Here are some important key points to define for refactoring : 
- there should be an unique root search component to use in different places, for example in the mydspace page or the in search page
- this component should be extremely customizable so that it can be reused easily
- the root component should handle search results and facets based on the search configuration and search parameter, if any
- the result and facets must be passed on to the child components
- the child components should only emit events to handle in the root component
- the new root component should provide object swapping/reloading functionality

@tdonohue we estimate the refactoring in about 60 hours

**Comment by tdonohue** [comment]
Thanks for the analysis @atarix83 .  I've added the estimate to this ticket.
