### ISSUE TITLE
Date filter no longer works in Search

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1112]
**Describe the bug**
(Copied from [Test Plan, Item T009](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

>"Basic search results are appearing as documented under expected results. However, if adding additional filters on advanced search page then search stops functioning. Use case - basic search made on ""test"", added author name, ""Simmons, Cameron"" and added year range filter. Upon adding year range filter, screen goes into loop.

Video of behavior: https://ibb.co/GnK1pSX

**To Reproduce**
1. Search on "test" on https://demo7.dspace.org/
2. Filter by Author "Simmons, Cameron"
3. Filter by a Date (or Date range).  The results will never load.

**Expected behavior**
Date filters should work

**Comment by tdonohue** [comment]
@artlowel : Could you (or someone on your team) look into this & let me know what you find?  It almost appears (to me) like the Date filter isn't sent to the backend -- so I *think* it's a UI problem.

**Comment by artlowel** [comment]
The date filter is sent to the backend, but the backend returns a 422. The reason is that the filter doesn't contain the equals operator. 

I also notice there's an issue with the handles of the date slider:
![image](https://user-images.githubusercontent.com/1567693/115374931-97147500-a1cd-11eb-863a-1d84cd717a37.png)


Both issues can be fixed in an estimated **3 hours**

**Comment by tdonohue** [comment]
Thanks @artlowel .  Estimate sounds good & assigning back to you for your team to work on.
