### ISSUE TITLE
Next/previous buttons not functioning in browse-by view

### ISSUE THREAD

**Issue by gsteinhart** [DSpace/dspace-angular#1135]
To reproduce the problem:

1. Make any selection from the "all of Dspace" menu
2. Scroll to the bottom of the page
3. Try to use the Next button - it doesn't work

**Comment by tdonohue** [comment]
Hi @gsteinhart : This is actually a result of someone deleting all our test content (again).  These buttons don't work because there's only one page of results being returned. 

So, I'm going to close this as it's a result of bad data.  The 4Science team is currently working on restoring our test data again.
