### ISSUE TITLE
Used forgot password or registration links keep loading forever

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1136]
**Describe the bug**
If you click a forgot password link after it's been used, or get the URL wrong, the page will keep loading forever. The reason is that rest returns a 404, but the UI only takes succeeded responses in to account.

For the registration link it's slightly more convoluted. If you click a used or wrong registration link you'll see the end-user agreement first. And if you've already agreed to it, you can't proceed. What you can do is click cancel (which revokes your agreement, that should be fixed as well) and click the link again. That _will_ allow you to check the agreement, save, which will cause rest to return a 404, and the UI to end up in a perpetual loading state.

**To Reproduce**
Forgot password:
1. Request a forgot password link
2. Use it to reset the password
3. Click it again

Register:
1. Register as a new user
2. Click the register link in the email
3. Finish the registration process
3. Click the registration link again
4. Click cancel on the end-user agreement page
5. Click the registration link again
6. Agree on the end-user agreement page, and click save

**Expected behavior**
Since we can't determine whether a forgot password or registration link has already been used, or is just plain wrong, we should simply show a 404 page.

For registration that also means we should check whether the link is valid, before we show the end-user agreement page.

Finally the cancel button on the end-user agreement page shouldn't change whether you've agreed or not, it should leave the state as it was.

**Related work**
- #687
- #707
- Discovered while working on #1113

**Comment by artlowel** [comment]
Fixing these issues will take an estimated **6 hours**

I would label these low or at most medium prio

**Comment by tdonohue** [comment]
@artlowel : Thanks for the bug ticket. I think this is `medium priority` as it sounds like something that really shouldn't happen in a production system.  I've added the estimate, let me know if your team would like to claim.

**Comment by MarieVerdonck** [comment]
For the 'cancel reset user agreement state' part of this issue: 

This isn't actually the case, the cancel just logs the current user from the session out, see `EndUserAgreementComponent#cancel` [[here](https://github.com/DSpace/dspace-angular/blob/main/src/app/info/end-user-agreement/end-user-agreement.component.ts#L77-L90)](https://github.com/DSpace/dspace-angular/blob/main/src/app/info/end-user-agreement/end-user-agreement.component.ts#L77-L90). So the fact that this checkbox is marked for the end-user agreement when you revisit a used registration link is due to it getting this info from the currently authenticated user (see `EndUserAgreementService#setUserAcceptedAgreement` [[here](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/end-user-agreement/end-user-agreement.service.ts#L62)](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/end-user-agreement/end-user-agreement.service.ts#L62)). 

If you revisit a used registration link via incognito tab for example the checkbox isn't checked and you can submit successfully after checking, and up on the forever loading page. So no changes needed in this for the context of this issue/PR. Whether or not the checkbox should be marked based on a possible currently authenticated user (if coming via registration link or otherwise) is possible separate issue.
