### ISSUE TITLE
Authors section appears twice on every Item page

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1196]
**Describe the bug**
On every item page (including Entities like Publication) the list of Authors appears twice...once on the left & once on the right.

**To Reproduce**
Some examples from the demo site:
* Regular Item: https://demo7.dspace.org/items/80b35f2d-cd10-4281-b180-fc6378b02d4c
* Publication Entity: https://demo7.dspace.org/entities/publication/12623672-25a9-4df2-ab36-699c4c240c7e

**Expected behavior**
The Authors should only be listed once on the Item page.

**Comment by tdonohue** [comment]
@artlowel : Assigning this to you as it also effects Entities. It's probably a tiny mistake & easily fixed.

**Comment by artlowel** [comment]
The left one is a metadata-only field, the right one will resolve virtual metadata values and turn them in to links to the Person item page. Since the right field works also if there are no related Persons in the author field, I was about to just replace the left one with the right one and create a PR, but there's one difference:

The virtual metadata component can only work with a single field metadata field, while the metadata only component combines 3 (dc.contributor.author, dc.creator and dc.contributor).

So I propose add support for multiple fields to the virtual metadata component as well. This will take an estimated **2 hours**

**Comment by tdonohue** [comment]
@artlowel : That sounds reasonable & correct, with _one_ minor modification: I don't think we should include `dc.contributor` in the Author field by default (as general contributors are more often *not* authors).  Instead, it should just combine `dc.contributor.author` and `dc.creator`.  (A separate field could always be added at a later time to list Contributors, but I don't feel that's required in this ticket.)

Adding the estimate & assigning back to your team to work on when you are ready.
