### ISSUE TITLE
the community page shows all the collections instead to show only its child collections

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#122]
See for instance the 
https://dspace7-demo.atmire.com/communities/7669c72a-3f2a-451f-a3b9-9210e7a4c02f

all the three collections in the demo database are listed instead to show only the only one that belong to this community
http://dspace7.4science.it/dspace-spring-rest/#http://dspace7.4science.it/dspace-spring-rest/api/core/communities/7669c72a-3f2a-451f-a3b9-9210e7a4c02f/collections

**Comment by atarix83** [comment]
@artlowel 

Do we need that collections in the community page are paginated?

**Comment by tdonohue** [comment]
@atarix83 : In most situations the number of collections in a community is not extremely large. However, it might be nice to paginate them if the list is longer.  I'm not sure if there's a way to only show pagination if more than one page exists?

**Comment by atarix83** [comment]
@tdonohue yes pagination is hidden if there is only one page

**Comment by tdonohue** [comment]
Moved this back over into "Ready (to be worked on)" state/column.  There is an old PR (#127) that began an implementation of this and might be of reference. However, the Angular UI code has changed significantly since that early attempt.

Per today's meeting, we believe everything is in place on the REST API to be able to resolve this bug. Just needs a volunteer to claim.
