### ISSUE TITLE
Move item features is not working

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1232]
**Describe the bug**
The move item feature seems to be completely broken. The search collection is not working most of time, entering some query terms produce the expected REST call with results but nothing is shown to the user. Empty the input leads to a menu with some collections (1-step Workflow collection, 3-step..., abc) but selecting one of them and clicking move the loading indicator over the move button stay forever. Nevertheless, the item seems to be moved (I have moved https://demo7.dspace.org/items/e1a070d3-7f94-494c-9ff8-5fcaabdc4738 to the https://demo7.dspace.org/collections/536584ca-cd75-4016-b99c-3c83c399ca2f collection, it was in https://demo7.dspace.org/browse/title?scope=020c3471-ba82-4f37-a424-b66bbd3df7fa before

**Comment by tdonohue** [comment]
@artlowel : Assigning this to you to investigate, as it appears your team built this component initially. 

From what I see, this looks to be an Angular side issue.  There's a few issues;
1. First, the searchbox for a collection to move to is hard to use.  Typing something in it doesn't appear to work (or maybe it is case sensitive or requires the start of the collection name).  However, if I simply click "Enter" without any text, then I get a dropdown of the collections.  We may want to see if this can either be quickly fixed, or replaced with the same sort of Collection searchbox that appears elsewhere (e.g. in New Item or similar).
2. Second, once I select a Collection and click "Move", the form just "hangs".  Nothing happens in the UI, but I can see that the backend request succeeded.  If I manually exit the hung form, and browse back to the Item, I can see it was moved successfully.

All in all, the form "works" somewhat, but it's user experience is very difficult.  I'm flagging this as "high priority" as it's very difficult to get to work properly, and even then, the behavior makes the user think it's broken.

**Comment by artlowel** [comment]
For 1. I'd propose we get rid of the custom search code, and rewrite it using the same component we use when selecting the collection to create a new submission in. This has the added benefit of only returning collections the user has ADD permission in

The second issue is because rest returns an object without a `_links` section in response to the PUT that moves the Item. While we could fix this on the rest side, it's not strictly necessary to make the UI work. We can also just parse this as an UnCacheableObject to get the error to go away.

Fixing both issues will take an estimated **6 hours**

**Comment by tdonohue** [comment]
@artlowel : that sounds reasonable. I think we should just keep the fixes to the UI side initially, if possible.  If we find a need to do a later, minor update to the REST API, we can do that in a separate ticket.   I'll add the estimate & reassign back to you for your team
