### ISSUE TITLE
Upgrade @ngrx

### ISSUE THREAD

**Issue by wwelling** [DSpace/dspace-angular#126]
This will have to wait until https://github.com/codewareio/ngrx-store-freeze/issues/17 is resolved.

**Comment by artlowel** [comment]
I'd rather upgrade to @ngrx/platform as soon as possible. The ngrx team has been closing a quite a few issues I was watching with the notification that they're fixed in platform. 

Ngrx-store-freeze is just a tool that ensures objects stay immutable during development.
if you write a reducer, you should write tests for that immutablility anyway
ngrx-store-freeze just makes it easier to detect those issues early.

I say we leave store-freeze out now, and create an issue to put it back in as soon as it's up to date

**Comment by StevenLiekens** [comment]
Hey @artlowel the store-freeze tool is up to date with ngrx v4 now.

**Comment by artlowel** [comment]
Thanks for the heads up.

adding ngrx-store-freeze back in is trivial. But I can't seem to figure out an AoT compatible way to determine whether we're in production mode, in order to decide whether or not to add ngrx-store-freeze to AppModule's imports. 

I've tried all sorts of things, using it directly, using the getConfig() function, wrapping the imports in another function, wrapping the entire initialization of ENV_CONFIG in config.ts in a function … I keep running in to the `Error encountered resolving symbol values statically` error

@wellingWilliam can you have a look? You can find my current, broken branch [here](https://github.com/artlowel/dspace-angular/tree/ngrx-store-freeze-update)

**Comment by wwelling** [comment]
@artlowel I will try to make some time to look at this later today or tomorrow.

**Comment by wwelling** [comment]
This upgrade is complete. Closing now.
