### ISSUE TITLE
Upload button in bitstreams not working 

### ISSUE THREAD

**Issue by ivicadimitrovski** [DSpace/dspace-angular#1286]
The Upload button in bitstreams is not working:

![image](https://user-images.githubusercontent.com/44358971/128095886-d686afd9-075b-4fc5-91b3-d26aa9b92345.png)

**Comment by tdonohue** [comment]
@artlowel : Would someone on your team be available to look at this?  It's likely a small, but annoying bug, and it appears to be in 7.0

**Comment by tdonohue** [comment]
@artlowel : This has slipped through the cracks & it was also reported again on dspace-tech today: https://groups.google.com/g/dspace-tech/c/JvcxeV21tWk/m/WGQcriMHCgAJ

Any chance you or someone on your team could help get this fixed in 7.1?  It seems like uploads of files to existing Items just isn't working right now

**Comment by artlowel** [comment]
This will take an estimated **2 hours**. We should be able to get it in to 7.1, but we may miss the Sept 23rd PR deadline
