### ISSUE TITLE
Upgrade to Angular 12 (or 11)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1289]
Currently our codebase is on Angular 10.  As [Angular 10 LTS support ends on Dec 24](https://angular.io/guide/releases), we should look at upgrading to either Angular 11 or 12 in the 7.1 release.

If an upgrade to Angular 12 would prove difficult, simply getting us on Angular 11 is perfectly OK for 7.1.  However, if upgrading to Angular 12 is not much different than an Angular 11 upgrade, we may want to do both at once.

Use the Angular Upgrade guide for analysis: https://update.angular.io/

**Comment by tdonohue** [comment]
@artlowel : As mentioned in today's meeting, assigning to you / your team for estimation / analysis

**Comment by atarix83** [comment]
We suggest to start on work on this task during the 7.2 but to merge it only when the 7.2 has been released as a first task of the 7.3.
Basically we're suggesting to move this task to the 7.3 because an upgrade while many tasks are in progress may have a negative impact on the release time of the 7.2.

This could be a general rule also for all upgrading tasks in the future
