### ISSUE TITLE
Make submission form translateable

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1333]
Currently submission form fields are defined in single, fixed language on server side .xml file.
If your system is in several languages, there is no way to switch the label values along with rest of UI to desired language texts.

Either provide multiple fields on server-side config or enable translation upon building submission form.

**Comment by tdonohue** [comment]
@MarisArins : It's possible to create separate `submission-forms_[languagecode].xml` per supported language.  So, for example, the configuration `submission-forms_de.xml` will be used if German (de) is the selected language.  See also this section in the "Multilingual Support" docs: https://wiki.lyrasis.org/display/DSDOC7x/Multilingual+Support#MultilingualSupport-Localizationofsubmission-forms.xml

I agree this could be improved upon in the future, but basic support already exists.  I'm going to close this ticket as the feature already exists, even if it's a bit "clunky" because you have to define separate configs per supported language.

**Comment by MarisArins** [comment]
Thanks @tdonohue for pointing this out, I must have missed this feature !
