### ISSUE TITLE
dc.type facet not visible on MyDSpace page

### ISSUE THREAD

**Issue by f-rapp** [DSpace/dspace-angular#1342]
**dc.type facet missing on MyDSpace page**
I noticed that the dc.type facet is not among the sidebar facets of the My DSpace page [1], even though it is included in discovery.xml [2],[3] and there are actually items with a dc.type field in the workspace / workflow.

![grafik](https://user-images.githubusercontent.com/67266996/135588332-d4e3f0c3-1d04-4c29-b6ff-f46f4df84a95.png)
Screenshot of workspace view

At some point I got a glimpse of the facet (very shortly) and then it vanished.

[1] https://demo7.dspace.org/mydspace?configuration=workspace
[2] Workspace view https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L661
[3] Workflow view https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L734

**To Reproduce**
1. Log in as DSpace Submitter.
2. Go to MyDSpace Page
3. Create a submission with a dc.type field (e.g. article) and save it.
4. Check whether you can see the dc.type facet  https://demo7.dspace.org/mydspace?configuration=workspace
5. Create a submission with a dc.type field and submit it.
6. Check whether you can see the dc.type facet  https://demo7.dspace.org/mydspace?configuration=workflow

**Expected behavior**
The dc.type facet should be visible.

**Comment by tdonohue** [comment]
I've verified this bug exists.  Not exactly sure why the `dc.type` filter/facet (configured by `searchFilterType`) isn't appearing.   It's configuration looks valid (at a glance): https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L1685-L1692

Moving this to the 7.2 board to see if we can get to it, since this may also affect other facets.
