### ISSUE TITLE
Browse-by Subject does not allow to proceed to next pages once filtered

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1379]
In demo site open "browse by Subject" page : https://demo7.dspace.org/browse/subject

Initially browsing to Next and Previous pages work.

As soon as start point is set e.g. letter "C", navigation buttons have no effect.

Expected: 
At least navigation to Next pages should work.
P.S.  In Browse-by Title Previous/Next functions both work after setting start point.

**Comment by tdonohue** [comment]
Yes, I can reproduce this.  It appears that currently the letters act as a "filter" instead of jumping you to a page.  So, clicking "C" filters you to every subject starting with "C".  If there are more than 20 subjects starting with "C", you *will be able to go to the next page*. However, on that next page you'll just see more subjects starting with "C", and there's no way to move on to "D" or later letters.

So, this is a bug or a usability issue.  If these letters are meant to act as "filters", then it must be made more clear (e.g. "Browsing by Subject starting with 'C'") AND there must be a way to go back to the full list of subjects.  If these letters are meant to jump you to a letter within the list, then they must stop acting like filters.

**Comment by artlowel** [comment]
This will take an estimated **6 hours** to fix
