### ISSUE TITLE
Usability issue when editing uploaded bitstream within the submission

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1399]
**Is your feature request related to a problem? Please describe.**
We found out that editing the bitstream information during the submission has an usability issue. Indeed when the bitstream form is open the user frequently click the save button in the footer instead of the green save icon, believing in this way to have saved the bitstream form, while it doesn't happen. 
![Schermata da 2021-11-10 14-57-24](https://user-images.githubusercontent.com/2486489/141126991-1952bcb3-8f72-4a60-bfce-c3bbe3c79071.png)

**Describe the solution you'd like**
To avoid this issue we suggest to change the functionality in order to open the bitstream form in a modal so that it is clear how to save the changed information

**Comment by atarix83** [comment]
@tdonohue 

estimation for this task is about 6-8 hours

**Comment by tdonohue** [comment]
@atarix83 : This appears to be the same issue that @paulo-graca noted in #1382 .  He had created a separate smaller PR to simply move the save button to a more logical location, see #1383 

So, we should likely discuss which approach we feel is more appropriate here... *either* rebuild the section to use a popup modal for editing the bitstream & adding embargo info... *or* work to make the current section more user friendly / easier to understand.

**Comment by tdonohue** [comment]
Per today's meeting discussion, I now understand that @atarix83 's proposal here is the simplest solution, as this section of the submission process doesn't get saved by the "Save" button at the bottom of the page.

Therefore, I'll update this ticket with the estimate and assign back to @atarix83 for his team to work on.

Because we are fixing this issue with a modal, that means I'm going to close @paulo-graca 's smaller PR fix (sorry, Paulo, but I hope you'll agree that this larger fix is likely even better usability than just moving around the buttons).

**Comment by davidenegretti-4science** [comment]
Solved together with:
- #1337 
- #1359 
- #1399 
- #1415 
- DSpace/Dspace#7977
