### ISSUE TITLE
Scripts & processes without parameter

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#1445]
**Describe the bug**
When starting a process without parameter, Angular refuses to start the process. This happens when no parameter was selected (but there was one), or for a script without parameters

**To Reproduce**
1. Open /processes/new in Angular
2. Start a process without selecting parameters
3. The save button doesn't work

Steps to reproduce the behavior for a script without any parameter:
1. Open /processes/new in Angular
2. Start a process which doesn't have any parameters
3. The save button doesn't work

**Expected behavior**
Processes should also start without parameters

**Comment by artlowel** [comment]
This seems to be due to the fact that the [parameters input](https://github.com/DSpace/dspace-angular/blob/4d4e920f0d7e1cc0c92763e488692c8e54cc3d7d/src/app/process-page/form/process-form.component.ts#L38) in ProcessFormComponent is used in a number of array operations without ever checking that it's defined.

This can be fixed in an estimated **2h**

**Comment by tdonohue** [comment]
@artlowel : Sounds reasonable.  I've added the estimate & moved to 7.2.  Let me know if you want to claim it, or feel free to assign to yourself (and move to "in progress" column of our board) to claim it
