### ISSUE TITLE
Base Path support

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/dspace-angular#145]
As you build your app, using default settings, your project will work under:
http://localhost:3000/

But if you need to use a different base url like http://localhost:3000/angular/
You can use the simplest solution wich is to set the HTML5 `<base>` tag in the index.html file:
`<base href="/angular/">`

changes here can be a problem regarding the config settings in different environments. In a production environment you might not want to use the "/angular" base path.

Other solution is to use the APP_BASE_HREF, 
`<base ng_href="{{APP_BASE_HREF}}">`

and in the app module, include:
```
import { APP_BASE_HREF } from '@angular/common';

@NgModule({
providers: [
    { provide: GLOBAL_CONFIG, useFactory: (getConfig) },
    { provide: APP_BASE_HREF, useValue: '/angular/'}
  ],
```
I think this base path should be a supported enviornment setting (ServerConfig already includes the **baseUrl** property).

**Comment by artlowel** [comment]
There is already a property for that: [ui.nameSpace](https://github.com/DSpace/dspace-angular/blob/master/config/environment.default.js#L8) but a quick test shows that it doesn't work with any value other than `/` so that should be fixed.

**Comment by wwelling** [comment]
This has been resolved, but not closed. Closing now.

**Comment by atarix83** [comment]
I reopen this issue because not all works properly. If you add a property for that: ui.nameSpace, the images and the fonts that are not loaded.
Indeed `assets/images` and `assets/fonts` paths does not consider the namespace. 
Also the client.js is not found because we're using an absolute path here : 
https://github.com/DSpace/dspace-angular/blob/605c3524c813fd019005387eb643e3d00fa0ba6e/src/index.csr.html#L17
