### ISSUE TITLE
Adding/Editing Authorization page no longer found (404 error)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1456]
**Describe the bug**
It's no longer possible to edit authorizations from the UI (Community, Collection, Item or Bitstream).  All throw a 404 error

**To Reproduce**
1. Login as an Admin
2. Edit a Collection. Go to the Authorizations tab.  
3. Click "+ Add" -> 404 Error
4. Click Edit next to an existing policy -> 404 Error
5. Edit an Item -> visit "Status" tab & click "Authorizations".  -> Try to add/edit a policy -> 404 Error
6. Edit an Item -> Bitstreams tab -> Edit Bitstream -> "Edit Bitstream's policies" -> Try to add/edit policy -> 404 Error.

**Expected behavior**
Obviously, this all worked in 7.1.  Something must have broken these links accidentally.

**Comment by artlowel** [comment]
This is likely due to the use of the "legacy" link resolution [here](https://github.com/DSpace/dspace-angular/blob/7a1b98ce838279e9e911316f7adbd433aa10091c/src/app/shared/resource-policies/resource-policies.component.ts#L284) and [here](https://github.com/DSpace/dspace-angular/blob/7a1b98ce838279e9e911316f7adbd433aa10091c/src/app/shared/resource-policies/resource-policies.component.ts#L299).

I'll try to create a PR later today
