### ISSUE TITLE
First time visit to an item leads to an "Invalid CSRF token" when attempting to store usage event

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/dspace-angular#1486]
**Describe the bug**
When you visit an community/collection/item page for the very first time (as in your first page on a repository) the POST to the "/server/api/statistics/viewevents" leads to a 403 with the following message:

> Access is denied. Invalid CSRF token.

**To Reproduce**
1. Install something like "[Clear Session](https://chrome.google.com/webstore/detail/clear-session/maejjihldgmkjlfmgpgoebepjchengka)" or similar
2. Then visit a random item on the DSpace 7 demo site
3. Clear the sessions completely
4. Open up a network tab
5. Refresh the item page, at this point you are basically visiting the repo for the first time, no previous sessions or cookies, ...
6. The POST to the "/server/api/statistics/viewevents" WILL fail with a 403.

Ps: You CANNOT reproduce in an anonymous browser window, for whatever reason I do not get the issue there. 

**Expected behavior**
The POST should work as it does for subsequent requests. As it stands now people coming from a random google page that visit the repo will not have their first hits registered as statistics.

**Comment by tdonohue** [comment]
Hi @KevinVdV : Just wanted to note why this seems to occur (as I've seen it as well)  

Unfortunately, you don't receive a CSRF token until the first `GET` request. In this scenario, I believe this `POST` happens almost immediately after (or at the same time) as the first `GET`... so when the `POST` occurs, the client hasn't received a CSRF token yet, and therefore doesn't send the CSRF with the first `POST`.

My only idea here would be to find a way to *delay* the first `POST` slightly until after the initial `GET` responds with the token. In general, maybe the `POST` for every `viewevent` should be delayed so that it doesn't occur until the `GET` for that event sends a response...that should ensure the `POST` always succeeds, as if the CSRF token is new or changed by the `GET`, then it'll send that updated CSRF token in the `POST`.

I admit, I'm not exactly sure how to implement this on the Angular side, but I *think* that's what's happening here.

**Comment by tdonohue** [comment]
@benbosman : Another older ticket previously assigned to you / your team.  Do you want this to remain assigned to Atmire for 7.5, or should I unassign?

**Comment by tdonohue** [comment]
Closing, as this was a duplicate of https://github.com/DSpace/DSpace/issues/9236 which has been fixed.
