### ISSUE TITLE
Disabling preboot doesn't work on production mode

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1522]
**Describe the bug**
When trying to run the application in production mode with preboot disabled doesn't work. A white page is displayed with the following error

![Schermata da 2022-02-15 09-11-35](https://user-images.githubusercontent.com/2486489/154020252-ddef339c-3765-4b09-9f7e-b15b0f3b41a3.png)

It seems the default configuration is not loaded when preebot is disabled

**To Reproduce**
1. disable preebot in your config.prod.yml : 
``` 
universal:
  preboot: false
  async: true
  time: false
```
2. Run application with `yarn start`

**Expected behavior**
The application should work also when preebot is disabled

**Comment by tdonohue** [comment]
@atarix83 : This failure is because the `universal` settings were removed from the runtime configuration in #1437.  They are now hardcoded into the default `environment.ts` files (loaded by `angular.json`), and are not read from `config.*.yml`. 

Here's where you find the Universal settings now:
* https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.ts#L12
* https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.test.ts#L9
* https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.production.ts#L7
* Defaults at https://github.com/DSpace/dspace-angular/blob/main/src/config/default-app-config.ts

I admit, I'm not sure if these `universal` configurations can even be _changed at runtime_... if not, then they cannot be supported in the YAML configs.  Additionally, I like this change to remove them from the main `config.*.yml` configs as it  **highly discourages** anyone from turning off Angular Universal, as doing so obviously breaks SEO.   

@wwelling : since you moved this configuration in #1437,  any thoughts on this?

**Comment by atarix83** [comment]
@tdonohue @wellingWilliam 

I tried to disable it also by changing the default-app-config.ts and the problem is the same. So currently the application doesn't work if preboot is disabled and configuring it by using the config.prod.yml works as I expected.

For what concerning if should be possible to change this options in the yaml files we think that it should. Even if is highly discourages in our opinion we should avoid forbidding to change it by using the configuration files

**Comment by wwelling** [comment]
@atarix83 just to be clear, you want to be able to build a production distribution with preboot (universal) disabled?

**Comment by wwelling** [comment]
Turning off preboot as @tdonohue said can only be done in environment.js before compile. 

It is not possible at runtime without recompile and restart the node server. 

https://github.com/DSpace/dspace-angular/blob/main/server.ts#L174

It was not included in the default runtime config.

https://github.com/DSpace/dspace-angular/blob/main/config/config.example.yml

It was an oversight to not remove it from the [default-app-config.ts](https://github.com/DSpace/dspace-angular/blob/main/src/config/default-app-config.ts#L23). The reference to the app config at runtime should not be using these properties. They should only be used from environment, and I believe this is only in the server and the main browser file to support HMR.

**Comment by wwelling** [comment]
@atarix83 please try disabling here https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.production.ts#L8 and rebuilding production dist.

**Comment by wwelling** [comment]
There is a minor bug making both environment.ts and default-app-config.ts be set to false.

https://github.com/DSpace/dspace-angular/blob/main/src/config/default-app-config.ts#L24

This should only be in the environment.ts as it is a build time config and not able to be changed without rebuild. Will have PR shortly to remove from default-app-config.ts.

**Comment by wwelling** [comment]
The error above is from a built distribution where the [server](https://github.com/DSpace/dspace-angular/blob/main/server.ts#L170)is using preboot true and the [main browser](https://github.com/DSpace/dspace-angular/blob/main/src/main.browser.ts#L50) is using preboot false. The main browser is using an environment that has been extended from runtime config as the server is using the static environment defined at build time.
