### ISSUE TITLE
Delete button Not Working

### ISSUE THREAD

**Issue by SrinivasRao17** [DSpace/dspace-angular#1563]
Hello Team,

We have installed DSpace 7.1 version and we are not able to delete items. When we click on Delete its not working, wherein we are able to Withdraw the Item. Need your suggestion how can we activate or solve this Delete issue in 7.1 version. 

Please help us to resolve this issue. 

Thanks & Regards,
Srinivas Rao

**Comment by artlowel** [comment]
This issue was reported before: https://github.com/DSpace/dspace-angular/issues/1481 and https://github.com/DSpace/dspace-angular/issues/1501

It was fixed in version 7.2.

If you need to fix it in 7.1 you can try to cherrypick the commits in the PR that fixed it: https://github.com/DSpace/dspace-angular/pull/1503/commits

**Comment by SrinivasRao17** [comment]
@artlowel Thanks for the update and links. I will try to fix delete option with the provided link. Thanks!!
