### ISSUE TITLE
Enabling "Relationship" tab in Edit Item

### ISSUE THREAD

**Issue by SrinivasRao17** [DSpace/dspace-angular#1589]
Dear All,

Could you please help me out how do we enable Relationship tab in Edit Item. When i try to access relationship tab it gives an  message "Add 'dspace.entity.type' metadata to enable relationships for this item". Please find the attached screenshot for your reference. Thanks!!

Unable to upload screenshot

**Comment by tdonohue** [comment]
@SrinivasRao17 : If you have simple usage questions, please ask them using one of our Support options listed at https://wiki.lyrasis.org/display/DSPACE/Support  

This GitHub ticketing system is only for suspected bugs or submitting feature/improvement requests.  Since this is a question I'm closing it. Please use our mailing lists or similar (see that Support page).  Thanks.

(As a sidenote, I'm pretty sure that message is telling you what you need to know. That particular Item must not have a "dspace.entity.type" metadata field.  It's impossible to add a Relationship to default Items...they must be entities (with a valid dspace.entity.type) to create a relationship.)
