### ISSUE TITLE
MyDSpace Status search facet doesn't update to reflect user changes to task status 

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1610]
**Describe the bug**
The "Status" search facet on MyDSpace (workflow configuration) doesn't update when a workflow Item's status is changed. 
The resulting mismatch is very noticeable when there are only a few workflow Items and could be confusing.

**To Reproduce**
1. Go to https://demo7.dspace.org/mydspace?configuration=workflow (& make sure at least one workflow Item exists)
2. Open the "Status" facet
   * The listed facets should correspond to the search results
4. Toggle the task's claimed/pooled status
   * **The "Status" facet will stay unchanged**

**Expected behavior**
The "Status" facet should reflect the changed state of workflow Items.

**Comment by tdonohue** [comment]
Possible duplicate ticket in #1736 (which notes a similar issue with counters in the sidebar).  These two tickets likely should be claimed together as they might be fixed easily at the same time.

**Comment by tdonohue** [comment]
Assigning to @corrad82-4s and adding a zero hour estimate as this bug ticket will be fixed as part of #1736

**Comment by corrad82-4s** [comment]
Hi @tdonohue , as per what commented in https://github.com/DSpace/dspace-angular/issues/1736#issuecomment-1209126231, this issue seems to be more complex than expected. 
A solution could be force update of facets in case of task status changes, but we cannot be sure facets reflects what is displayed among search results. What if, for example, between task status change and refresh, 10 new items joined the pool? They would be counted in facets, but not visible in page. Ideally, the whole page would have to be updated, but this would void what done recently to avoid full page reload. 

What about a "warning" message, about possible "outdated" facet values? Leaving to user the decision between keeping outdated facets or reloading the page (e.g. with a button)?
