### ISSUE TITLE
Mirador Build Fails

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#1611]
**Describe the bug**
The Mirador viewer build fails with the following: 

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }
resolve 'url' in '/Users/michaelspalti/willamette/dura_space/dspace-angular/node_modules/normalize-url'
```

We need to add a webpack polyfill to devDependencies. Also, we should update `webpack.mirador.config.ts` to use the `copy-webpack-plugin` since it's already in our devDependencies and a good replacement for `html-webpack-plugin`

**To Reproduce**
1. execute yarn run build:mirador 

**Expected behavior**
The mirador build should succeed and the files copied to dist.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
@mspalti : Would you be willing to work on this?  I'll add it as high priority to the 7.3 board, since obviously we didn't mean to break this.

This also shows that we need to find a better way to test this automatically (to avoid breaking it in the future).  Perhaps we should consider adding a quick build of Mirador into our CI process (https://github.com/DSpace/dspace-angular/blob/main/.github/workflows/build.yml)?  It might be something we simply put at the end of the CI for now.  

(Eventually, we might also consider whether to add Cypress e2e tests for this...but that'd require more work as it'd mean spinning up Cantaloupe in Docker in our CI environment.)

**Comment by mspalti** [comment]
I'll work on it. It should be a quick fix.

**Comment by mspalti** [comment]
@tdonohue , I agree that we should consider adding the Mirador build to CI. I don't know if we want that in the PR I just submitted. If it's just a matter of adding the yarn command at the end of the file that would be easy enough!
