### ISSUE TITLE
Clearing bitstream description leaves and empty dc.description entry for the bitstream

### ISSUE THREAD

**Issue by amgciadev** [DSpace/dspace-angular#1612]
**Describe the bug**
Clearing description of bitstream via UI leave an empty dc.description metadata entry. Is this intentional rather than fully removing the entry?

**To Reproduce**
1. Edit any bitstream via the Edit item section
2. Clear the description
3. Check via the API HAL browser
Example item: https://api7.dspace.org/server/api/core/bitstreams/5415158c-ee79-4313-b150-296b6c1b5556/ and https://demo7.dspace.org/items/ca791d64-2dff-47ab-ad80-a42f8c5756cb/edit

**Expected behavior**
The metadata entry for "dc.descrition" is fully removed from the bitstream's metadata.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
@amgciadev : I believe this is expected behavior (if I'm understanding correctly what you mean by "clear the description"). 

If you set the dc.description to an empty value, then the dc.description field will be kept on the Item and display no value.

However, if you click the delete button next to the dc.description field, then it will be removed entirely.  After clicking delete you must click "Save" for the changes to take effect.  Here's a screenshot which shows the delete button to press, after which Save will enable and you must click Save to remove the field.

![edit-metadata](https://user-images.githubusercontent.com/483997/167441587-38e52083-7c2e-4cb2-b86a-aaaf0d83f031.png)

**Comment by tdonohue** [comment]
@amgciadev : Thanks for clarifying.. I had misunderstood obviously.

This does look like a very minor bug.  I agree that ideally the `dc.description` field should not even appear for a Bitstream if it is cleared out.  That said, I don't think this impacts the behavior of the UI in any significant way.  It's just somewhat useless information.

Nonetheless, I'll pull this over to our board and see if we can find a way to fix this.

**Comment by md1222** [comment]
@tdonohue 

We can work on this issue and the estimated time is around 4 hours.
Please let me know how to proceed.

**Comment by tdonohue** [comment]
@md1222 : Sure, we welcome anyone to contribute to DSpace.  Just to clarify though, is the "we" you are referencing Vir Softech?  If this is a planned contribution from a Service Provider, it's obviously important for me to understand which Service Provider is doing the work.

In any case, we just ask that you create a PR that aligns with our code contribution guidelines documented in our GitHub repos: 
* Guidelines for Angular UI: https://github.com/DSpace/dspace-angular/blob/main/CONTRIBUTING.md
* Guidelines for backend: https://github.com/DSpace/dspace/blob/main/CONTRIBUTING.md

Thanks!

**Comment by md1222** [comment]
@tdonohue 

Thank you for your reply sir and yes I am referring to Vir Softech.

**Comment by md1222** [comment]
@tdonohue 
I request you to please review the change #2112

**Comment by tdonohue** [comment]
@md1222 : That PR #2112 has been added to our 7.6 board.  It will have reviewers assigned. However, I will note that, since we just finished 7.5, the next week (or so) will be concentrated on planning out 7.6. This means reviews may move slower for the next few weeks.  I'll still do my best to try and get you feedback as soon as I can .  Thanks for the contribution & we will work to get it reviewed soon.
