### ISSUE TITLE
Problem submitting form, when the same field is required and repeated with different visibility settings for different types

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#1655]
I use backend and frontend versions 7.3-snapshot, after the type-bind submission form feature was included.

**Describe the bug**, 
**To Reproduce**
Given the following submission form definition:

```
<form name="test">
    <row>
        <field>
            <dc-schema>dc</dc-schema>
            <dc-element>type</dc-element>
            <dc-qualifier/>
            <repeatable>false</repeatable>
            <label>Type</label>
            <input-type value-pairs-name="test_types">dropdown</input-type>
            <hint>Enter the type of the work.</hint>
            <required>You have to provide at least one type.</required>
        </field>
    </row>
    <row>
        <field>
            <dc-schema>dc</dc-schema>
            <dc-element>title</dc-element>
            <repeatable>false</repeatable>
            <label>Title</label>
            <input-type>onebox</input-type>
            <hint>Enter the title.</hint>
            <required>You have to enter a title.</required>
        </field>
    </row>
    <row>
        <field>
            <dc-schema>dc</dc-schema>
            <dc-element>title</dc-element>
            <dc-qualifier>subtitle</dc-qualifier>
            <repeatable>false</repeatable>
            <label>Subtitle</label>
            <type-bind>a,b</type-bind>
            <input-type>onebox</input-type>
            <hint>Enter the subtitle.</hint>
            <required>You have to enter a subtitle.</required>
            <visibility>workflow</visibility>
        </field>
    </row>
    <row>
        <field>
            <dc-schema>dc</dc-schema>
            <dc-element>title</dc-element>
            <dc-qualifier>subtitle</dc-qualifier>
            <repeatable>false</repeatable>
            <label>Subtitle</label>
            <type-bind>c</type-bind>
            <input-type>onebox</input-type>
            <hint>Enter the subtitle.</hint>
            <required>You have to enter a subtitle.</required>
        </field>
    </row>
</form>
```

You can deposit type a and type b without any problem. But if you try to deposit type c, you will never succeed to submit the form, because despite the fact that you entered a subtitle, it seems, that it will expect you also to fill the invisible subtitle field.

While you filled in all the fields, you will get this error message:

> Deposit cannot be completed due to errors in the form.
> Please fill out all required fields to complete the deposit.

![Screenshot from 2022-05-16 14-57-40](https://user-images.githubusercontent.com/8408850/168598991-560cf811-c009-47de-b978-cc15cc3f9f4f.png)

**Expected behavior**
You should also be able to submit the form for type c.

**Related work**
This bug is related to the type-based submission form feature.

**Comment by tdonohue** [comment]
I think this is an unexpected use case right now to duplicate the same field with different settings.

I'm not sure the submission form can currently support duplicated fields (in this example configuration there's two `dc.title.subtitle` fields, which only differ in their "visibility" setting).  I think we may be expecting field names (`dc.title.subtitle`) to be unique in a submission form...which may explain why the *first* field of this name in the form is the one which ends up being "required" (and why you don't hit this same problem when the first field is filled in but the second is skipped)

All that said, it might be possible to work around this unique field assumption by improving the validation code to better ignore fields which are not currently "visible" in the form. So, even though we have two duplicative fields, we'd need to see if we can enhance validation to only validate the field which is currently visible (based on the `<type-bind>` value).

**Comment by MW3000** [comment]
Yes, it is a pretty essential functionality. You have fields that are repeatable/visible/required for some types, not-repeatable/not-visible/not-required for others or have different labels for different types. So you will have the same field definition repeated one or more times in the same form with different type-binds.

**Comment by kshepherd** [comment]
hm. this will be a bit tricky.. unlike previous DSpace  versions where metadata values could be 'skipped' (because the metadata is completely cleared and readded every time), here the validate process has to remove metadata values from an in-progress item. We can't tell which metadata value was added by which submission form input at that stage, it's just a value.

One possibility:
While iterating DCInputs+fields, before deciding whether to remove metadata values, iterate over all DCInputs and check to see if any input with the same field allows for the current publication type. if it does, leave all values there. If not, remove all values.

Or, more efficiently do one pass over DCInputs before moving onto the main loop, and construct a List which can be used to look up by type name.

This isn't perfect. It would still be possible, while switching between different types that have different input rules applied to them, to get repeated values in even though the last chosen type doesn't allow repetition. (how would we know which value to leave in the item? we have to strip them all, or leave them all).
We should be able to enforce required and 'is this allowed' though.

Was this supported in DSpace 6? I'm guessing so?

**Comment by kshepherd** [comment]
My attempted fix at : https://github.com/DSpace/DSpace/pull/8296
