### ISSUE TITLE
Unable to Add field with new name

### ISSUE THREAD

**Issue by SrinivasRao17** [DSpace/dspace-angular#1659]
**Is your feature request related to a problem? Please describe.**
We are unable to add new field in the Item list (dc.description.abstract) we need to add new field with "dc.calculation"

**Describe the solution you'd like**
Is there any API that we need to add in the backend for adding dc.calculation in the item list.

**Describe alternatives or workarounds you've considered**
I need help from your end to add this item

Could you please help me out so that i can add or modify item list in the fields. Thanks!!

**Comment by tdonohue** [comment]
Closing as question is unclear & seems to be a usage question rather than a bug report or feature request. This ticketing system is only for bug reports / new feature requests.  Please use one of our Support options to ask questions: https://wiki.lyrasis.org/display/DSPACE/Support

At a basic level, new metadata fields can be added from the UI when logging in as an Admin.  Just go to the sidemenu & select "Metadata -> Registries".  This will show you all metadata schemas currently available, you can select any and add new fields.  If you need more information, feel free to ask more detailed questions using one of the support options listed above.

**Comment by SrinivasRao17** [comment]
Thanks a lot for the update. :)
