### ISSUE TITLE
Allow for Processes to be deleted from the User Interface

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1660]
**Is your feature request related to a problem? Please describe.**
Processes currently cannot be deleted from the User Interface, even though `DELETE` is possible from the REST API: https://github.com/DSpace/RestContract/blob/main/processes-endpoint.md#execution-deletion

Without this feature, the list of processes will just grow and grow, even though they can be deleted via the REST API.

**Describe the solution you'd like**
At a minimum, we should allow individual processes to be deleted (add a delete button when viewing a process).  

It also might be nice to provide a way to bulk delete processes, either via a series of checkboxes, or via a new `processes_cleanup` script which can delete all processes which are greater than ___ days old.

**Comment by mwoodiupui** [comment]
I'd say that the ability to automatically remove stale process debris, rather than wasting a sysadmin's time doing this manually, is not nice but necessary.

**Comment by artlowel** [comment]
I'd propose to add a delete button to the process detail page, and a trash can icon in the process overview list. There isn't much difference between checking a bunch of checkboxes, and clicking the same number of trashcans. 

I'm hesitant to add a "delete all" button at the top, because there's currently only an endpoint to delete processes individually so that would mean the UI would have to fetch them all first, which is a bad idea. Besides in practice you usually don't want to delete them all anyway, but only all processes matching a certain query (using some script, or older than some date, etc). So that's perhaps something to look at in conjunction with a query feature on the process overview page later on.

I also like @mwoodiupui's idea of auto-expiring processes after a set duration. But that would be (almost) entirely a backend feature, so it should be moved to that repo.

Atmire would like to work on the delete buttons in the UI, as I described above though. That would take an estimated **8 hours**

Since @tdonohue is on holiday, I'll assign this to myself
