### ISSUE TITLE
Missing information about failed query against external providers

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#1678]
**Describe the bug**
While working at rest issue  [#8327](https://github.com/DSpace/DSpace/issues/8327) we noticed that, in case of error during external system query, user is not properly informed about this failure.

**To Reproduce**
1. login to dspace7 and go to MyDSpace
2. start a new Publication submission from external source
3. enter a query string and select “Pubmed” as external source
4. In case query fails with a 500 backend error, following page is displayed

![image](https://user-images.githubusercontent.com/70699836/172389097-9a7433cf-8139-484c-98ab-3c948f3dcc4a.png)
![image](https://user-images.githubusercontent.com/70699836/172389154-de315d69-85af-40fa-bff7-b1e3af36ddfa.png)

**Expected behavior**
In case of rest error (500 in this example) A message indicating that search went in error.  We believe current behavior could be improved, and such improvement would lead to a little UX improvement in case of failure of a query for live import towards an external system.

We, 4Science, can take in charge this improvement, our work estimation is 2/4 hours.

**Comment by tdonohue** [comment]
This ticket seems somewhat related to https://github.com/DSpace/DSpace/issues/8358, but it might be more specific to a single area of DSpace.

I'm not against this idea, but I think we need to be cautious.  As noted in that other ticket, the REST API was designed to _not return_ error stacktraces in order to avoid "information exposure" (it can be a security issue to share full exceptions as it can give attackers too much information about the underlying system).

All that said, I do agree that there are specific areas where we can and should be providing a more detailed error message.  This seems like one that would qualify.  I just want us to try to avoid information exposure (see https://lgtm.com/rules/6780073/)

**Comment by abollini** [comment]
we are almost ready to open the PR, it was a bit harder than expected, it took 8 hours
