### ISSUE TITLE
False positives when matching theme based on handle

### ISSUE THREAD

**Issue by BrunoRoemers** [DSpace/dspace-angular#1710]
**Describe the bug**
DSpace 7 has the ability to switch themes based on the handle of the current item/collection/community (or the handle of one of their parents). Whether a theme is a match, is ultimately [decided here](https://github.com/DSpace/dspace-angular/blob/main/src/config/theme.model.ts#L90), however this logic contains a bug.

Example: given `dso.handle = http://hdl.handle.net/123456789/123123` and `theme.config.handle = 123456789/123`, the theme should not be matched, but it will be matched because: `http://hdl.handle.net/`**`123456789/123`**`123`.

**To Reproduce**
1. configure a theme that matches on a handle, e.g. `123456789/123`
2. create an item and edit the handle such that it equals the theme handle + something extra, e.g. `123456789/123123`
3. visit the item and observe that the theme is active
    - you can inspect the Redux state with [this extension](https://addons.mozilla.org/en-US/firefox/addon/reduxdevtools/) to see which theme is active (`theme.currentTheme`, action of type `dspace/theme/set` has been [dispatched here](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/theme-support/theme.service.ts#L141))

**Expected behavior**
The theme should NOT be active, because the theme handle does not match the item handle.

**Suggestion**
Add a utility function that given any string, returns a handle (in some canonical format) or undefined (if the input string could not be parsed). This function would become the single source of truth of what constitutes a valid handle.

**Comment by mwoodiupui** [comment]
Yes, the class `HandleTheme` looks unfinished:  it takes `any` rather than `DSpaceObject` like the other matchers, and `includes` is clearly the wrong test for "will match the community, collection or item with the given handle" which calls for equality.  (https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration#UserInterfaceConfiguration-ThemeSettings)

**Comment by ybnd** [comment]
Note that
* `HandleTheme.matches()` uses `any` because `handle` is not a `DSpaceObject` property in Angular right now, it is a getter on _some_ DSO subclasses
* ... and that getter returns `dc.identifier.uri` instead, which may be changed & is therefore not even guaranteed to reflect the actual handle
* This is why `.includes()` was used. If we want leave the "handles" as is we'd want to use `.endsWith()` to match it fully.

I'm not exactly sure how we got to this weird situation, but I think this issue is a good opportunity to actually include `handle` in the Angular `DSpaceObject`, then we can solve all of this way more cleanly

**Comment by tdonohue** [comment]
@artlowel : I'm OK with bumping this up to high & letting it into 7.4 since it's a small task.  Assigning to you & adding the estimate.
