### ISSUE TITLE
The wording of the English text on the "Forgot Password" page is incorrect

### ISSUE THREAD

**Issue by Ianvdl** [DSpace/dspace-angular#1716]
**Describe the bug**
The text on the Forgot Password page (visible at https://demo7.dspace.org/forgot) says:

"Enter Register an account to subscribe to collections for email updates, and submit new items to DSpace."
and
"This address will be verified and used as your login name. "

I suspect these are oversights since the text is the same as the ones for registering an account. The offending lines are at https://github.com/DSpace/dspace-angular/blob/fd356d4ca78bc3cbb8a5952c67ea0cf7566b1fae/src/assets/i18n/en.json5#L1465-L1473

**To Reproduce**
Load the Forgot Password page. 

**Expected behavior**
The text should reflect the functionality provided by the page.

**Related work**
None at the moment. I'm happy to modify src/assets/i18n/en.json5 to provide new wording, if this is something you'd like to have fixed.

**Comment by tdonohue** [comment]
@Ianvdl : If you are willing to provide a PR, please feel free to just create it.  That's the quickest way to get small fixes done (as otherwise this ticket will wait for a different volunteer to step forward and fix it).  If you create a PR, please link it by to this ticket by saying it "Fixes [issue-id]" (where [issue-id] in this case is `#1716`.   Then, I can make sure your PR is reviewed to be included in the next release. Thanks!

**Comment by Ianvdl** [comment]
@tdonohue Thank you for your guidance. I've created a PR for the fix, please let me know if the wording is in order.

As an aside, does the project encourage just creating a PR in the future for small fixes, or would you prefer I make an issue first?

Thanks.

**Comment by tdonohue** [comment]
@Ianvdl : For small typos or fixes, a PR (without an issue ticket) is perfectly OK.  We only request an issue ticket if it's a bug which may require detailed explanation and/or screenshots to show others how to reproduce it.  Thanks for your PR, I'll pull it over to our board to try and find a reviewer.
