### ISSUE TITLE
The "citation_pdf_url" meta tag download link doesn't use https

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/dspace-angular#1721]
**Describe the bug**
When running angular on server side & having an apache in front of it to ensure https access the "citation_pdf_url" shows as http.

This leads to an issue where users are not able to download publication file(s) via links from Google Scholar in Google Chrome and Microsoft Edge browsers.

**To Reproduce**
Checkout the following url's:
* https://unsworks.unsw.edu.au/entities/publication/fd08fc25-48dc-40bc-b673-deb232f31faa
* https://demo7.dspace.org/entities/publication/1974d7d3-9648-4dbe-b083-56374f5314e4

**Expected behavior**
The "citation_pdf_url" should be in https if the server is running on https.

**Comment by artlowel** [comment]
The cause of this issue seems to be that the [ServerHardRedirectService](https://github.com/DSpace/dspace-angular/blob/d0771715b66de256ca69203cbc5b6a5a9caf5a1d/src/app/core/services/server-hard-redirect.service.ts#L71) uses the protocol and the host of the incoming request to determine the origin. So if you're not using https on the angular server directly but instead put a different server in front of it and redirect internally over http this will be wrong.

I suggest adding an optional config property, to set the origin. If it's missing we fall back to the current code.

This can be done in 2 hours. Atmire would like to claim it.
