### ISSUE TITLE
Missing translations in publication search modal dialog (publications of author)

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#1728]
## Describe the bug

missing translations of `submission.sections.describe.relationship-lookup.title.isPublicationOfAuthor` and `submission.sections.describe.relationship-lookup.search-tab.tab-title.isPublicationOfAuthor`

![image](https://user-images.githubusercontent.com/952735/179257728-1b4cc6e8-311c-4487-b30f-f58d7c0e2475.png)

## To Reproduce

1. enable "configurable entites" feature
2. establish a "person" collection
3. assign default "Person" submission form to collection created in step 2
4. open submission form of collection created in step 2
5. click on publication lookup button (button with fa-search icon)

## Expected behavior

both keys are translated

**Comment by tdonohue** [comment]
Hi @saschaszott : If you find missing translation keys of this sort, we'd welcome a PR (especially if you know or can figure out what it should say).  The various translations of the DSpace UI are all provided by volunteers...so they do occasionally get outdated & require updates.  It seems this one likely is only missing those keys because those keys were added *after* the initial translation was contributed to DSpace.  So, if you have any updates to the translation to suggest, we'd welcome a PR!  Otherwise, we'll have to wait to find a volunteer who can help us translate these keys.

**Comment by saschaszott** [comment]
Hi @tdonohue , the two translation keys mentioned above are still missing in the "default" i18n file (`en.json5`).

**Comment by tdonohue** [comment]
Added zero hour estimate as this will be included in the fix for #1729.
