### ISSUE TITLE
Auto-assigned workflow tasks include a broken "return to pool" button on /mydspace

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1739]
**Describe the bug**
The "Return to pool" button still shows up even though the WFI was assigned automatically and can't be returned to the pool.

[We make the assumption that _all_ claimed tasks work with a pool](https://github.com/DSpace/dspace-angular/blob/4da017a0ee051a361fac44482c20a05ff5253146/src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.ts#L47-L51), but this is not the case for most user assigning ations:
* [`AssignAction`](https://github.com/DSpace/DSpace/blob/31f706042f098e2b78cfcc9a637f5852f8d307a1/dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/AssignAction.java#L64-L64)
* [`AssignOriginalSubmitterAction`](https://github.com/DSpace/DSpace/blob/31f706042f098e2b78cfcc9a637f5852f8d307a1/dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/AssignOriginalSubmitterAction.java#L66-L66)
* [`AutoAssignAction`](https://github.com/DSpace/DSpace/blob/31f706042f098e2b78cfcc9a637f5852f8d307a1/dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/AutoAssignAction.java#L165-L165)
* [`InheritUsersAction`](https://github.com/DSpace/DSpace/blob/31f706042f098e2b78cfcc9a637f5852f8d307a1/dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/InheritUsersAction.java#L64-L64)

It's not immediately clear to me how we would address this, the first thing that comes to mind would be to
* not add the "return to pool" to claimed tasks button by default (also: "claimed" is confusing)
* instead, include `return_to_pool` in REST depending on the `usesTaskPool` value of the _preceding user assignment action_

**To Reproduce**
Go through the steps listed in [#8400](https://github.com/DSpace/DSpace/pull/8400)
In the final step, the workflow task that was automatically assigned to the original submitter will include the "Return to pool" button. Clicking on it results is a HTTP 500 error.

**Expected behavior**
Workflow tasks that don't have an associated task pool should not give the user the option to return them to the pool.

**Related work**
https://github.com/DSpace/DSpace/pull/8400

**Comment by tdonohue** [comment]
Because this bug doesn't impact the ["defaultWorkflow"](https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/workflow.xml#L27-L35) workflow tasks/actions (i.e. the default, I think it's directly related to #770 (and https://github.com/DSpace/DSpace/issues/2841)... The root issue here is that currently (as of 7.3), the "defaultWorkflow" behavior is somewhat hardcoded into the codebase. Other steps/actions do not fully work as they cannot be loaded dynamically from the backend.

So, I'm going to move this over to the Tier 3 board alongside those tasks.  I think it needs to be solved as part of that effort.

**Comment by tdonohue** [comment]
Closing, fixed by #2039 (which closed related #770)
