### ISSUE TITLE
Make the number of communities on the home page configurable

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1749]
**Is your feature request related to a problem? Please describe.**
In DSpace 7, there are only 5 top-level communities listed on the home page, https://demo7.dspace.org/home. When the user clicks on the next page they see the next 5 communities. This is too slow. 
<img width="512" alt=" DSpace7_home_communities" src="https://user-images.githubusercontent.com/13037168/182934132-f37b7f9c-c65f-4c19-9149-3a6c433ba090.png">

In DSpace 6 XMLUI, all the top-level communities are listed on the home page, https://demo.dspace.org/xmlui/, which helps the user immediately find the right one. Administrators, too, want to see the entire list without multiple clicks.
<img width="1034" alt="DSpace6_XMLUI_home_communities" src="https://user-images.githubusercontent.com/13037168/182934163-acff33cb-f28b-4415-bc03-d28fac09ee6f.png">

**Describe the solution you'd like**
One solution would be to make the number of communities per page configurable with a number, or perhaps, an option, "all." Since the time to load the home page in DSpace 6 XMLUI is acceptable, I don't think a large number or "all" would be a problem and would certainly be less time than waiting for multiple pages. 

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
Agreed, this should be configurable.  It appears to be hardcoded here: https://github.com/DSpace/dspace-angular/blob/main/src/app/home-page/top-level-community-list/top-level-community-list.component.ts#L57

This likely could be fixed in a similar manner to @mwoodiupui 's #1771.  It just needs a configuration to be added and used in that `top-level-community-list.component.ts`. 

Pulling this over to our 7.4 board in the hopes of a volunteer.  It seems like something that might be fixed very quickly.

**Comment by mark-cooper** [comment]
@tdonohue I've had a request for this and it seems straightforward enough that I'm happy to volunteer for it (and #1750).

**Comment by tdonohue** [comment]
@mark-cooper : Sounds great!  Please feel free to submit a PR when you are completed, and link the PR back to both tickets (Using "Fixes" or "Resolves" [keywords from Github](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
