### ISSUE TITLE
Make the number of communities in the Browse by Community page configurable

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1750]
**Is your feature request related to a problem? Please describe.**
In DSpace 7, there are 20 top-level communities listed on the Browse by Community page, https://demo7.dspace.org/community-list. When the user clicks on "Show More," this adds 20 more communities. This is slow for repositories with many top-level communities.
<img width="997" alt="DSpace7_community_browse" src="https://user-images.githubusercontent.com/13037168/182936175-7aea863c-6ac4-4a7e-b260-07a9d7b4befa.png">

In DSpace 6 XMLUI, all the top-level communities are listed on the Browse by Community page, https://demo.dspace.org/xmlui/community-list, which allows the user to immediately explore them all. Administrators, too, want to see the entire list without multiple clicks.
<img width="1004" alt="DSpace6_XMLUI_community_browse" src="https://user-images.githubusercontent.com/13037168/182936784-f6b7f6a4-715b-4a20-8afa-a8f5271035c1.png">

**Describe the solution you'd like**
One solution would be to make the number of communities per page configurable with a number and the option, "all." Since the time to load the collections page in DSpace 6 XMLUI is acceptable, I don't think a large number or "all" would be a problem and would certainly be less time than waiting for multiple clicks to load the entire list.

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by alawvt** [comment]
Thank you very much for working on these feature requests. Does changing a setting to 0 mean unlimited, as @mwoodiupui suggested? I don't see a comment about it.

**Comment by tdonohue** [comment]
@alawvt : No, unfortunately at this time there's no option for an "unlimited" value at this time & no immediate plans for that.

The pageSize values should be one of the valid "pageSizeOptions" listed here: https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/pagination/pagination-component-options.model.ts#L25   If they are not one of those values, then it'll be rounded to the nearest valid value.  As you can see in that list, the maximum you can choose is 100

This is purposeful as a value of "unlimited" is currently a bit dangerous in terms of performance.  If you have 500 top level communities and you attempt to load them all at once, the performance is very poor right now .  That's why currently we cap the max per page at 100.

**Comment by alawvt** [comment]
@tdonohue, Thank you for that explanation. The maximum value of 100 is certainly reasonable.
