### ISSUE TITLE
Make the number of bitstreams on the Item pages configurable

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1774]
**Is your feature request related to a problem? Please describe.**
In DSpace 7, at most 5 bitstreams appear in Simple and Full Item Views, e.g. https://demo7.dspace.org/items/03731881-2185-4baf-a6a8-1438a4d29dc8 and https://demo7.dspace.org/items/03731881-2185-4baf-a6a8-1438a4d29dc8/full.

In Simple Item View, "Show more" adds 5 more bitstreams to the list.
<img width="535" alt="DSpace7_simple_view_bitstreams" src="https://user-images.githubusercontent.com/13037168/185233339-5a5048f6-b2d0-463c-a3db-41b26801ec58.png">

In Full Item View, 5 bitstreams initially display. Clicking advances to the next page of 5 bitstreams.
<img width="1190" alt="DSpace7_full_view_bitstreams" src="https://user-images.githubusercontent.com/13037168/185234027-acd50794-a255-47af-8de9-d133d6ec5b76.png">

**Describe the solution you'd like**
In DSpace 6 XMLUI, all bitstreams appear in Simple and Full Item Views. Please implement this or a configuration to set the initial and incremental number of bitstreams shown on these pages.

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
Agreed, this should be configurable.

Currently, it appears to be hardcoded to '5' in this component:
https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/simple/field-components/file-section/file-section.component.ts#L38

Changing that to be configurable should not be difficult, and it'd likely be similar to what was done in #1771.   I'd recommend making this configurable instead of defaulting to display all bitstreams, as I suspect different sites will want different behaviors.

Since this is a public page, I'll flag this as `high priority` and pull it over to the 7.4 board.  I think this could be implemented by a novice developer & might be done alongside similar tickets like #1750 and #1749
