### ISSUE TITLE
Reassign submitter email address for Request a Copy

### ISSUE THREAD

**Issue by VTOpenLib** [DSpace/dspace-angular#1785]
**Is your feature request related to a problem? Please describe.**
I would like to change the email address to which the "request a document" email is sent. Why? If someone leaves the organization, has tasks reassigned, and someone else becomes in charge of responding to requests for Admin-only files uploaded to a record item, there is currently no way to change the email address to which these access requests are emailed. It is important to authenticate people that request these items, so I cannot just make them open access (especially when they are things like testbanks to which students should not have access.)

**Describe the solution you'd like**
I would like to be able to edit the submitter email address to which the "request for document" email is sent so that I can assign a more junior level colleague the responsibility to respond to these requests.

**Describe alternatives or workarounds you've considered**
Forwarding the email to someone else.

**Additional context**
n/a

**Comment by tdonohue** [comment]
@VTOpenLib : Thanks for the feedback!  Unless I'm misunderstanding your use case, I think this feature _may_ already exist in a different form in DSpace.

We already have this configuration in the `dspace.cfg` on the backend. It defaults to false, but it can be modified in your `local.cfg`:
```
# Should all Request Copy emails go to the helpdesk instead of the item submitter?
request.item.helpdesk.override = false
```

When set to `true`, that will force all Request emails to be sent to the `mail.helpdesk` email account, which is configurable also in `dspace.cfg`:
```
# Helpdesk E-mail
mail.helpdesk = ${mail.admin}
mail.helpdesk.name = Help Desk
```

So, one option here is to set that to `true` and configure your `mail.helpdesk` to go to a mailing list which includes all the people you want to be responsible for these requests.

Because these requests are all sent via email, there's currently no way to "manage" or reassign these requests in DSpace.  So, if the above configuration doesn't work, you'd likely be asking for us to create a new management system for these requests (which would be much more complex, but is possible).

**Comment by VTOpenLib** [comment]
Thank you. Is there a way to do this on a record-by-record basis rather than redirecting all inquiries to a central place?  i.e. different people need to receive notifications for different records.

**Comment by tdonohue** [comment]
@VTOpenLib : Unfortunately, no. That's the feature that doesn't yet exist in DSpace.  It's only possible to send them all to a helpdesk email, or send them all the the original submitter.  There's no way to customize where they are sent per item at this time.  If that's what you really need, then that would be a new feature.

**Comment by VTOpenLib** [comment]
Thank you. Yes, that is what I really need. 

So, please consider this a new feature request. 

If there is a different place to submit a new feature request, please let me know where to do that as I was under the impression that this is the place to submit such a request. Thank you.

**Comment by tdonohue** [comment]
@VTOpenLib : This is the correct place!  I was just making sure I fully understood your use case & clarifying why the existing configuration won't work.  But, yes, we'll consider this a feature request.  Keep in mind though that it'll be lower priority until we hear others need the same feature ... as more community feedback comes in, the priority would obviously increase.

Thanks for clarifying the use case here!  For now, I'll pull this over to our "low priority" board.  But, it may move up if we discover this is a common use case or need.  And, even if it's "low priority", there is always a chance a volunteer developer will want to build this soon to meet the same needs at their institution.

**Comment by mwoodiupui** [comment]
There is PR #2115 which adds a CollectionAdministratorsRequestItemStrategy to direct copy requests to the members of the owning collection's admin. group.  Would that serve?

**Comment by VTOpenLib** [comment]
That might work. It depends on how many people are in the "owning collection's admin group". I'd like to prevent it from sending also to all of the super/system admins. They are not trained in the (manual) process for authenticating access for these specific items, nor is it their responsibility -- and I'm sure that they don't need more email. Can you tell me if they would by default also receive these notifications?

**Comment by tdonohue** [comment]
@VTOpenLib and @mwoodiupui :  I've realized this is already **possible**, but it seems to be undocumented. 
 I notice this after I reviewed the PR that @mwoodiupui linked to above: https://github.com/DSpace/DSpace/pull/2115

Simply put, there's an option in the `requestitem.xml` file which allows you to specify *any metadata* field to store the email of the person who should manage Request a Copy requests.  This means that you can create any metadata field you want (e.g. "local.requestcopy") and set it on and item by item basis.  This seems like it would meet @VTOpenLib 's needs, as it lets you define a specific email address for each item (and that email need not correspond to the submitter or anyone else, it can be any email address.)

Here's how you'd do it:
1. Create a metadata field which you'd like to use to store this email address.  You may want to add this metadata field to our "metadata.hide" settings so that it's not visible except to full Admins: https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L944-L945
2. Uncomment the "emailMetadata" setting here: https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/requestitem.xml#L22    Set it to use that metadata field.
3. Edit the Item(s) which you want to reassign.  Specify the email address you want to reassign them to in that metadata field.
4. At this point, the next time a request copy comes through, it should go to the email address in the metadata field.  If that metadata field doesn't exist on an item, it'll default to the submitter email address.

So, I think this can be closed, as it already exists.  As @mwoodiupui points out, there are even more options available in the upcoming  https://github.com/DSpace/DSpace/pull/2115 to also allow you to send these email to *multiple people*

**Comment by mwoodiupui** [comment]
@VTOpenLib `CollectionAdministratorsRequestItemStrategy` specifically gets only direct members of the default administrators group for the Item's owning collection.  It does not chase sub-groups.  It does not cascade from containing collections or the Site.

**Comment by tdonohue** [comment]
Closing this as I believe it's now been fully answered & it already exists in 7.x. I also updated the documentation about how to change the email address by using a metadata field at https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-Configurewhogetsrequestviaametadatafield

**Comment by alawvt** [comment]
@VTOpenLib, thank you for submitting this request and thank you @tdonohue and @mwoodiupui for responding. @tdonohue, this is great news about the emailMetadata setting. May we add that same documentation to the DSpace 6 Wiki?

**Comment by tdonohue** [comment]
@alawvt : Sure, feel free to copy it to 6.x as well, as I believe it works in the same manner (but I haven't had time to test it).  There are some general notes implying it works the same way in 6.x here: https://wiki.lyrasis.org/display/DSDOC6x/Request+a+Copy#RequestaCopy-SelectingRequestaCopystrategyviaSpringConfiguration

**Comment by VTOpenLib** [comment]
Yes, thank you very much, @tdonohue and @mwoodiupui . Much appreciated!

**Comment by alawvt** [comment]
I have added the documentation for DSpace 6.
