### ISSUE TITLE
Generic error occurs when replying to a Copy Request if you don't have permissions to send a reply

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1806]
**Describe the bug**
A clear and concise description of what the bug is. Include the version(s) of DSpace where you've seen this problem & what *web browser* you were using. Link to examples if they are public: DSpace 7.3, Firefox

1. With a personal email, I created an item in DSpace 7 Demo, https://demo7.dspace.org/items/b2fac597-a382-4c0e-82ef-802afca015a0. 
2. As dspacedemo+admin@gmail.com, I restricted the bitstream, https://demo7.dspace.org/items/b2fac597-a382-4c0e-82ef-802afca015a0/request-a-copy?bitstream=bfe2b22e-bca7-4a13-851e-f8f6f5091ec4 to Administrators only. 
3. I requested the item from a second personal account. 
4. I received the request at the first personal email account. I selected "Send copy" and received the error,
![DSpace7_request_copy_reply_error2](https://user-images.githubusercontent.com/13037168/187996424-8df1c350-24af-4ce4-ab2e-43d6a6ea3a01.png)

**To Reproduce**
1. Do this
5. Then this...

**Expected behavior**

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
I tested this today and "Request a Copy" is working fine for me locally.

**However**, I have seen this scenario before, and I suspect you are hitting an authorization issue.  For instance, I've seen this same behavior when performing these steps: 
1. Login as "User1" and submit an Item with a restricted Bitstream
2. Login as "User2" and submit a "request a copy" request to User1 for access to that Bitstream
3. Now, login as a full Admin (User3) and attempt to reply to that request.  User3 can access the "Request a Copy" page, but the reply _will fail_, because only the user who received the request (Submitter by default) can reply to it.  

The person who receives the request depends on your "strategy" configured for Request a Copy.  By default, only the original submitter can reply.  But, it's possible to specify a different responder if you change the request configuration to use "helpdesk email" or Collection Administrators or Item metadata. See https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-SelectingRequestaCopystrategy

All that said, I think the bug here is that the error message returned is not informative.  Additionally, the permissions of the user accessing the request a copy page should be checked *earlier* & you should be blocked from accessing the page if you are not allowed to respond.  I'll update this ticket's title to clarify the bug.

**Comment by tdonohue** [comment]
This appears to be fixed in 7.6 by https://github.com/DSpace/dspace-angular/pull/2199
