### ISSUE TITLE
Pagination in REST API

### ISSUE THREAD

**Issue by SrinivasRao17** [DSpace/dspace-angular#1907]
Hi Team,

When we search for item in the list we will be able to view only 20 items in the page. Can we get complete list of items in one page. please find the attached screenshot for your reference. 

When we login and search for item list in REST API we will get only "Size 20" as default. but we need to change this default to total number of elements"1968" in one page. Can this be possible. Please check and let me know. Thanks!!

This is required as we are integrating REST API end points with other application and we need complete item list to add those API end points. 

{
  "page": {
    "size": 20,
    "totalElements": 1968,
    "totalPages": 99,
    "number": 0
  }
}

**Comment by tdonohue** [comment]
@SrinivasRao17 : You can pass the `size` parameter to any page to request more items.  See our REST documentation at https://github.com/DSpace/RestContract#pagination

However, it is NOT possible to request *all items* in a single request (by default the max is 100 per page, IIRC).  The reason is that very large requests can take a very long time to respond.

Closing this as answered.  Please be aware that we ask that questions about DSpace usage go through one of our Support channels: https://wiki.lyrasis.org/display/DSPACE/Support   GitHub issues should only be used to report suspected bugs, etc.

**Comment by SrinivasRao17** [comment]
Dear Tim,

Thanks for the quick response for the REST API Pagination solution. 

We have encounter one more issue.
We are not able to pull Item API end points under Collection API calls. Could you please help us to identify Item(Metric or Terms) API end point. 

If an Item is mapped to other collections then we are able to view those API under "mappeditem" but we are not able to view direct API's under collections. 

We are not able to attach screenshot.

Thanks!!

**Comment by tdonohue** [comment]
@SrinivasRao17 : All REST endpoints are documented at https://github.com/DSpace/RestContract/blob/main/endpoints.md

The high level structure of the REST API is at https://github.com/DSpace/RestContract/blob/main/README.md  

For Items, you'd need to use the separate /api/core/items endpoint, or the Search endpoint
https://github.com/DSpace/RestContract/blob/main/items.md
https://github.com/DSpace/RestContract/blob/main/search-endpoint.md

All features in DSpace 7 are implemented in the REST API, so anything you need/want to do should be possible.  If you ever need to figure out which endpoint to use, I recommend installing our Angular UI and watching what requests it makes to the REST API to gather information for particular pages. You can watch those requests by using your browser's DevTools and looking at the "Network" tab.

If you need any other help, as I said, you should use our Support channels: https://wiki.lyrasis.org/display/DSPACE/Support  We do not provide Q&A via GitHub issues.
