### ISSUE TITLE
Add and configure test tools

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#2]
We agreed on using:
- jasmine for unit tests
- protractor for e2e tests
- karma as a test runner

These tools need to be added to the project and configured.

We'll also need some documentation added to the wiki on how to use them (e.g. create a `my.component.spec` file in the same directory as the component for jasmine, put your e2e tests in that folder, that sort of thing…)

**Comment by sourcedump** [comment]
Hello!
I need some hints to decide how to proceed and I'm sure that someone of you has more experience than me with the 'package.json'.
Protractor needs to be installed as global. Should I put it into the 'global' script? Or we should create a 'global-test' or something like that?
Moreover, Protractor has Selenium server as dependency that can be installed with the following shell command:
webdriver-manager update
In this case where I can put that command (must be executed after the Protractor installation)? 
For a more clean install I should check the presence of a Java SDK because it's needed by Selenium. 
Maybe all these operations need a separated shell script?
Thanks

**Comment by artlowel** [comment]
angular-cli uses these exact same tools for testing. If I were you, I'd [set up a new angular-cli project](https://github.com/angular/angular-cli#usage), and take a look at the code it generates: which relevant libraries are added to package.json, what the config files for these tools look like, etc. It should give you a good starting point.

Looking at a local angular-cli project, it would indeed seem that protractor is a global dependency, and should therefore be added to the `global` script. And that they add a `e2e` npm script that runs protractor, and a `pree2e` script (meaning it will trigger automatically before every run of `e2e`) that runs `"webdriver-manager update"`

**Comment by wwelling** [comment]
@artlowel good advice

For a more complete setup for testing I would check out this starter project. It is not using Angular Universal, but that should not play a role on the testing strategy or setup.

https://github.com/AngularClass/angular2-webpack-starter

**Comment by sourcedump** [comment]
Thanks!
