### ISSUE TITLE
DSpace cookie messages are not used, instead the default Klaro messages are used

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#2027]
**Describe the bug**
In the latest DSpace7.5-Snapshot DSpace Klaro cookie messages named in `src/app/shared/cookies/klaro-configuration.ts` and defined in the i18 files are not used, instead the default Klaro messages are used.

**To Reproduce**
1. Clear your browser cache and open a DSpace page or go to the demo site https://demo7.dspace.org
2. Have a look at the cookie dialog

<img width="484" alt="Screenshot 2023-01-05 at 10 56 26" src="https://user-images.githubusercontent.com/8408850/210755258-664bb863-f07b-4b3a-98fc-a74815f146fb.png">

3. Compare to the messages you defined in `en.json5` and see that they do not match

**Expected behavior**
The messages named in `src/app/shared/cookies/klaro-configuration.ts` and defined in the i18 files should be used in Klaro cookie dialog.

**Comment by MW3000** [comment]
Perhaps related to https://github.com/DSpace/dspace-angular/pull/1908 ?

**Comment by ybnd** [comment]
Thank you for catching this @MW3000!

@tdonohue the i18n was working properly as of #1908, but it was also fine at _some point_ at least while I was working on #1975...

I think I messed up while merging `main` & didn't test properly
* [Here](https://github.com/DSpace/dspace-angular/pull/1975/files#diff-390f6f8dd9f4cf9d0342e816697b2a83b6bc35d8343cafd1dda8ba19bd40a128R52) it's back to importing `'klaro'` instead of `'klaro-no-translations'`
* ...which probably causes Klaro to use its own `en` keys, which we don't override in `klaroConfiguration` anymore (changed to `zz`)

If this is the only issue it should be enough to just change the import, I can do that next week.

____

Optional alternative:
If Klaro isn't in the main bundle anymore we could also revert the `zz` bit, but as you said

> we are already translating much of Klaro in our existing `src/assets/i18n/*.json5` files

...so if we don't need them we can still save bandwidth with the lazy bundle
