### ISSUE TITLE
IIIF viewer not loading images

### ISSUE THREAD

**Issue by nwoodward** [DSpace/dspace-angular#2058]
**Describe the bug**
After standing up Cantaloupe and configuring the DSpace backend for IIIF support, there are Javascript errors in the browser console when I view an item with an image and IIIF enabled in the metadata. I see the same JS errors on our DSpace 7.4 instance and the DSpace demo server.

Condensed errors:
> ERROR Error: NG0904                                       [main.js]
...
ERROR TypeError: this.vcr is undefined              [main.js]
...
Uncaught TypeError: Ks.viewer(...) is not a function               [mirador.js]

**To Reproduce**
1. Log in to https://demo7.dspace.org
2. Create an item with an image
3. Add the metadata field dspace.iiif.enabled and set to 'true'
4. View item with browser tools enabled

**Expected behavior**
The Mirador viewer should display the image bitstream.

**Comment by tdonohue** [comment]
@nwoodward : The DSpace 7 demo site (https://demo7.dspace.org) doesn't currently have IIIF enabled, so I'm not surprised that it isn't working there.  Cantaloupe isn't even installed there.

I've just tried this on my end using our `docker-compose-iiif.yml` development/testing script available in the codebase as the "backend": https://github.com/DSpace/DSpace/tree/main/dspace/src/main/docker-compose

```
# This ensures Cantaloupe is running alongside a backend in Docker
docker-compose -p d7 -f docker-compose.yml -f dspace/src/main/docker-compose/docker-compose-iiif.yml up -d
```
NOTE: For the backend, I also had to enable the following in local.cfg:
```
# For IIIF testing
iiif.enabled = true
event.dispatcher.default.consumers = versioning, discovery, eperson, orcidqueue, iiif
```

Then, I spun up the frontend, using the instructions at https://wiki.lyrasis.org/display/DSDOC7x/IIIF+Configuration

```
# This ensures Mirador is actually running in the UI
yarn run start:mirador:prod
```

Finally, I made sure I had an Item with an image bitstream and having `dspace.iiif.enabled=true`.

For me, everything is working.  I can see images load in Mirador using the latest `main` (which is mostly the same as v7.5 right now, we've only had a few tiny bug fixes applied since 7.5).


That said, I **can verify** that I'm seeing the same errors in my browser's DevTools Console.  They do not seem to block the ability to view images in IIIF, but they do appear:
```
ERROR Error: NG0904
...
ERROR TypeError: Cannot read properties of undefined (reading 'createComponent')
...
Uncaught TypeError: Xs.viewer(...) is not a function
```

**Comment by nwoodward** [comment]
Thanks for checking. OK, so the console errors I'm seeing aren't what is preventing the image from ultimately loading in the browser. I'll do another deep dive into this in the next week.

**Comment by nwoodward** [comment]
OK, I think the problem happens when going from my local dev environment with everything on localhost, where IIIF works in the way you described, to my test DSpace 7.5 server online.

I could only get it to work on the server if I set up Cantaloupe behind a reverse-proxy in Apache as per their instructions (https://cantaloupe-project.github.io/manual/3.4/deployment.html#Reverse-ProxyingApache) and give it a public URL. Then I updated `iiif.image.server` in `[dspace]/config/modules/iiif.cfg` to point at the public URL.

I noticed that before making these changes, when Cantaloupe was still running on localhost:8182 on the test server, the first time I visited an item with dspace.iiif.enabled in my browser console I saw a 500 Server Error for the URL: http://localhost:8182/iiif/2/[uuid]/info.json, which gave me the impression the Angular app was looking locally for Cantaloupe when it shouldn't.

**Comment by subratlubu** [comment]
Hello Team,
I have installed the IIIF Image with the Cantaloup image server in DSpace8.2 and running it on a localhost server. The metadata field dspace.iiif.enabled and set to 'true'. Everything is working fine, but when I tested it in DSpace front end, the following error message showing with a blank page.

"SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data a..."

<img width="1534" height="1103" alt="Image" src="https://github.com/user-attachments/assets/ddbb7d52-eadb-446b-a6e4-be6839412767" />

Any guidance would be a great help for me.

Thank you.

Regards
Subrat Nanda
