### ISSUE TITLE
Travis config browser duplication

### ISSUE THREAD

**Issue by courtneypattison** [DSpace/dspace-angular#206]
I just started learning Travis CI yesterday, so I may be way off on this one.

It seems like dspace-angular is using the APT addon to install chrome, then using chromium with Xvfb so it's headless.

Since dspace-angular is using a trusty linux virtual env for CI, maybe it would be cleaner to [use the chrome addon and run a headless chrome](https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai). I'll submit a PR to show what I mean.

Sorry if these are annoying, but I have a couple of questions about dspace-angular's .travis.yml:
1. Why did you stop caching the node_modules?
2. Why is `yarn lint` in Travis if it is designed to always exit with zero?

**Comment by tdonohue** [comment]
Hi @courtneypattison.  Thanks for the questions & code contributions!

Some quick answers for you:

1. We removed the caching of `node_modules` as we ran into a past scenario where Travis CI was failing tests because it was using an old version of a module that no longer worked with our codebase.  At the time the easiest fix seemed to be to stop caching modules, as it seemed to us that Travis wasn't always "picking up" when we had updated the module version.  This change came in via #144 (but I see there's not much info to go on in that PR description).  I don't think we're against re-caching modules if it makes sense...but we'd just have to keep an eye out for future Travis issues.

2.  I actually don't know the answer myself :)  But, I see you changed this in your PR #207, which seems fine by me!

Admittedly, while a few of us have Travis CI experience (in core DSpace), this is the first time most of us have used the combo of Travis CI + Node + Angular.  So, improvements and tough questions are more than welcome, as it'll help us all improve the configuration of Travis (and learn in the process)

**Comment by courtneypattison** [comment]
@tdonohue thank you for your response!

I can definitely understand why you'd stop caching modules. That bug must have been frustrating. 

Since you're not against linting being a part of dspace-angular's CI flow, I'll submit a PR that allows linting to exit with nonzero values and fix the few current linting errors.
