### ISSUE TITLE
iframe no longer supported in collection introductory text

### ISSUE THREAD

**Issue by dagrenzer** [DSpace/dspace-angular#2064]
In DSpace 5 and 6, iframes could be included in community and collection introductory text and would display (in this way videos or maps could be embedded, see https://demo.dspace.org/xmlui/handle/10673/101 for example). In DSpace 7 this is no longer the case.

Was this changed intentionally? If not, can it be added back? I don't see documentation or discussion of the change anywhere...

I don't see the list of allowed HTML tags defined in the code, maybe it is predefined by Angular? Is it the same as the list in the documentation at https://wiki.lyrasis.org/display/DSDOC7x/Simple+HTML+Fragment+Markup ?

**Comment by dagrenzer** [comment]
See https://demo7.dspace.org/handle/10673/245528 for an example of an iframe failing to display in DSpace 7.

**Comment by tdonohue** [comment]
@dagrenzer : This appears to be managed by Angular itself.  In these Collection/Community fields we are using Angular's built in `[innerHtml]` property.  Angular itself "sanitizes" all HTML that flows through that property in order to avoid XSS vulnerabilities/attacks.  Here's an article that summarizes why Angular does this: https://angular.io/guide/security#preventing-cross-site-scripting-xss

It doesn't look like there's a definitive "reference" from Angular regarding which tags it allows.  But, I found these links to the source code from Angular, which shows what is allowed and not allowed:

Allowed HTML tags (elements) are here: https://github.com/angular/angular/blob/main/packages/core/src/sanitization/html_sanitizer.ts#L36-L64

Allowed HTML attributes (on those tags) are here: https://github.com/angular/angular/blob/main/packages/core/src/sanitization/html_sanitizer.ts#L69-L84

So, looking at that list, `<iframe>` is definitely not allowed.  It does appear you can use tags like `<img>` or `<video>` though, if you are just looking for a way to embed an image or video.

I don't think know that we'd want to bypass this sanitization in DSpace 7, as it's protecting us from potential security vulnerabilities.  (Arguably, we shouldn't have allowed this in DSpace 6 either).

I'll update the docs you linked to above with this information to ensure it is formally documented https://wiki.lyrasis.org/display/DSDOC7x/Simple+HTML+Fragment+Markup

**Comment by tdonohue** [comment]
Closing as "answered".  I've updated the docs at https://wiki.lyrasis.org/display/DSDOC7x/Simple+HTML+Fragment+Markup with more details.  It appears that there are corresponding HTML5 tags you can use instead of iframe (e.g. img, audio, video, map, etc)
