### ISSUE TITLE
Delete bitstream multiple times resend rest request

### ISSUE THREAD

**Issue by aroman-arvo** [DSpace/dspace-angular#2173]
**Describe the bug**
Rest request are repeated id some bitstreams are deleted, saving between.

**To Reproduce**
Edit an item with multiple bitstreams -> bitstreams
Select one for delete and click "save"

200 OPTIONS /server/api/core/bitstreams/c170ce52-f330-40a4-a4db-051bc0e5f6bd
200 DELETE 	/server/api/core/bitstreams/c170ce52-f330-40a4-a4db-051bc0e5f6bd

are send.
Select other bitstream to delete and save:
200 OPTIONS /server/api/core/bitstreams/c170ce52-f330-40a4-a4db-051bc0e5f6bd
200 OPTIONS /server/api/core/bitstreams/8d5377b5-c36c-4e1f-aa44-804dd620578d
404 DELETE 	/server/api/core/bitstreams/c170ce52-f330-40a4-a4db-051bc0e5f6bd
200 DELETE 	/server/api/core/bitstreams/8d5377b5-c36c-4e1f-aa44-804dd620578d
And so on

**Expected behavior**
Do not repeat requests.

**Comment by tdonohue** [comment]
@aroman-arvo : I'm not sure that I understand this ticket.

The reason that OPTIONS requests are sent is because they are required for CORS (called a preflight request).  So, there are two requests at all times in this scenario:

1. First, an `OPTIONS` request for CORS to let the server know that a DELETE is planned to be sent. CORS verification will occur to validate that a DELETE is valid.  See OPTIONS documentation for details: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS
2. Then, assuming CORS passes, the actual `DELETE` request will be made.

So, I believe this behavior of sending an `OPTIONS` request followed by a `DELETE` is expected/required to support CORS.  It's not a bug.

But, please let me know if I'm misunderstanding this ticket.

**Comment by aroman-arvo** [comment]
Example at local. (https://demo7.dspace.org dont allow me to upload files)
[screen-recorder-fri-mar-31-2023-11-10-13.webm](https://user-images.githubusercontent.com/116575333/229078402-cbe07d35-fb46-4f09-ad0d-3f5a76fda124.webm)

My local version is a bit modified, at yours repeated deletions should return a 404 status.

**Comment by alexandrevryghem** [comment]
@aroman-arvo could you check if this error still occurs now? The endpoint for deleting bitstreams has been changed since when you opend this issue (see PR #2280)

**Comment by aroman-arvo** [comment]
the bug should have been fixed. the issue can be closed
