### ISSUE TITLE
`ngOnChanges` hook does not work in themes

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/dspace-angular#2201]
**Describe the bug**
When overriding a stock component in a theme, the changes hook is never called.  The instance variable `compRef` is used in `src/app/shared/theme-support/themed-component.ts:ngOnChanges` but that variable is not set until `ngInit` runs, and that happens *after* the first call to `ngOnChanges`.

I note that none of the stock themeable components implements `onChanges` so this issue has not caused a problem until now, when I want to make `section-upload-file.component.ts` themeable.

**To Reproduce**
1. Write a themed replacement component that depends on change notification.
2. Notice that no changes notifications are received.

**Expected behavior**
All component lifecycle hooks should function in themes.

**Comment by mwoodiupui** [comment]
`SubmissionSectionUploadFileComponent` breaks as soon as I introduce `ThemedSubmissionSectionUploadFileComponent`, before actually creating a new implementation in my theme.

**Comment by alexandrevryghem** [comment]
This is caused because the `ThemedComponent.ngOnChanges()` [here](https://github.com/DSpace/dspace-angular/blob/8f62fc2fa91a063db7a94b1fdbfcce5433e41b49/src/app/shared/theme-support/themed.component.ts#L65) updates the `@Input()` variables from the `SubmissionSectionUploadFileComponent` directly. By updating those variables manually, the `ngOnChanges()` method is not triggered. The fix would be to call the `ngOnChanges()` method with [these](https://github.com/DSpace/dspace-angular/blob/8f62fc2fa91a063db7a94b1fdbfcce5433e41b49/src/app/shared/theme-support/themed.component.ts#L60) changes instead.

Atmire would like to claim this issue

**Comment by tdonohue** [comment]
@alexandrevryghem : Sounds good & thanks. Assigning to you and pulling over to the 7.6 board

**Comment by mwoodiupui** [comment]
#2202 may be useful in testing a fix for this issue.

**Comment by tdonohue** [comment]
@mwoodiupui : a possible fix for this issue was just created in #2235.  So, you may want to try out #2235 to make sure it fixes the issue you've encountered

**Comment by alexandrevryghem** [comment]
I found out that the `ngOnChanges` is also not called components who don't use the regular theming method but use the custom decorators instead:
- `ListableObjectComponentLoaderComponent`: `@listableObjectComponent`
- `MetadataRepresentationLoaderComponent`: `@metadataRepresentationComponent`
- `ClaimedTaskActionsLoaderComponent`: `@rendersWorkflowTaskOption`

I can fix those too in this PR 🤷‍♂️
