### ISSUE TITLE
remove buttons "Delete EPerson" and "Reset Password" in "Create EPerson" form

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#2289]
The "Create EPerson" form contains two buttons that are disabled as they are not applicable in the context of eperson creation. The buttons should removed from the form.

![image](https://github.com/DSpace/dspace-angular/assets/952735/61da5473-a4b2-4801-bebf-943f9dd5c14f)

**Comment by tdonohue** [comment]
NOTE: As of 7.6, the "Reset Password" button has already been removed.  But, the "Delete EPerson" button still does exist on this creation page (though it's disabled).

I'll leave this ticket open as I agree it's a very minor usability/design issue.  Likely could be easily fixed by someone who finds the time.

**Comment by HamzaFarooqArif** [comment]
I can do this. assign this to me

**Comment by tdonohue** [comment]
@HamzaFarooqArif : Thanks for volunteering!  I've assigned this to you.  Please keep in mind our "How to Contribute" guide when submitting a PR: https://github.com/DSpace/dspace-angular/blob/main/CONTRIBUTING.md

**Comment by tdonohue** [comment]
Closing, fixed by #2391
