### ISSUE TITLE
Media viewer controls rendered behind DSpace header

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#2341]
**Describe the bug**
The preview of `ngx-gallery` is rendered _behind_ the DSpace header, which obscures its controls, including the "Close" button. Because of this, the preview can only be closed by
* pressing Esc (which is likely not obvious to users)
* refreshing the page
* navigating to another page

**To Reproduce**
1. Open (or create) an Item with multiple images in the ORIGINAL Bundle
2. Click on the media viewer placeholder to open th preview

**Expected behavior**
The preview should be drawn over top of the header.

**Solutions**
Can be solved [here](https://github.com/DSpace/dspace-angular/blob/884aa0743096b4bfe946679aa48ad3f5727575df/src/app/header-nav-wrapper/header-navbar-wrapper.component.scss#L1-L4) by either
* _not_ specifying a `z-index` (note that the `z-index` of `ngx-gallery` is _already higher_ than the one we set here!)
* or specifying `position: static`

However, these changes are incompatible with mobile view (see https://github.com/DSpace/dspace-angular/pull/2220)

**Comment by HamzaFarooqArif** [comment]
I want to work on it. please assign it to me

**Comment by tdonohue** [comment]
Thanks again @HamzaFarooqArif for volunteering!

**Comment by HamzaFarooqArif** [comment]
I apologize that I'll not be able to continue working on it. I'm unassigning me from this issue

**Comment by tdonohue** [comment]
Additional details from duplicate ticket #2429 created by @Sondissimo :

**Describe the bug**
When we select an item, if we open the bitstream to visualize it, we encounter a strange behaviour regarding the top navbar.
Version: 7.6

**To Reproduce**
Steps to reproduce the behavior:
1. When we visualize an item bitstream the navbar is not correctly rendering
![image](https://github.com/DSpace/DSpace/assets/119754561/197a490e-3f43-4835-ae41-5b791808ea7c)


**Expected behavior**
The navbar shouldnt be visible when inspecting bitstreams

**Related work**
https://github.com/DSpace/DSpace/issues/9022

**Comment by tdonohue** [comment]
Assigning to @Sondissimo who [volunteered on behalf of 4Science](https://github.com/DSpace/dspace-angular/issues/2429#issuecomment-1671653662).

**Comment by davide-negretti** [comment]
I'm now working on this one in place of @Sondissimo

**Comment by davide-negretti** [comment]
The best solution I've found so far is to apply the z-index of the `header-navbar-wrapper` container conditionally, when the collapsible navbar is open on mobile screens. However this is going to require a refactoring of the whole component.

**Comment by davide-negretti** [comment]
I opened a PR: #2594
