### ISSUE TITLE
Google Analytics key needs to come from the server

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#244]
Currently the google analytics key needs to be configured in dspace-angular's config file, but the REST API uses it as well, to track downloads. When the key becomes available on a configuration endpoint on the REST API, we should use that instead and remove it from dspace-angular's config.

**Comment by tdonohue** [comment]
Related to this recent REST Contract PR: https://github.com/DSpace/Rest7Contract/pull/119

**Comment by tdonohue** [comment]
In reviewing DSpace 7 tasks, I just realized this was forgotten.  Currently we have two Google Analytics keys... `gaTrackingId` in dspace-angular, and `google.analytics.key` in the REST API.

Now that the REST API has a configuration endpoint (https://github.com/DSpace/DSpace/pull/2762), we should remove the `gaTrackingId` and retrieve this key from the `/config/property/` endpoint.

@artlowel : would you (or someone on your team) be willing to estimate this when you get the chance.  My assumption is this is likely a small task, so I'm tentatively adding this to Beta 5 so that it's cleaned up prior to 7.0 final.

**Comment by artlowel** [comment]
This will take an estimated **1h**
Atmire would like to claim this ticket

**Comment by tdonohue** [comment]
Thanks @artlowel .  Sounds good, assigning back to you for your team.
