### ISSUE TITLE
Add hash/fingerprint to the translation files

### ISSUE THREAD

**Issue by alexandrevryghem** [DSpace/dspace-angular#2461]
Add hash/fingerprint to the translation files, this way the user doesn't has to hard refresh to get the updated version of the translation files.

Possible implementation:
- Calculate the hashes & save them by using `EnvironmentPlugin`
- Add the hashes to the translation files using `CopyWebpackPlugin`
- Create a new `TranslateLoader` to retrieve the translation files using the saved hashes

**Comment by tdonohue** [comment]
Seems loosely related to #1961 

Overall, I agree it'd be good to have hashes of all these files so that we don't need to reload them until changed.  The challenge is in ensuring the rest of the code is aware of the hash updates so that it can load the appropriate file.

For now I'm pulling this over to the 8.0 board alongside the other ticket.  If changes are smaller in nature & don't impact upgrades, we could potentially consider for a bug fix release...but I'm concerned this would require more work than that.

**Comment by tdonohue** [comment]
Closing fixed by #2464 in 7.6.1
