### ISSUE TITLE
Javascript broken in IE11

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#251]
Javascript support is currently broken in IE11. 
You get the error message: `Object doesn't support property or method 'assign'` in the console. This likely means that a polyfill is missing
The error could have been there for quite a while, because due to server side rendering it's not all that noticeable that javascript is disabled.

**Comment by tdonohue** [comment]
Tested today, and seems to still exist (visible when opening IE's Developer Tools (F12)).  The Javascript error message is slightly different now and says:
`Object doesn't support property or method 'fill'`

Looking at the "Network" tab in the Developer Tools, it does appear that IE11 is simply requesting the next HTML page on each click and not using the REST API.

**Comment by saschaszott** [comment]
Did you observe that `browserslist` [file](https://github.com/DSpace/dspace-angular/blob/d9634a84aef0e9c9bea502d032aaaad7af1101f4/browserslist#L11) contains

```
not IE 9-11 # For IE 9-11 support, remove 'not'.
```

**Comment by tdonohue** [comment]
@saschaszott : Thanks for the note, I did not notice that we had that setting in our `browserslist` file.

@artlowel : This is an older ticket now, but I'd like to add it to Beta 5, if you agree.  Internet Explorer 11 still is shipped as part of Windows 10 (even though MS Edge is now the default).  Nonetheless, it seems like we might want to ensure there's support for IE 11 (at a minimum).  Does that seem reasonable to you?  Or is there a good reason we should leave out IE 11?

Tentatively adding to the Beta 5 board with Estimate TBD.

**Comment by saschaszott** [comment]
Maybe its worth changing the (negated) filter line in `browserslist` to

```
IE 11
```

and check if the error message disappears in IE11.

**Comment by tdonohue** [comment]
After further analysis, we are closing this as `won't fix`. 

Microsoft is in the midst of [retiring IE 11 entirely](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666) and is moving everyone to Microsoft Edge.  The timeline for this movement starts in Nov 30, 2020 when MS Teams will stop support of IE 11, and all MS365 apps stopping support in Aug 2021.

Because the timeline of IE11 support is closing rapidly, we will not support IE 11 for DSpace 7.  Anyone encountering this issue should use Microsoft Edge browser which is the default browser on Windows 10 and does not encounter this bug.
