### ISSUE TITLE
DSpace 7: Insufficient collection information when reviewing a workflow item 

### ISSUE THREAD

**Issue by f-rapp** [DSpace/dspace-angular#2570]
**Describe the bug**
When you review a workflow item, there is not enough information on the collection that the item was submitted to.

**To Reproduce**
1. Take a workflow item from the pool under https://demo.dspace.org/mydspace?configuration=workflow
2. Chose "edit".
3. You cannot see enough information to determine whether this is the right collection.
Example:
<img src="https://github.com/DSpace/dspace-angular/assets/67266996/1fb93dba-f66b-40f3-a6af-536706e66709" width="200">

For **workspace** items, that is not a problem, since the dropdown shows the full hierarchy and name, see:
<img src="https://github.com/DSpace/dspace-angular/assets/67266996/26b42fe6-4ab3-4b02-847c-b5a25a1204c2" width="200">
However, since the collection of a workflow item cannot be changed, this function is not available and there is not enough information to check whether the item was submitted to the right collection.

**Expected behavior**
You should see the collection name and the full hierarchy of the chosen collection.
Also: It could make sense to include the full hierarchy here as well:

<img src="https://github.com/DSpace/dspace-angular/assets/67266996/932d26ac-37ca-4191-9871-f59580e3f777" width="200">

**Related work**
#1602

**Comment by tdonohue** [comment]
Verified on the demo site.  This is also somewhat related to #1602 as both are scenarios where it would be useful to make the entire Collection hierarchy visible.

Needs a volunteer to investigate & find a solution.

**Comment by alanorth** [comment]
On a related note, when I get reports from submitters/reviewers about workflow issues I can often find the items as a super admin, but it is difficult to see who submitted it, which collection it was submitted to, etc. This information is critical to being able to debug workflow issues.

For example, from the "Administer Workflow":

![Screenshot 2024-02-22 at 10-04-18 CGSpace Administer Workflow-fs8](https://github.com/DSpace/dspace-angular/assets/191754/992af9cd-42de-45e9-b05c-aa97bd921f5a)

It would be nice if that information appeared the same way as on the "MyDSpace" workflow list. For example you can see the submitter and collection:

![Screenshot 2024-02-22 at 10-11-07 CGSpace MyDSpace-fs8](https://github.com/DSpace/dspace-angular/assets/191754/fdcfd0b3-675c-4bd0-9d13-77dda347f1e1)

**Comment by f-rapp** [comment]
I'd like to suggest to include the full collection path and not only the collection name. We have collections with the same name and would like to make the hierarchy visible, so we know if users submitted to the right collection.

**Comment by alexandrevryghem** [comment]
@f-rapp: With PR #2888 the current breadcrumb is completed with the comcol structure, would this be sufficient?

**Comment by f-rapp** [comment]
Hi, It's definitely helpful to see the com/coll infos in the breadcrumb. However, it's important to our reviewers to see the com/coll info before they actually open the item. That is in the preview of the item on the My DSpace page.

**Comment by tdonohue** [comment]
I think #2888 is a valid "fix" for this ticket, as the original description points out that the hierarchy is visible on the workspace item form but **not** on the workflow item form.  As of #2888, it **is now visible on the workflow item form**.

I do understand it could be improved _even more_ by adding the entire hierarchy into the list of workflow items.  However, some hierarchies are very long & may be difficult to display in their entirety next to the workflow item in this preview list.

So, I'd like to close this ticket as "fixed".  However, @f-rapp if you want to open a new ticket to ask for the hierarchy to be added next to the workflow item, then we can look for a way to achieve that in a separate PR.

Closing as fixed by #2888 as the basic need is now met.  It's now possible to find "sufficient collection information" from the workflow item form.

**Comment by f-rapp** [comment]
Hi, I opened a separate issue for the full hierarchy next to an item on the MyDSpace page.
https://github.com/DSpace/dspace-angular/issues/2974
