### ISSUE TITLE
Severe cache bug during submission on deposit

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#2577]
**Describe the bug**
When a new submission that contains a relationship issue is created a severe cache bug occurs which doesn't allow to deposit the item.
Essentialy if all the changes in the submission have been saved, before to deposit the application try to retrieve the submission object again to check if the item can be deposited ([it happens here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/objects/submission-objects.effects.ts#L213)). In the case the changes of the submission are not yet saved before to add a new relationship field they are saved when the relationship is added. This probably cause a cache problem and when the user try to deposit the item the application can't retrieve the updated submission object ([it happens here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/objects/submission-objects.effects.ts#L213)) because it gets a remote data with status error stale and this leads to an endless loop of request to REST server.

**To Reproduce**
It can be reproduced in the sandbox environment also
1. as submitter try to create a new publication in the collection `Publication 2` which have a relationship field
2. start to fill out the form following this order and without clicking on save:
  - accept the license
  - add the titlke and the date that are mandatory
  - add an author
  - upload a file
3. click on deposit
4. the submission is hanging forever and in the network endless requests are sent

https://github.com/DSpace/dspace-angular/assets/2486489/a1f132d9-798f-4677-b038-cb2fe933056f

[Untitled_ Oct 26, 2023 9_46 AM.webm](https://github.com/DSpace/dspace-angular/assets/2486489/86f4a394-6589-488d-b70e-e2b6cd77581b)

**Expected behavior**
The submission should be deposited

**Related work**
It's important to retrieve every time a fresh submission object because of the bug already resolved https://github.com/DSpace/dspace-angular/issues/1502

**Comment by artlowel** [comment]
@atarix83 The problem seems to be caused by the `reRequestOnStale` feature, if you set that to `false`, in [the call you mentioned](https://github.com/DSpace/dspace-angular/blob/47ae04986dde3cdc157e50205ac0d74bb09a2f77/src/app/submission/objects/submission-objects.effects.ts#L213), the problem goes away. 

Since the submission always manually re-retrieves the submission objects it shouldn't be necessary anyway so disabling it shouldn't affect the functionality.

However I do think there's still a bug in that `reRequestOnStale` feature, in a complicated case like this. If i log the number of calls to the findByID method for that same submission object, I count 6.  Some with `reRequestOnStale` true, others false. Then we also manually re-retrieve the object in the effect (by setting useCachedIfAvailable to false). I suspect this causes an edge case where the request that one of these subscriptions makes gets immediately set to stale by one of the others, causing the reRequestOnStale to trigger, which sets it to stale again, causing an infinite loop

So I'd try the workaround of disabling `reRequestOnStale` in the effect, see if it doesn't break anything, and if it doesn't merge that now. But leave the issue open to look into in more detail later

**Comment by atarix83** [comment]
thanks @artlowel  for your analysis. i can confirm your solution works.
I've also find out that if i change the [request](https://github.com/DSpace/dspace-angular/blob/47ae04986dde3cdc157e50205ac0d74bb09a2f77/src/app/submission/objects/submission-objects.effects.ts#L213) by including the item and collection embeds it works as well even with reRequestOnStale as true.
I've tried it becuase i notice that there are two requests done endlessly one just the submission id and one with also item and collection embed
![immagine](https://github.com/DSpace/dspace-angular/assets/2486489/5cd971fc-0a18-4881-b9e9-63de4559a9cd)

Maybe it can help to better understand the bug.

In the end i agree to temporary fix the issue in one of the two way and then to try to find out the problem in this edge case

**Comment by hutattedonmyarm** [comment]
I'm positive, that this is related to #1924. I observed the same pattern of endlessly re-requesting on stale
