### ISSUE TITLE
Get rid of global npm/yarn dependencies

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#261]
Global npm or yarn dependencies can be problematic because their versions aren't tied to the project, you use a single version for your entire system.

The reason we added them, is to be able to use certain tools from the command line. (e.g. webpack, rimraf, karma, ...)

But when a script defined in `package.json` uses these tools, it's not necessary to globally install them, because yarn and npm will automatically add the folder `./node_modules/bin` to the PATH when running scripts.

Since all our build scripts are in `package.json`, we no longer have any need  of global dependencies. We should therefore ensure that all global dependencies are also `devDependencies`, and remove the `global` script from `package.json`, and the docs

**Comment by tdonohue** [comment]
This ticket is still applicable even though it's quite old. These global dependencies still exist in our `package.json` here: https://github.com/DSpace/dspace-angular/blob/master/package.json#L18

One note here is that included in those global dependencies is `pm2`, which is NOT being used for development/builds, but rather for production deployment (specifically, it's used by the `deploy` and `undeploy` commands in our `package.json`).  We may want to consider whether `pm2` should instead be a documented prerequisite (alongside node & yarn, but only required for production setups), instead of treating it like a dev/build dependency. More info about PM2 is at https://pm2.keymetrics.io/

**Comment by mwoodiupui** [comment]
Regarding PM2, I will just mention that I had been planning to use something else, probably Passenger.  More generally, it seems to me that this is something that should be left up to the site, with a well-documented suggestion for sites that are not so opinionated. :-)

**Comment by mwoodiupui** [comment]
This issue seems to have been partially addressed, but there is no linked PR.  The `global` script was removed in commit 8bf241c182479f9fb35ca3028397b7c01e980316 at 2020-03-18 11:03:40.  However, README.md still instructs one to `yarn run global`.

**Comment by tdonohue** [comment]
@mwoodiupui : Good point. Yes, it seems like we fixed this as a "side effect" of the move to Angular CLI in #625

So, I think this ticket can be closed as soon as we remove any remaining references to `global`...likely just that one in the README.

**Comment by alanorth** [comment]
There are no longer any references to installing `global` packages in `package.json` or `README.md` so I think this is resolved.

The [DSpace 7/8 Install docs](https://wiki.lyrasis.org/display/DSDOC8x/Installing+DSpace#InstallingDSpace-Yarn(v1.x)) mention installing yarn and pm2, but I think that's the right place for detailing global dependencies (not in our project's package.json).
