### ISSUE TITLE
Community logo upload not working 

### ISSUE THREAD

**Issue by Ahmedhj24** [DSpace/dspace-angular#2826]
I have installed DSpace 7.6 and the community logo upload not working (when choosing the image nothing happened even the file name doesn't appears). I have change the DSpace directory to be owned by tomcat and add the read/write permission but still not working. 
note the DSpace 7.2 installed in the same server work with no error.
thanks for help

**Comment by tdonohue** [comment]
@Ahmedhj24 : You will need to use our troubleshooting guide to look for underlying error messages.  It's not possible for anyone to help otherwise, as there's a variety of issues that could be occurring.  See https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

It's also possible you are hitting this bug (which is now fixed and will be released in an eventual 7.6.2): https://github.com/DSpace/dspace-angular/issues/2240

Closing as this is not reproducible locally or on our demo site at https://demo.dspace.org/ . It's better to ask for support on mailing lists... see https://wiki.lyrasis.org/display/DSPACE/Support
