### ISSUE TITLE
ORCID authentication bug on Sandbox/Demo.

### ISSUE THREAD

**Issue by librariankimberly** [DSpace/dspace-angular#2917]
I'm using the DSpace 8 sandbox at https://sandbox.dspace.org/home. When clicking the Log in with ORCID button I am directed to the ORCID sandbox, which does not allow me to log in. (It states it uses only mailinator.com addresses and has a defunct "more information" link. I'm also noting the same problem on the DSpace 7 demo site. I'm using Firefox.

**To Reproduce**
1. Go to https://sandbox.dspace.org/
2. Click login in upper right corner
3. Click the Log in with ORCID button.

**Expected behavior**
I expected to be able to login with ORCID since the option was presented to me.

**Comment by tdonohue** [comment]
@librariankimberly : I wanted to briefly note here that unfortunately this isn't really a "fixable" problem.   We are purposefully using the ORCID Sandbox as this is a test server & we don't want to mess with individuals *real* ORCID data.   

ORCID's policy for their ORCID Sandbox is that it will only accept Mailinator (`@mailinator.com`) email addresses.  More information from them on how to use Mailinator (which is a free service) is in their Sandbox docs at: https://info.orcid.org/documentation/integration-guide/sandbox-testing-server/  (Click on the "How do I register a test client.." link which has all the details).

I do realize this makes ORCID authentication more difficult to test (as you'd have to setup a temporary Mailinator address first).  But, DSpace doesn't have any way to change this policy, as this is ORCID's policy. 

So, I appreciate that you logged this ticket because it gives the opportunity to **document** (in this ticket) why ORCID works this way on our https://sandbox.dspace.org (and https://demo.dspace.org) sites.  Unfortunately, though, there's no way for us to solve this issue, so I'm going to close the ticket.  That said, even while the ticket is closed, it **is possible** to add more questions/comments here (and I'll still be notified of them). So, if you have any, please do let me know.

**Comment by librariankimberly** [comment]
Thanks for the response. This makes sense and I suspected there was a reason behind this. Should this be tested? If so, I'll adjust the test to indicate what would need to happen to test this and when I have some time, I'll follow the instructions you've indicated. @tdonohue

**Comment by tdonohue** [comment]
@librariankimberly : It's not as important to test for 8.0 as there were no significant changes between 7.x and 8.0 ( that I recall). But, that said, if someone in DCAT can find time to test it, I'm of the opinion that it'd be "nice" to have everything retested.  (Sometimes a fix in one area of the code can have unexpected consequences elsewhere)

So, it'd be nice to test if there is interest.  But, it's not the highest priority.

**Comment by librariankimberly** [comment]
[like]  Chapman, Kimberly A - (kimberl... reacted to your message:
________________________________
From: Tim Donohue ***@***.***>
Sent: Wednesday, April 10, 2024 4:54:58 PM
To: DSpace/dspace-angular ***@***.***>
Cc: Chapman, Kimberly A - (kimberlychapman) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [DSpace/dspace-angular] ORCID authentication bug on Sandbox/Demo. (Issue #2917)


External Email

@librariankimberly<https://github.com/librariankimberly> : It's not as important to test for 8.0 as there were no significant changes between 7.x and 8.0 ( that I recall). But, that said, if someone in DCAT can find time to test it, I'm of the opinion that it'd be "nice" to have everything retested. (Sometimes a fix in one area of the code can have unexpected consequences elsewhere)

So, it'd be nice to test if there is interest. But, it's not the highest priority.
