### ISSUE TITLE
Item created using ROR import cannot be submitted in DSpace 8

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#2922]
**Describe the bug**
Different problems encountered (on the sandbox) when adding an item using import metadata from external sources with ROR as a source : 
1) When selecting an organisation, the ROR id of the institution is not added (id metadata is empty in deposit form) 
2) Most importantly, I was not able to submit the item, DSpace ask for file and even after adding one, this error message is still displayed when trying to deposit: "Deposit cannot be completed due to errors in the form. Please fill out all required fields to complete the deposit." and the only problem I see is for the file: 
![image](https://github.com/DSpace/dspace-angular/assets/19291880/b1c7d3cb-08d5-4efb-90c7-96051c07f566)

**To Reproduce**
1. Add a new organization using the new ROR source. Connect as administrator, 
2. Go to My DSpace and clic on the "document with arrow" button on the left of the dotted box 
3. Select Organizational Unit
4. In the list select Research Organization Registry (ROR) 
5. Search for an institution (i.e. Université Laval). 
6. Clic on the cloud icon and then the Start Submission button. 
7. Finaly verify all information and clic on Deposit
8. An error occurs and the document is not deposited

**Related work**
Link to any related tickets or PRs here.
This problem may be related to https://github.com/DSpace/dspace-angular/issues/2920

**Comment by tdonohue** [comment]
@pilasou : Now that #2920 is fixed, this error no longer occurs.  I was able to search for an organization in ROR and import it & complete the submission: https://sandbox.dspace.org/entities/orgunit/35ce51c8-1fa9-4a19-9b2e-fde18984f76b

Therefore, I'm closing this ticket as I believe it was fixed by the solution to #2920

(If you still find a way to reproduce the error, we can always reopen this later on as needed.)

**Comment by pilasou** [comment]
Hi @tdonohue I confirm that I was able to submit a new item in the sandbox! Thanks!
