### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#298]
UI control in the navbar where the user gets to change the language in real time.

**Comment by bram-atmire** [comment]
Already sinked some time in this but hitting the wall where I currently don't know how to make the TranslationService, which is currently initialized as a private Service in app.component.ts, available for use in the header module.

Any hints are welcome!

**Comment by bram-atmire** [comment]
Current branch I'm working on, where it "this.translate" currently can't be found because the header component can't get to the service https://github.com/bram-atmire/dspace-angular/commit/b2011e701c54b41bb765add05524d9511bb71196

**Comment by LotteHofstede** [comment]
You'll have inject the translate service into your component, by adding it as an argument to your constructor (don't forget to set a scope - private, protected, public, ... - for it). The HeaderComponent already uses two injectables, [the Store and HostWindowService](https://github.com/bram-atmire/dspace-angular/blob/b2011e701c54b41bb765add05524d9511bb71196/src/app/header/header.component.ts#L29) - just add the TranslateService here.

This is not needed for your particular issue, but if you'd create a new service service this would be important to know, so I'll just mention it anyway:
You have to make sure the module that your header component is a part of - which is the [AppModule](https://github.com/bram-atmire/dspace-angular/blob/b2011e701c54b41bb765add05524d9511bb71196/src/app/app.module.ts#L89) in your case - imports the TranslateModule. The AppModule already imports the TranslateModule [here](https://github.com/bram-atmire/dspace-angular/blob/b2011e701c54b41bb765add05524d9511bb71196/src/app/app.module.ts#L62).

**Comment by cjuergen** [comment]
Tried it and it worked, but shouldn't this be a shared component like auth-nav-menu in order to better reuse/remove  it.  But I'm completely new to Angular.
One other question tried to make it configurable default Language and list of available languages and put this in config/environment.dev.js for local development. 
Where should config options for a real commit to DSpace go ?

**Comment by bram-atmire** [comment]
I also got a little bit further, and have now a working, but ugly language switch dropdown cfr
https://github.com/bram-atmire/dspace-angular/tree/issue-298-language-switch

I agree, it might be cleaner if this is not such a part of the header but a separate component.

I also wonder about how to address the configurability:
- reading out the configuration (where do we read it out?)
- allowing a user to enable another language
- allowing a user to disable a language

And how that config persists.

**Comment by artlowel** [comment]
As @cjuergen mentioned, it's neater if you put the language switch in a separate component, and use that component in the header.

To ensure the select is styled by bootstrap give it the class [`form-control`](https://getbootstrap.com/docs/4.0/components/forms/#form-controls). To ensure it fits nicely in the navbar, wrap it in a div or form with the class [`form-inline`](https://getbootstrap.com/docs/4.0/components/navbar/#supported-content)

For now, I'd configure the available languages by adding them to `environment.default.js`. They can be overwritten in the `environment.(dev|prod|test).js` files for specific deployments. Since the translation source files reside on the angular server, it makes sense to configure them there as well (as opposed to getting the config from REST).

Afterwards we can [consider adding a step in the build process](https://github.com/ngx-translate/core/issues/307#issuecomment-258435136) that configures the languages in ngx-translate based on the available language json files. However I'm not convinced that is better, as you may want to disable languages that come with dspace, and if you do that by deleting the translation files, you may need to do it again every time you update.

**Comment by cjuergen** [comment]
Imo it should be configurable and not automatically be pulled from available translations in order to give the instance control over it. Furthermore most will have to adjust the message catalogue and be it mere branding. They usually do it for only a couple of languages and not for all.

**Comment by bram-atmire** [comment]
PR 308 can be reviewed. It has typedoc, but doesn't have any specific tests yet.
