### ISSUE TITLE
Page size change and sorting doesn't work on some pages

### ISSUE THREAD

**Issue by Leano1998** [DSpace/dspace-angular#2996]
**Describe the bug**
If you want to change the number of items on the edit-relations-lookup (edit-items -> relationships -> +Add) or change the sort settings it doesn't work. The same happens, if you try to do the same thing on a community-page in the search section.

**To Reproduce**

1. Edit an entity-item
2. Navigate to the relationship-tab and click _Add +_ to add a new relationship.
3. Try to change the sort order or the number of items per page

The list of found items doesn't change. (If you click _Select page_ the page will be selected and afterwards the sorting-changes/number-of-items are applied.)  

**Expected behavior**
The settings should be applied.

**Comment by tdonohue** [comment]
I can reproduce this on the Sandbox (https://sandbox.dspace.org).  It's also *very easy to reproduce* as follows:
1. Browse to any Community/Collection page
2. On the "Search" tab (default tab), in the sidebar change the "Results per page" from 10 to 20.
3. The entire page **hangs**.  It become unresponsive.   It doesn't appear to send a request to the REST API, but the page just shows the "loading" dots and never returns.

Flagging as **high priority** because it's very easy to end up with an unresponsive site.

**Comment by tdonohue** [comment]
Pinging @artlowel and @alexandrevryghem in case this is of interest.  It sounds related to #2732 (from @alexandrevryghem ) and also possibly related to #2978 (which @artlowel has claimed).    It might be the same issue on both pages, or slightly different (not sure).

If you are interested, let me know or claim it for yourself.

**Comment by tdonohue** [comment]
@alexandrevryghem : Are you still working on this one?  Ideally, this would be nice to fix prior to 8.0 since it's currently possible to cause the search page to "hang indefinitely" as described here: https://github.com/DSpace/dspace-angular/issues/2996#issuecomment-2091060693

**Comment by alexandrevryghem** [comment]
@tdonohue: Yes I'll try to look into it tomorrow/next week

**Comment by tdonohue** [comment]
@alexandrevryghem : Just a reminder this might be good to fix in time for 8.0, if possible to do so.
