### ISSUE TITLE
Initialize UI language as user's browser language

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#301]
This is current behaviour of DSpace to be reproduced. I dipped into this, based on code available from the ngx-translate example at https://stackblitz.com/github/ngx-translate/example, but couldn't get this to work yet in DSpace

**Comment by cjuergen** [comment]
Yes the basic behavior is to check the list of browser language settings use these, if not present in the supported locales use the default.
If a user logs in, use his user profile language.
If a user chooses a language from the UI use this.

I gave it a try and done a basic language-switch together with the the initial setting of the browser lang in the app component.  Just a stub but it switches the language.
https://github.com/cjuergen/dspace-angular/commit/c9300f986f589057a33fb1763927729a73edee7e
My very first step in Angular, so most likely there are better ways to do it. But you can try the branch out.

**Comment by cjuergen** [comment]
I did not find anything like https://docs.oracle.com/javase/7/docs/api/index.html?java/util/Locale.html getDisplayLanguage in ngx translate so I put the language display names in the message catalogues.

And I wonder whether we should be more specific and user the culture lang https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/lib/translate.service.ts#L509 rather than the Browser Lang and than fallback on the basic language if no culture related translation is available.

**Comment by bram-atmire** [comment]
Only saw your comment now - looks very similar to what i'm trying in https://github.com/bram-atmire/dspace-angular/commit/02cb1fb2e5093756c3dc6e558ddef18774ddd7a0 and indeed I agree, the language names themselves should be part of the catalog.
