### ISSUE TITLE
HTML support on system-wide-alert

### ISSUE THREAD

**Issue by AgustinAlfieri** [DSpace/dspace-angular#3019]
**Is your feature request related to a problem? Please describe.**
When using the system-wide alert feature I've wanted several times to put a specific link for our users. Normally it's to give them a direct link to a specific page describing an update or an email address to contact for a specific reason. Being able to highlight some information would also be really useful.

**Describe the solution you'd like**
To be able to use HTML for the system-wide alert messages.

**Describe alternatives or workarounds you've considered**
I don't think full HTML support is necessary, only the ability to put links and maybe bold text.

**Comment by abelgomez** [comment]
This can be easily performed by changing two simple lines:

Replace:

https://github.com/DSpace/dspace-angular/blob/6c4ff40020c6bf7cc27cc69756f404bbc857fa16/src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.html#L24

with:

https://github.com/sistedes/dspace.ui/blob/8c5c07dac054ad1c70adbecc60bc4dc0444625c0/src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.html#L25

And similarly, replace:

https://github.com/DSpace/dspace-angular/blob/6c4ff40020c6bf7cc27cc69756f404bbc857fa16/src/app/system-wide-alert/alert-form/system-wide-alert-form.component.html#L102

with:

https://github.com/sistedes/dspace.ui/blob/8c5c07dac054ad1c70adbecc60bc4dc0444625c0/src/app/system-wide-alert/alert-form/system-wide-alert-form.component.html#L101

Of course, this solution does not do any sanity check on the included HTML, but since the system-wide alert is something that only administrators can set, seems fair enough.

If that's acceptable, I can submit a pull request.

**Comment by abelgomez** [comment]
Sorry, it seems that links to lines in my repo are not rendered.

To make it clear, replace:

    <span>{{(systemWideAlert$ |async)?.message}}</span> 

with:

    <span [innerHTML]="(systemWideAlert$ |async)?.message"></span>

**Comment by tdonohue** [comment]
@abelgomez : Feel free to submit a PR.  We use `[innerHTML]` in other areas of the application as well, so it is acceptable.
