### ISSUE TITLE
Move language loading logic from app.component.ts constructor to separate loader

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#318]
Judging by:
https://github.com/DSpace/dspace-angular/blob/master/src/app/app.component.ts#L47
and
https://github.com/DSpace/dspace-angular/blob/master/src/app/app.module.ts#L62

We are currently initializing translate service without a particular loader, and we are loading the languages in the app.component constructor.

It might be better (up for discussion!) to use a separate loader for this, as https://github.com/ngx-translate/core#usage suggests.

**Comment by artlowel** [comment]
We _are_ using loaders. They're not in app.module.ts because we need different loaders on the server and in the browser. 

browser.app.module.ts uses the [TranslateHttpLoader](https://github.com/DSpace/dspace-angular/blob/9745faf17bfcf26ffb99272a1433885fc1a35423/src/modules/app/browser-app.module.ts#L27), server.app.module.ts the [TranslateUniversalLoader](https://github.com/DSpace/dspace-angular/blob/9745faf17bfcf26ffb99272a1433885fc1a35423/src/modules/app/server-app.module.ts#L27), which will simply get the file from the filesystem rather than over HTTP.

**Comment by bram-atmire** [comment]
Thanks for the clarification! Closing the issue.
