### ISSUE TITLE
Faulty submission form: arrange more than 3 lines

### ISSUE THREAD

**Issue by Verena-HSU** [DSpace/dspace-angular#3217]
The rearrangement of more than 3 lines in the submission form is faulty. Rows disappear in the display (they are there again when saving) or are arranged differently than specified.

This has been tested with Chrome version 126.0.6478.183 (Offizieller Build) (64-Bit) on Dspace 8 demo version with the following item:
https://demo.dspace.org/workspaceitems/2168/view

Scenario:
1. Open a submission form
2. Add three or more rows with authors or keywords or else
3. Rearange the lines several times.

--> Sometimes lines will disappear, sometimes arrange in a different order.

Expected behaviour: 

Lines will always appear und in the chosen order.

**Comment by kshepherd** [comment]
I have been seeing this in 7.6 and 8.0 as well.

I believe that after a reorder, the displayed text for 'existing values' do not always match the underlying [Reorderable]MetadataValue that is used in patch add/update/delete operations.

1. It seems to require that neither of the fields being 'switched' in the reorder are the first or last field (as of last save / current form state)
2. It happens with both plain metadata values and controlled values, or a mixture of both
3. The actual values are in the order they were moved. If you click 'Save' and reload the page, the values will appear in the order that they were moved to, with matching display text / labels.

Here are five author entries I made to demonstrate this on the DSpace Demo server - the 4th is a controlled value:

![screenshot_2024-07-29_11:19:16_selection](https://github.com/user-attachments/assets/84bbcd27-f8a0-49fb-ad88-2882d8f84c34)

Here is what is displayed after I reorder the 4th and 3rd values - they are switched but the label for the "Four Friends" entry has now been rendered as "Three".

After clicking Save to perform the patch updates, and reloading the page, I can see that the reordering was successful, the displayed text in the form was just incorrect:

![screenshot_2024-07-29_11:25:01_selection](https://github.com/user-attachments/assets/2b55da89-a143-4281-b210-ca9575506edb)

I believe the behaviour reported in https://github.com/DSpace/dspace-angular/issues/2004 (unreliable save/delete) is related to the same issue - the saves and deletes are probably actually doing "the right thing" but do not match user expectations because the displayed text in the form components doesn't match the actual existing value to be saved/deleted.

**Comment by jlipka** [comment]
I have mentioned my idea/solution in the other Github issue (#2004), please have a look if this could help here as well:
https://github.com/DSpace/dspace-angular/issues/2004#issuecomment-2264821632

**Comment by kshepherd** [comment]
> I have mentioned my idea/solution in the other Github issue (#2004), please have a look if this could help here as well: [#2004 (comment)](https://github.com/DSpace/dspace-angular/issues/2004#issuecomment-2264821632)

Just to note my comment here, too, the fix mentioned in #2004 is good on its own merit (fixing bad equality checking) but only affects existing relationships being patched/saved from a submission, not onebox metadata values being re-ordered in an active submission.

**Comment by tdonohue** [comment]
May be fixed by #3679, which needs testers.
