### ISSUE TITLE
[Usability issue] "Browse by" pages are missing "Now showing" contextual information

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#369]
After merging #364, all Browse By pages are now missing important contextual information.  

Namely, the "Now showing items __ of ___" text is missing on all pages.  This text can be seen in the XMLUI at: http://demo.dspace.org/xmlui/browse?type=title 

This has several major usability problems:
* The user cannot has no sense of how many items are in the "browse by" results (i.e. no sense of how many pages exist)
* Pagination becomes incredibly confusing, as you have no idea what page you are on, how many pages exist, and whether pagination is even _functioning properly_ (as the only sign you are on the last page is that the next page button suddenly grays out).

This contextual information was removed by the addition of the "Starts-With" component in #364

**Comment by atarix83** [comment]
@tdonohue 

to resolve this issue we suggest to modify the current pagination component in order to have the possibility to navigate through pages using the current paginator or just with next/prev buttons. In this way we are going to use the paginator also for browse-by component so the contextual information are displayed. 
Estimation is about 12-16h

**Comment by tdonohue** [comment]
@atarix83 : Thanks, that sounds reasonable.  I'll assign add the estimate at 14h (middle of your estimate) and pull this over onto the 7.3 board for your team to work on immediately.
