### ISSUE TITLE
Collections and Communities –– URIs?

### ISSUE THREAD

**Issue by lhenze** [DSpace/dspace-angular#471]
Hi, Is it correct that each community, sub-community, and collection has its own URI?
If so, will we need 2 more keys in the i18n folder for the labels? 
I see we have already "item.page.uri": "URI" but not for collections/communities

**Comment by artlowel** [comment]
That i18n key is used as a label on [item pages for the `dc.identifier.uri` field](https://github.com/DSpace/dspace-angular/blob/330a70657d5c03c52e4f0e96309ffdbfb485359c/src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html#L51). As far as I can tell we're not rendering that field for communities or collections anywhere, so I don't think we need an i18n key for it.

If the question is: shouldn't we render the handle for collections and communities on their homepages, then that's a different matter. 

Since we'll no longer have the handle in the UI URLs in dspace 7, the handle URL can no longer be easily derived from it. So yes in my opinion it makes sense to add it to the community/collection homepages.

**Comment by lhenze** [comment]
Sounds good, thanks. 
So seems to me it's consistent to add the keys 
"collection.page.handle" and "community.page.handle". 
?

**Comment by tdonohue** [comment]
Closing, as this was already done. Communities and Collections display URIs on their homepages
