### ISSUE TITLE
Possible error in package.json

### ISSUE THREAD

**Issue by sourcedump** [DSpace/dspace-angular#53]
The script "start:dev" should have the command 'npm run server:dev' not 'npm run server' or the execution will fail.

**Comment by artlowel** [comment]
I'm not sure `npm run server:dev` is exactly what we need. It does start the correct js file, which is what's fixing the issue, but it also uses nodemon instead of node. This means it will watch for changes and restart the server when they happen. And we already have a npm script for that: `npm run watch:dev` 

So what I think we need here is a separate script that runs `node dist/server/index.js` -> _that_ should probably be called `server:dev` and the current `server:dev` script should be renamed to something like `server:dev:watch` (and every other script that uses it should be updated)

**Comment by sourcedump** [comment]
Ok, done
