### ISSUE TITLE
Type Assertion or Deserializer

### ISSUE THREAD

**Issue by wwelling** [DSpace/dspace-angular#67]
Do we need to bring in a dependency to deserialize JSON into objects? If so, which library should be used?

TypeScript allows for Type Assertion: https://basarat.gitbooks.io/typescript/content/docs/types/type-assertion.html

If we need a more robust deserialization, is the following library a better option?

https://github.com/pleerock/class-transformer

We are currently proposing: https://github.com/weichx/cerialize

**Comment by tdonohue** [comment]
This discussion came up in today's meeting and is in reference to the already merged PR #61 (which uses `cerialize`)

**Comment by artlowel** [comment]
Type assertion alone wont do, because that only helps at compile time. If you assert a plain javascript object is a Collection for example, it won't get any of Collection's methods, because that assertion is compiled out, javascript doesn't know about it. You need to create a new Collection instance, and give it the properties of that plain javascript object, in order to be able to use Collection's methods on it. A serialization lib helps with that.

I compared class-transformer and cerialize when I was writing the hal-serializer, and both libs are quite similar. I ended up choosing cerialize mainly because i thought their naming was clearer, and because class-transformer had issues with [arrays](https://github.com/pleerock/class-transformer/issues/44) and [dates](https://github.com/pleerock/class-transformer/issues/22) not serializing under certain circumsances, that had been open, without response for quite some time.

If you have good reason to prefer class-transformer I'm willing to reconsider.

**Comment by wwelling** [comment]
I suppose it would be a lot to ask for type assertion to transpile into a javascript object that can deserialize complex json. I could imagine how it could though. I did not do any research into the different options, I just found them passing in other articles and notice class-tranformer is a more popular library.

**Comment by artlowel** [comment]
closing
