### ISSUE TITLE
Bitstream drag and drop

### ISSUE THREAD

**Issue by tantz001** [DSpace/dspace-angular#679]
There does not appear to be a way to reorder bitstreams with drag-and-drop when the bitstreams in a given bundle span multiple pages.

**Comment by artlowel** [comment]
You should be able to drop it on a page number

**Comment by tantz001** [comment]
Thanks, I have tried that both on Safari and Chrome with no luck -- the item simply remains at the bottom of the current page.

**Comment by artlowel** [comment]
In that case it broke. We'll take a look

**Comment by artlowel** [comment]
Currently it appears to be working as it was designed: 
As soon as you pick up a bitstream from page 1, that page is left with only 9 elements. When you drop it on page 2 it will appear as the first element on page 2: the 10th element overall. After you click save, the server will again divide it up in to pages of 10, which means that the dropped bitstream will now be at the bottom of page 1.

I agree that this is confusing, but the reason it was done this way is that if there are pages in between the page you start dragging and the page you drop on, we don't want to have to fetch all those in-between pages from the server, start calculating the new page borders client side etc, because that would defeat the point of pagination.

@tdonohue there are a number of things we can do to improve this in my opinion:
- We could save automatically. If you send the patch as soon as you drop the element and wait for the server's response before showing the dropped-on page, this problem goes away. However on most other edit pages for DSpace objects you get to see your changes and have the option to discard them before you save. 
	- This would take about **3 hours** to implement
- We could show the dropped element as the _second_ element of the page you're dropping on. This would ensure that after a save, it remains on that page, but as the first element. However if you manually move it to the top, after dropping but before saving, it would still end up on the previous page. 
	- This would take about **an hour** to implement
- We could keep track of all the order movements in memory, also for pages that haven't been fetched yet. This would mean that if you drag from page 1 to page 4, pages 2, 3 and 4 get an offset of -1, which would mean their first element as returned from the server will actually be rendered as the last element of the previous page. So if you drop something on page 4, and then click on page 2 for the first time, we'd get page 2 from the server, move its first element to the bottom of page 1 in the store, render its next 9 elements in order, and for its last element, take the first element of page 3 if that's been fetched yet, otherwise leave it out
	- This is by far the hardest solution and will take **12 hours** to implement

Of course we also have the option to leave it as is, it's not really a reordering bug (the bitstreams end up in exactly the order you dropped them in), rather a confusion due to the way pagination works.

@tdonohue as a side-note: I noticed I get a CORS exception now when I reorder bitstreams on my machine agains the demo rest api. The PATCH method is not allowed for localhost. Perhaps some additional configuration is needed for that server after your CORS PR (whitelisting localhost)?

**Comment by artlowel** [comment]
Note: I found [this item on the demo site](https://dspace7-demo.atmire.com/items/b6def9e5-8efd-493d-9afa-a2bd97805ac8) useful in wrapping my head around this issue. It has 2 pages of bitstreams in the ORIGINAL bundle

**Comment by tdonohue** [comment]
@artlowel : I think my preference here is your first option. Drag and drop should save immediately, as otherwise things get confusing across pages.   I think this also solves a minor usability issue in that right now after drag & drop reorder, the undo button for the moved bitstream never actually enables. This is incorrect behavior as the undo button should be enabled for any bitstream where changes were made.  In any case, your first solution would also solve this problem.  You cannot undo a reorder except by simply reordering things again.

As for the REST API demo site, I expect it does *not* currently have localhost whitelisted (as `dspace.ui.url` has been customized on that demo site to point at the Demo UI).  I'll ping 4Science on this in Slack, as they'd need to make the change obviously.
