### ISSUE TITLE
Ensure content in Redux store is immutable

### ISSUE THREAD

**Issue by wwelling** [DSpace/dspace-angular#68]
Some resources:

http://blog.angular-university.io/angular-2-application-architecture-building-flux-like-apps-using-redux-and-immutable-js-js/

https://houssein.me/redux/immutablejs/angular/2016/07/04/angular2-with-immutablejs-and-redux.html

http://onehungrymind.com/build-better-angular-2-application-redux-ngrx/

http://blog.scottlogic.com/2016/01/25/angular2-time-travel-with-redux.html

**Comment by artlowel** [comment]
I'm aware of Immutable.js (although I've never worked with it), but I hadn't included it yet because there are claims it hurts performance, has poor documentation, makes it harder to debug, ...  e.g. https://medium.com/@AlexFaunt/immutablejs-worth-the-price-66391b8742d4#.1xoz93bx0

You can also ensure immutability by testing for it, which is what I did up until now (e.g. [here](https://github.com/DSpace/dspace-angular/blob/master/src/app/header/header.reducer.spec.ts#L43)). 
This has the advantage that these tests only happen during development, and aren't slowing down your production code.

**Comment by artlowel** [comment]
I ran into [ngrx-store-freeze](https://github.com/codewareio/ngrx-store-freeze), middleware for ngrx that will throw an exception when the state is mutated. 

It ensures a dev can't accidentally modify the state, and forget to test for it, but it also has the advantage that it's only enabled in development mode.

**Comment by artlowel** [comment]
In the meeting on 2017-03-02 we agreed to add ngrx-store-freeze, but as it will only cover cases that you execute in dev mode, we'll still keep writing those unit tests as a fail safe.
