### ISSUE TITLE
Shibboleth authentication inconsistent.

### ISSUE THREAD

**Issue by tantz001** [DSpace/dspace-angular#681]
Initial login and authentication seems to work, but the Admin menu seems to disappear rather randomly, requiring users to click the 'login with shibboleth' button again.  This restores the Admin menu (without actually logging in again).

**Comment by tdonohue** [comment]
@tantz001 : Could you please provide a step by step method to reproducing what you are seeing?  Is the Admin menu disappearing after simply browsing around? Or are your refreshing/reloading the page and losing your authentication session (that is a known issue if so that authentication is lost on a reload, but we have an early possible fix here: https://github.com/DSpace/dspace-angular/pull/682)?  Is it only occurring in one browser or all?

In general, it helps the development team if you can find a way to reproduce a bug, and then give us the step-by-step process you've found. Otherwise, we have to try to search around for where the bug might be.

**Comment by tantz001** [comment]
There are actually a number of situations, but one I remember for sure is simply pressing the 'home' image (the DSpace logo).  Although now for the life of me I can't duplicate it.  Maybe it is a timeout issue?  And yes, for sure, a page refresh will do it.  I will note very carefully the next time this actually occurs.

**Comment by tdonohue** [comment]
@tantz001 : We will need an exact description of how to reproduce this.  We've had a *lot* of recent updates (even as recent as today) to the Angular authentication code which has fixed similar bugs related to losing authentication tokens/cookies.  So, it's very possible that this bug was already fixed (which might be why you cannot reproduce it) by other fixes we've applied in recent weeks.

For now, I'm flagging as "cannot reproduce".  We'll leave this open temporarily in case you figure out a way to reproduce this problem. But, if not, no worries, we can close the ticket & reopen later if it's ever rediscovered.
