### ISSUE TITLE
DS-4311 Workflow Actions refresh entire MyDSpace page instead of just WorkflowItem

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#721]
This is a duplicate of [DS-4311](https://jira.lyrasis.org/browse/DS-4311)

Clicking "Claim Task" reloads the entire MyDSpace page. This loses your context, so you need to locate the item you just claimed (and it may suddenly jump to the second page of results, like it did when I tested). This can be fixed by ensuring the MyDSpace page does NOT reload all results, but just reloads the claimed Item (as needed).

In DSpace 6 XMLUI, you can claim a task and immediately see the actions for that item hereafter without having to search for the item in your list again.

After editing the item metadata, the user should also immediately be able to perform the applicable actions (e.g. approve it after editing the metadata) without having to find the item again.

Related to [DS-4489](https://jira.lyrasis.org/browse/DS-4489) (now #771) and [DS-4490](https://jira.lyrasis.org/browse/DS-4490) (now #772)

There is no estimate for this task in the release plan.

**Comment by tdonohue** [comment]
As discussed in today's meeting, this ticket is not only about the "Claim Task" button (though that button's behavior is the worst).  

The page refresh also occurs when clicking "Accept" or "Reject" or "Return to Pool".  So, a user looking to click "Accept" on several claimed tasks in a row would need to:  (a) click Accept (page reloads), (b) search/page for the next item, (c) click Accept again (page reloads), (d) search/page for the next item.    Ideal behavior would allow the user to click "Accept", staying where they are & then click "Accept" on the next item, etc.

**Comment by atarix83** [comment]
@tdonohue 
I've take a look on this issue and  to avoid to reload the entire page we need changes on both angular end rest side.
Indeed the main issue is that to reload the single element of the search we need to know which is the new object type created after the execution of a workflow action.
For example when making a [request to claim a task](https://github.com/4Science/Rest7Contract/blob/main/pooltasks.md#post-method-single-resource-level) the endpoint should return the new `claimedtask` created while now return only a `204`. The same should be when [returning a task to the pool](https://github.com/4Science/Rest7Contract/blob/main/claimedtasks.md#delete-method).
The problem would still be there without changes on rest side even if we'd use the approach suggested for [#772 ](https://github.com/DSpace/dspace-angular/issues/772).

So we'd need: 

- (REST side) change the way we use now to claim task in such a way that endpoint return the new `claimedtask` created
- (REST side) add new search method by item for [pooltasks endpoint](https://github.com/4Science/Rest7Contract/blob/main/pooltasks.md) and [claimedtasks endpoint](https://github.com/4Science/Rest7Contract/blob/main/claimedtasks.md) to allow to retrieve the new task created after performing a "Accept", "Reject" or "Return to Pool" action
- (Angular) make changes to reload the single element instead the entire page 

in order to try to preview an Item during the Workflow approval process, we could add a `View detail` button that allow to switch to the existing detail mode, mantaining the focus on that specific Workflow task 
![Schermata da 2020-11-05 15-09-19](https://user-images.githubusercontent.com/2486489/98251376-ebf26500-1f78-11eb-8362-21ae64076f4f.png)

![Schermata da 2020-11-05 15-01-49](https://user-images.githubusercontent.com/2486489/98250895-52c34e80-1f78-11eb-8afc-0f3f5e00fd84.png)
 
Estimantion is about 16hours for REST and about 24hours for angular

**Comment by tdonohue** [comment]
In today's meeting, we discussed the proposal above and agreed to the approach.  A few notes from that discussion:
* The main issue is the REST API not returning the updated object when a claim/unclaim occurs.  The `204 No Content` returned was a mistake & we need to correct it.
* The new REST API search methods (to be used after clicking approve/reject) are necessary because the Angular UI doesn't know what the workflow configuration *is*.  Based on backend configuration, clicking "Approve" or "Reject" may result in different behaviors -- e.g. Item might be archived / sent back to submitter, or it might remain in workflow if multiple approvals are required to place into archive.
* The new behavior in the UI will be as follows:
    * After clicking Approve/Reject buttons, the frontend will query the backend for the next state. 
    * This might result in new buttons appearing (e.g. A reviewer might approve and put the Item into the next workflow step where they can now "Claim" it again).
    * This could also result in no further actions being available to the reviewer. In this scenario, the buttons may disappear altogether & a simple message like "You approved this item" or "You rejected this item" would appear in their place.
    * It's important to realize that the Item will NOT disappear from the current list of results.  This would be too complex to implement, and this behavior was modeled based on sites like GitHub (e.g. when you delete branches from GitHub, they just get grayed out but are not removed from your branch list until you refresh the page).
     * This means that the item won't disappear from a users list until the results list is refreshed (e.g. page reloaded, click on a new facet or new page).  It was noted in our meeting that this behavior may be confusing to users if they click on a new page and find the results list changed (but this also can occur if new items are submitted prior to their clicking on a new page, as new items will suddenly appear in their results list).  We feel this is a good enough approach.

**Summary:** [The approach described above](https://github.com/DSpace/dspace-angular/issues/721#issuecomment-722402119) is accepted. This has been split into two tickets:
1. This #721 ticket itself, which is now scoped to Angular work only.
2. The necessary REST API backend work to support this implementation: (COMING SOON)
