### ISSUE TITLE
Angular UI: Refactor metadata field used to store Entity Type

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#744]
Estimate: TBD

May only require minor changes depending on how REST contract changes

This is the Angular PR corresponding to https://github.com/DSpace/DSpace/issues/2815

**Comment by tdonohue** [comment]
**TICKET SIMPLIFICATION / RESCOPING**

For 7.0, this ticket has been simplified to the following, based on the scoping of the corresponding REST API ticket https://github.com/DSpace/DSpace/issues/2815

1. Any Angular UI code that previously used an Item's `relationship.type` field (which stores the type of entity) should be updated to use a new `dspace.item.type` field. This new field will store the same value as previously, so hopefully the code can be easily updated via a replacement.
2. This ticket obviously will depend on https://github.com/DSpace/DSpace/issues/2815 , and therefore ideally would be done by the same team so that they could be tested together.

I'll increase the estimate here to be 2 hours (just in case).  This is ready for volunteers.
