### ISSUE TITLE
Export Item (to ZIP)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#777]
From release plan spreadsheet

Estimate from release plan: none
Expressing interest: none

Likely should be redesigned to use the scripts & processes endpoint

Depends on REST Ticket https://github.com/DSpace/DSpace/issues/2845

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/dspace-angular/pull/1827 which was released in 7.4.

Export of Item is now possible via:
1. Login as Admin
2. Select "Processes" in Admin sidebar.  Click "+New"
3. Select "export" script
4. In "--type", fill out "ITEM"
5. In "--id", fill out the UUID or Handle of the item to export.
