### ISSUE TITLE
Supervision Orders (JSPUI Only)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#808]
From the release plan spreadsheet; no additional notes were included.
Estimate from release plan: TBD
Expressing interest: none

Depends on REST ticket https://github.com/DSpace/DSpace/issues/2878

**Comment by abollini** [comment]
We (at 4Science) are interested in this task. See also the note on the REST ticket https://github.com/DSpace/DSpace/issues/2878

On the angular side the following activities will be needed
- mydspace: a new option in the dropdown Show (other than Your submission / workflow) will be added to provide access to the workspaceitem that you supervise. Please note that this entry will be always shown (see below to fully disable the supervision system)
- a new Supervision orders administrative menu will be included similar to the Administer workflow focused on workspaceitems so that the administrator can check for existing supervision orders, delete or create new ones

A REST configuration flag will be introduced and exposed to angular so that the supervision system can be completely disabled to don't annoy users not using such feature.

Estimation for the angular part is: 40 hours

**Comment by tdonohue** [comment]
Thanks @abollini : That all sounds reasonable. I agree this should be a configurable feature which can be turned on/off.  When off, the REST API should not allow for any supervision orders.

I'll assign to your team for 7.5 & add the estimate.
