### ISSUE TITLE
relationships management during submission

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#818]
**Is your feature request related to a problem? Please describe.**
The current implementation of relationships management during submission, introduced with [this PR](https://github.com/DSpace/dspace-angular/pull/541), doesn't take into account how the submission module has been designed.
Indeed it was designed to deal only with workspaceitems/workflowitems endpoint during the submission process. This means no operations to change metadata or to change belonging collection are made directly to related item. Every operation are made by use of submission's steps/sections. This should also be applied to relationships management while the current implementation does not do. Indeed relationships are created/changed directly to the item by mean the [RelationshipService](https://github.com/4Science/dspace-angular/blob/main/src/app/core/data/relationship.service.ts). This introduced multitude of complex work around on the submission form to allow to deal with submission's metadata state and item's metadata state. Other than that unlike recently done for item's metadata, where we have restricted the use of the /core/items/:uuid endpoint to the administrators when the items is still an inprogress submission (see https://jira.lyrasis.org/browse/DS-4278), this approach should cause security issue allowing to add/edit relationships that would not be permitted according to the submission form configuration used.

**Describe the solution you'd like**
taking into account the above and the fact that [submissionforms config endpoint](https://github.com/DSpace/Rest7Contract/blob/main/submissionforms.md) has been already changed to deal with relationship 
![Schermata da 2020-07-24 15-30-06](https://user-images.githubusercontent.com/2486489/88396295-a2637d00-cdc2-11ea-8490-447ce268c0f0.png) 
a possible solution should be to change also implementation of [submission form section](https://github.com/DSpace/Rest7Contract/blob/main/workspaceitem-data-metadata.md) allowing you to display the relationships as well as metadata and making available patch operations on the sumission-form sections to deal with relationship. The following could be the new section data representation :
![Schermata da 2020-07-24 15-43-30](https://user-images.githubusercontent.com/2486489/88397625-82cd5400-cdc4-11ea-932e-cbcba2b4f3fa.png)

**Comment by tdonohue** [comment]
Discussed in [today's meeting](https://wiki.lyrasis.org/display/DSPACE/2020-07-30+DSpace+7+Working+Group+Meeting), where we all agreed:
1. The Submission process should only use WorkspaceItem and WorkflowItem.  No direct access to Item should be allowed.
2. Therefore the code added in #541 should be refactored to work in this manner (and all future PRs should adopt this behavior).
3. In the meantime, @atarix83 added a temporary workaround in #751 in [this commit](https://github.com/DSpace/dspace-angular/pull/751/commits/090fb94c4da57df2dbe415f520d5cd0e4ae32f85).

This tasks needs estimation (both for Angular and REST, as there likely is two tasks in one here).  It also needs volunteer(s).

**Comment by benbosman** [comment]
I've verified the REST and REST contract impact of this proposal

### How can this be integrated in https://github.com/DSpace/Rest7Contract/blob/main/workspaceitem-data-metadata.md

Since plain-text and entity relationships can be mixed (e.g. for authors), it has to be part of the returned data in the DescribeStep, and not a separate section, e.g.
```json
{
  "dc.contributor.author": [
    {
      "value": "Bollini, Andrea",
      "language": null,
      "authority": "rp00001",
      "confidence": 600,
      "place":0,
      "type": "plain-metadata-value"
    },
    {
      "value": "Dahlen, Sarah",
      "language": null,
      "authority": "virtual::1373",
      "confidence": 600,
      "place":1,
      "type": "relationship"
    }
  ],
  "dc.title": [
    {
      "value": "Sample Submission Item",
      "language": "en_US",
      "authority": null,
      "confidence": -1,
      "place":0,
      "type": "plain-metadata-value"
    }
  ],
  "dc.date.issued": [
    {
      "value": "test",
      "language": null,
      "authority": null,
      "confidence": -1,
      "place":0,
      "type": "plain-metadata-value"
    }
  ] ,
  "relation.isJournalIssueOfPublication": [
    {
      "value": "f4dcd8a6-4cc4-4806-8bb9-a7e8202e05b0",
      "language": null,
      "authority": "virtual::812",
      "confidence": 600,
      "place":0,
      "type": "relationship"
    }
  ]
}
```

This will require defining the type in the metadata, making sure REST creates and returns it, and Angular understands it.

The DescribeStep will need to populate the combination of the metadata and relationships:
* If the submission forms contain selectableMetadata and selectableRelationship, the virtual metadata should be included in the metadata field
* If the submission forms contain selectableRelationship without selectableMetadata, the virtual metadata should be included in the relation."relationship" field

### Create a new Relationship would require:
* PATCH `[{"op":"add","path":"/sections/traditionalpageone/dc.contributor.author","value":[{"value":"Dahlen, Sarah","type":"relationship","related-item":"e54aebce-cc1e-4cae-a20c-5897ad24eaa8"}]}]`
* PATCH `[{"op":"add","path":"/sections/traditionalpageone/relation.isJournalIssueOfPublication","value":[{"type":"relationship","related-item":"e54aebce-cc1e-4cae-a20c-5897ad24eaa8"}]}]`
* This suggestion would require another field "related-item" to determine the item to relate with
* When receiving a PATCH on type relationship, it can be verified whether this is authorized based on the submission forms

I estimate the changes in REST, including refactoring all tests to require roughly 15-20 days of work.


## After the REST Contract and REST changes, the Angular UI would also need to be updated

### Reading the current item's values in Angular
This implies this new type property will need to be read, to determine:
* How to display the value
* How to interact with the value

Finding the current values for a field will also require checking both selectableMetadata and selectableRelationship to determine where the value is included

### Interaction with the relationships in Angular
The create/remove/move relationship actions will need to migrate to the new PATCH format as well

We don't have an estimate for Angular yet, but will work on that part as well

**Comment by abollini** [comment]
the proposal seems reasonable. I can anticipate the need to make adaption to the json representation of the metadata for the `"type": "relationship"`
Indeed, the json representation that you obtain from a GET should be aligned with the structure that you send via a PATCH, more specifically if you add
```
[{
   "op":"add","
    path":"/sections/traditionalpageone/dc.contributor.author",
    "value":[
           {
            "value":"Dahlen, Sarah",
            "type":"relationship",
            "related-item":"e54aebce-cc1e-4cae-a20c-5897ad24eaa8"
           }
      ]
}]
```
the json should become
```
"sections": {
    "traditionalpageone": {
        "dc.contributor.author": [
            {
               "value": "Dahlen, Sarah",
               "type":"relationship",
               "related-item":"e54aebce-cc1e-4cae-a20c-5897ad24eaa8"
            }
        ]
   }
}

**Comment by tdonohue** [comment]
Closing this discussion ticket, as it has now been split into two tickets (both scheduled for 7.1):
* REST Ticket: https://github.com/DSpace/DSpace/issues/2953
* Angular Ticket: https://github.com/DSpace/dspace-angular/issues/858
