### ISSUE TITLE
Remove workaround for baseUrl ending in /api

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#826]
See https://github.com/DSpace/dspace-angular/pull/825

The variable in your config for the baseUrl (rest.nameSpace or DSPACE_REST_NAMESPACE) should no longer be configured to end in /api since this isn't configurable but always required by the REST side. For now if this is still the case a warning is shown in the startup logs; and the /api is only added if it does not already end in /api as a workaround. 

Workarounds to be removed: 
The changes to set-env.ts in https://github.com/DSpace/dspace-angular/pull/825/commits/a2fa51cef5e5425698a3dc05817a1c77669aae34

**Comment by tdonohue** [comment]
@MarieVerdonck : Just a quick question on this ticket to make sure I understand your proposal here.

Are you suggesting that the configuration for `rest.nameSpace` should also be updated to default to `/server` (instead of `/server/api`)? https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.common.ts#L25

If so, that seems reasonable to me that the Angular UI should just "know" that it must contact the `/api` subpath of the REST API for all requests.  As you noted, `/api` is hardcoded into our REST API, so it's fine to also hardcode it into the Angular UI.

**Comment by MarieVerdonck** [comment]
Yes, In the linked PR; this is already changed to /server (https://github.com/DSpace/dspace-angular/pull/825/files#diff-a5ce6d09560539875d50bcdbba336788R22); so that the sitemaps reference in the robots.txt can make use of rest.baseUrl, to point to its location (without /api)
<%= dspaceUrl %>/sitemaps/sitemap0.xml  (Ex: https://dspace7.4science.cloud/server/sitemaps/sitemap0.xml)

**Comment by tdonohue** [comment]
@MarieVerdonck : Oh, thanks! I missed the context of this bug ticket.  Sounds like the right direction to me as well.  I'll add this to the beta4 board.

**Comment by artlowel** [comment]
@tdonohue I propose we move this to beta5. I asked @MarieVerdonck to do it in this way (deprecate it first, with a clear warning in the terminal, but keep it working) so everybody would have some time to fix their configs.

**Comment by tdonohue** [comment]
Done, and makes sense @artlowel

**Comment by mwoodiupui** [comment]
I must have misunderstood a comment above:  I do not see that `nameSpace` has been changed in `environment.common.ts`, either in #825 or in `main`.  Please ensure that this is done.  I just ran into the deprecation warning today when doing a production build, because I followed the pattern in `environment.common.ts`.

**Comment by artlowel** [comment]
@mwoodiupui You're right, that should have been fixed in #825. I created #877 to address this, and updated the install docs on the wiki
