### ISSUE TITLE
Default selection in create/edit screen is unclear

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#843]
**Describe the bug**
Test users have reported difficulty in understanding the behavior of the administrative edit / create features (community, collection, item). The uuid of the current object that is when possible offered as a default choice for the feature is not intuitive for a normal user, the title of the object would be much better.

**To Reproduce**
1. login as an admin / user with sufficient edit permission
2. go to one community
3. use the create community/collection or the edit community/collection left menu 

**Expected behavior**
The user should see the title of the community where the create action will occur or the title of the object that he is going to edit. The uuid must be keep as an hidden parameter used by the application. The uuid can be eventually keep visible together with the title and the search should retain the possibility to work directly with an uuid

**Comment by tdonohue** [comment]
While I agree with this ticket overall, that the side menu create/edit is confusing, I wanted to offer an alternative perspective.

When creating or editing content within the UI, I find myself (almost unconsciously) looking for a *button* that I can press on the page itself.  So, if I was going to edit an Item, I naturally browse/search for the Item. But, then I want to click an edit (or pencil) button on the Item page, rather than using the side menu.  Similarly, if I want to create a Collection, I find myself browsing to the Community and looking for a create/add button which allows me to create a Collection in that location.

I realize that what I'm suggesting here is a slightly different feature than simply cleaning up the sidebar menu (so we can move this to a separate ticket if others feel it is out of scope here).  It could be that my natural behavior is quite different from others, but I sometimes find the sidebar options less intuitive than a simple button would be.  (That said, I'm not suggesting removing the create/edit sidebar options altogether, as some may appreciate those menu options)

**Comment by mwoodiupui** [comment]
@tdonohue 's comment sounds right to me.  I can see a case for treating menu choices related to model objects as pure *navigation*, and the other choices (related to the repository as a whole) as pure *action*.  I too would first look for actions within the context of a model object on the pane for the object.

Alternately, if navigation and action-in-current-context are to be mixed together in the menu, maybe it would help to make navigation and action visibly distinct?

(I also agree that there may be no good reason not to offer both menu and in-pane actions, if there is a sizable portion of the user community who expect each.)

**Comment by artlowel** [comment]
To solve this issue, #831, #889 and #890 I propose we do the following, for all these search dialogs that get initiated from the admin sidebar:
- We leave the search box empty
- When you first open it, the first result will always be the current dso. We'll put it there. 
- That gets padded with 4 actual results you'd get for the empty query.
- If the user starts to type, we search for 5 actual results. If the current dso isn't part of those results it will no longer be shown.
- Whether it's put there by us, or shows up in a search result, the current dso will get a different background to distinguish it from other results.
- Every result will show its parent above, as is the case for new → item now. For top-level communities, we'll use "Home" like in the trail.
- Every result will get a short description below, but truncated to one line
- you can scroll down to get the next page of 5 results, as is the case for new → item
- We'll go over each of these dialogs and add context to explain _why_ you need to search for a dso if needed.


This will take an estimated **22h**. 

I agree it would be nice to have an edit button directly on dso pages as well. I would prefer that over a context menu because I'd like to keep the horizontal menu for public options only, the sidebar does a better job of communicating that the options in it require elevated privileges. 

And adding a context menu to the sidebar has little added value compared to the proposal above, the option would be just as many clicks away and not necessarily easier to find.

So i'd propose adding an small square edit button to all DSO pages if you're authorized to edit the current dso. I'd put it at the level of the title, on the right edge of the screen:

![Screenshot](https://user-images.githubusercontent.com/1567693/95980957-3f601000-0e1e-11eb-9c98-688bcb2206eb.png)


This can be done in an additional **2h**

Atmire would like to claim this ticket.

**Comment by tdonohue** [comment]
@artlowel : Your proposal here sounds reasonable to me. In my opinion, this ticket should include the **2h** for the edit button as well.  So, that brings the total to **24hrs**.

(Sidenote: This is out of the scope for this ticket. But, depending on user feedback, we could consider a "context menu" like approach similar to Confluence Wiki.  On each wiki page, you see a pencil (edit) icon in upper right, along with a `...` button, which can be clicked for additional options in a dropdown format.  So, in the future, we could consider a `...` button that adds additional options like "delete", "create [sub-object]", "export" etc.  I don't see that as high priority though, as I think the sidebar menu approach described above might be good enough for most people.)
