### ISSUE TITLE
Usability issue with submission's repeatable fields

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#864]
**Describe the bug**
The new approach used for repeatable fields during submission generated a usability problem.
Indeed is not clear for the user that to really add a field when it is repeatable, he need to click on the "plus" button. Thereby in a situation like the following screenshot the user doesn't really fill the repeatable fields and after a save data are lost : 

![Schermata da 2020-09-09 18-56-23](https://user-images.githubusercontent.com/2486489/92629604-da6d4380-f2ce-11ea-832e-5c8c83fe738c.png)

**To Reproduce**
1. start a new submission
2. fill only the first field for a repeateble metadata
3. after saving the submission, data are deleted

**Expected behavior**
In my opinion the behavior of repeatable fields should be restored to as it was previously, i.e. without the need to click on the "plus" button to add only one field, but using the "plus" button only to add additional fields

**Comment by tdonohue** [comment]
I agree with the expected behavior & can reproduce this usability issue on the demo site.  This is loosely related to #835, which pointed out that the auto-save is a bit too aggressive & also may remove values from these repeatable fields if you haven't pressed "+" before auto-save is triggered.

Therefore, I've tentatively scheduled this for beta 5 alongside #835 .

**Comment by artlowel** [comment]
I agree the way it works now is confusing and needs to be improved

But I'd like to provide some background on why it turned out this way:

- To keep UI clutter down, we wanted to avoid having hints, and buttons such as lookup and search, on every value of a repeatable field, only on the top value
- For that reason we didn't want to make the top row draggable, as it is strange if you drag the top row down, to lose a bunch of buttons, and have the new top row sprout those buttons. So the idea was to have the top row be an input field only, and have saved values in a list below. Similar to how dspace 6 does it.
- The top row is also a query field now. You can type in a query and press lookup to search for entities. #751 adds similar functionality for authority control searches. If the value of the top row was auto-saved, and the form happened to auto-save before you pressed lookup or selected an authority value, your query would end up being stored as a metadata value. Thats why we decided it would only save the entered value if the user explicitly took action (clicking the plus button)

**Comment by tdonohue** [comment]
Thanks @artlowel for the summary behind this decision. However, I do think we need to think further on the best behavior here, as with this current behavior and #835 (aggressive auto-save), data loss is unfortunately frequent.  

I think we need to step back and look at the behavior we want to achieve, and how to make the interaction more user friendly -- currently, the need to press the "+" is not obvious, and the auto-save makes it frustrating if you forget. At the same time, it is also not the fault of the auto-save feature, as if you forget to hit the "+" and click "save" manually, you also lose your entered metadata.

**Comment by tdonohue** [comment]
Note: I've found this behavior of the "+" button also causes this bug: #884 

Simply put, if you enter in a value _without clicking "+"_, the submission form thinks you've still entered that value. So, for example, it'll put a green checkmark next to the section even if you forget to click "+" next to your entered author name.  This results in the "Deposit" button being enabled before it should be.  Clicking on "Deposit" throws an error & locks up the form as described in #884

**Comment by atarix83** [comment]
To solve this issue we propose to automatically add an edited repeatable field when the field loses the focus. In this way we can avoid the main issue and at the same time we can maintain useful sorting functionality and keeping UI clutter down as noted by Art. 
This work can be done within estimation given for https://github.com/DSpace/dspace-angular/issues/835

**Comment by artlowel** [comment]
Won't the field lose focus if you type a query and click the lookup or search buttons? We need a way to prevent search queries typed in that box from being stored as metadata

**Comment by tdonohue** [comment]
As discussed today, for now we are going with the "Add" button approach -- change the "+" button to say "Add" and still require it to be pressed before a value is saved.  This behavior is identical to DSpace 6.x XMLUI behavior for repeated fields, and therefore is good enough for 7.0.  It could be enhanced in a later 7.x release as needed.

The estimate for this ticket is set to **0 hr** as it is included in the estimate on #835 & will be solved by that ticket.  See [this comment for details](https://github.com/DSpace/dspace-angular/issues/835#issuecomment-709429248).

**Comment by tdonohue** [comment]
We expect this bug will be fixed by the (in progress) fix for #971

**Comment by tdonohue** [comment]
I've verified this is fixed by #1025
