### ISSUE TITLE
Submission embargo bug

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#869]
**Describe the bug**
Embargoes for files are not working in the submission, it contains a group selection without groups

**To Reproduce**
1. Start a submission
2. Upload a file
3. Edit the file
4. Select in "Access condition type" e.g. embargo
5. Select the Group
https://www.dropbox.com/s/6p2slc4pdmwbym8/Schermafdruk%202020-04-29%2016.30.10.png?dl=1

**Expected behavior**
It should know in advance this is specific to the Anonymous group (not display the dropdown).
If there is a use case for multiple options, the dropdown should display groups

**Comment by cwilper** [comment]
## Findings

The "select group" functionality has multiple problems:

* The dropdown doesn't get enabled and populated at the appropriate time due to flawed logic in [section-upload-component.ts](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/upload/section-upload.component.ts) -- the code incorrectly enables it for any configured access condition type where there is a required start date or end date.
* By design, it relies on the ability of the submitter to make an administrative REST request to retrieve the sub-groups of a configured "select group".

The "access conditions" functionality at large has the following problems:

* The [SubmissionUploads REST API documentation](https://github.com/DSpace/Rest7Contract/blob/main/submissionuploads.md) is incomplete. It omits any mention of `groupUUID` and only describes `selectGroupUUID`. These directly correspond to `groupName` and `selectGroupName` as configured and described in [access-conditions.xml](https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/access-conditions.xml).
* When an access condition is selected on the client side, the PATCH request includes the access condition's corresponding group UUID, which the server then blindly trusts, regardless of whether it is configured. This makes it possible for a submitter to give read access to groups that the repository administrator may not have allowed per configuration.

## Recommendation

* Simplify the functionality of "access conditions" by getting rid of the "select group" functionality altogether.
  * It wasn't a capability in DSpace 6
  * It isn't used in out of box configuration
  * It introduces a new access control problem that is not trivial to solve: How to provide a list of subgroups to a submitter without requiring them to be a repository administrator or giving all submitters inappropriate, broad access to group membership information.
* Adjust the REST API to stop using UUIDs to convey the specific group that an access condition is associated with. Instead, only the "access condition name" as configured in Spring should be used (e.g. "embargo", "administrator"). When processing the PATCH request upon the user making a selection, the server should do a lookup in the config to determine the appropriate group.
* Update REST documentation accordingly.

## Estimate

6 hours

**Comment by tdonohue** [comment]
Thanks @cwilper for your analysis & recommendations here.  

However, I think this "select group"  feature *did* exist in DSpace 6.  Here it is in this screenshot in our docs of this feature: https://wiki.lyrasis.org/display/DSDOC6x/Embargo#Embargo-Restrictlistofdisplayedgroupstospecific(sub)groups

That said, I think you are correct that it's a security/access problem to allow any submitter to select from groups which they cannot/should not "see".  At a glance, it looks like the `selectGroupName` field was meant to limit which groups the submitter is able to select from (to only subgroups of that `selectGroupName`), but that in itself seems a bit "hacky" and problematic.

All in all, I think your approach here sounds reasonable.  For those who want multiple embargo group options, they could simply modify `access-conditions.xml` to add additional selectable embargo options with different groups (e.g. "embargo then public", "embargo then campus-only", etc).

Thanks! I've added your **6 hr** estimate to the ticket label.

**Comment by benbosman** [comment]
The REST part has been implemented in https://github.com/DSpace/DSpace/pull/3136, this required more than the expected 6 hours because there were even more bugs in the API than expected

With the REST part ready, we can also estimate the Angular part, this is expected to require 13 hours of work. We can work on this implementation

**Comment by tdonohue** [comment]
Thanks @benbosman . I've updated the estimate. I've kept it assigned to you so that your team can start on this.

**Comment by abollini** [comment]
@tdonohue as noted in https://github.com/DSpace/DSpace/pull/3136#issuecomment-773474396 I suggest to reconsider this decision or to create a followup action to restore the functionality.

The issue can be solved as follow
1. instead than expose the uuid of the parent group containing the selectable (sub)groups having  we would have modified the access condition configuration exposed via REST to directly list the group and the uuid. This should mean a json like that
```
{
  "id": "default",
  "required": true,
  "max-size": 536870912,
  "accessConditionOptions": [
		{
 			"name": "openaccess"
		},
		{
 			"name": "administrator"
		},  	 			
		{
 			"name": "embargo",
 			"options": [{"label": "Group 1", "value": uuid1}, {"label": "Group 2", "value": uuid2} .... ]
 			"hasStartDate": true,
 			"maxStartDate": "2018-06-24T00:40:54.970+0000"
		},
		{
 			"name": "lease",
 			"options": [{"label": "Group 1", "value": uuid1}, {"label": "Group 2", "value": uuid2} .... ]
 			"hasEndDate": true,
 			"maxEndDate": "2017-12-24T00:40:54.970+0000"
		}
  ]
}
```
2. the patch operation could have been extended to protect against illegal attempt to select unexpected group (that should lead to a 422 as the parameter is semantically unvalid/unexpected)

Our estimation for these change is 8 hours for the REST/Contract side, 4 hours on the Angular side

**Comment by tdonohue** [comment]
@abollini : I've created a new follow-up ticket & scheduled it tentatively for 7.2 https://github.com/DSpace/dspace-angular/issues/1011  Could you copy your recommendations & estimate over to that ticket?

Unfortunately, I don't feel we have sufficient time to rethink this now.  I'd much rather reschedule this for later, so that we can spend more time ensuring that we aren't accidentally opening up security issues here.  Thanks!
