### ISSUE TITLE
[Submission] Date & dropdown not properly indicated as mandatory

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/dspace-angular#882]
**Describe the bug**
When you have mandatory oneboxes or textareas & you add some metadata, the mandatory fields will receive a red border & the mandatory text pops up. This doesn't work for the date / dropdown fields if they are mandatory.

**To Reproduce**
1. Alter the submission-forms.xml to make a date and a dropdown field mandatory. 
2. Restart the REST tomcat
3. Start a submission & add some metadata to the title
4. The Abstract field will receive the red border & a help text to indicate that this is mandatory will pop up.
5. The above doesn't happen for the date / dropdown fields.

**Expected behavior**
The red border should show up & the required text should be displayed.

**Comment by artlowel** [comment]
Fixing this will take an estimated **2h**

**Comment by artlowel** [comment]
Atmire is interested in claiming this

**Comment by artlowel** [comment]
After further analysis it turns out these fields can already be styled as invalid correctly, but they're not because a 'touched' mechanism already exists in the ng-dynamic-forms lib, and these specific fields only show errors when they've been touched first. However it doesn't work in practice: if you touch them without saving they don't become invalid, and if you save the touched status is reset to false.

I'd suggest this be fixed in the context of #835

**Comment by tdonohue** [comment]
Closing, as noted above this was fixed in #960, as that disabled the auto-save
