### ISSUE TITLE
problematic Angular compiler setting: set preserveWhitespaces to default value (false)

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#903]
**Describe the bug**

The Angular compiler setting `preserveWhitespaces` (https://angular.io/api/core/Component#preserveWhitespaces) was set to `true` which is **not** the default value (see `main.browser.ts`).

This results in unintentionally added whitespace, e.g. in the list of search results

![image](https://user-images.githubusercontent.com/952735/96338176-99660d00-108c-11eb-813b-550f964b500c.png)

1. go to https://dspace7-demo.atmire.com/mydspace?configuration=workspace&page=1&query=20201017&scope=

**Expected behavior**

Superfluous whitespace characters should be removed from the compiled template.

Set `preserveWhitespaces` to default value (`false`) or remove setting in `main.browser.ts` completely.

**Comment by saschaszott** [comment]
By changing the compiler option to `false` (or by removing the option) whitespace between `span` elements is removed. To preserve whitespace (without changing the compiler option), you can use the Angular entity `&ngsp;` which is replaced by a space in the rendered HTML.

**Comment by artlowel** [comment]
That option was purposefully enabled by @atarix83 in [this commit](https://github.com/DSpace/dspace-angular/pull/384/commits/31e2a9ca2998fd84e3e0e4b661384ea371aee16d#diff-f6a7e26673fdcb7e26c58a785bb61abc2d43a1fa828bb67fe0a87099e1c016c8R5) for his [MyDSpace PR](https://github.com/DSpace/dspace-angular/pull/384).

Do you remember why @atarix83?

**Comment by saschaszott** [comment]
whitespaces between `span` elements in template blocks that need to be reviewed if you decide to change the Angular compiler option:
* `<ds-truncatable> … </ds-truncatable>`

**Comment by tdonohue** [comment]
It sounds like setting `preserveWhitespaces` back to the default of `false` is recommended to "greatly reduce AOT-generated code size and speed up view creation" according to https://angular.io/api/core/Component#preserving-whitespace

So, I'd be in favor of trying to set this back to the default value, if it doesn't cause issues....and, as recommended, use either `&ngsp;` or `ngPreserveWhitespace` attribute in templates that need whitespace preserved. 

@atarix83 : could you take a look at this ticket & advise on whether there's a reason why we need `preserveWhitespaces=true` set globally?

**Comment by atarix83** [comment]
@artlowel @tdonohue 
the reason is that helped to regain white spaces between Bootstrap buttons. Otherwise this the result
![Schermata da 2020-10-20 19-14-07](https://user-images.githubusercontent.com/2486489/96621116-8495ad80-1308-11eb-9272-648f73b504aa.png)

**Comment by atarix83** [comment]
while whitespace in the list of search results for mydspace page are not unintentional

**Comment by tdonohue** [comment]
I still think we should look to revert this setting and go back to `preserveWhitespaces=false`, as it sounds that that will result in a smaller application size & minor speed improvements.   If we are finding that *specific areas* of the code need extra spacing, we should preferably use Bootstrap styles (e.g. `mx-2` will set a margin on left/right of 2, see [spacing](https://getbootstrap.com/docs/4.1/utilities/spacing/))....or if those don't work, we can annotate the button section with `ngPreserveWhitespace`, so that whitespace is only preserved for the buttons, but not elsewhere on the page.

In any case, I see this as low priority right now. Tentatively scheduling for 7.1. If someone wants to volunteer to do this earlier, I'm all for it, but it seems minor compared to other open bugs.
