### ISSUE TITLE
If you open Communities & Collections directly,  the result list is empty.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#908]
If you open Communities & Collections directly (go to https://dspace7-demo.atmire.com/community-list), the result list is empty.

_Originally posted by @saschaszott in https://github.com/DSpace/dspace-angular/issues/899#issuecomment-711028738_

May or may not be related to #899

**Comment by artlowel** [comment]
I expect this will be due to the [zone.runOutsideAngular](https://github.com/DSpace/dspace-angular/blob/main/src/app/community-list-page/community-list-datasource.ts#L29) call in datasource. SSR will think the page is done rendering as soon as that call occurs, and send the result to the client.
While runOutsideAngular can improve the responsiveness of the UI on the client, we may need to remove it here to prevent this issue.

I expect this and #899 together will take **3h** to fix.

Atmire is interested in claiming these tasks

**Comment by tdonohue** [comment]
Sounds good @artlowel .  I've assigned this back to you for your team & moved to "in progress".  Also added #899 to the beta5 board and assigned to you as well.
