### ISSUE TITLE
Discovery facets displaying incorrect items

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#915]
**Describe the bug**
When selecting a facet, the result contains items which don't exactly match the facet value. It seems to only match on one word

**To Reproduce**
1. Open https://dspace7-demo.atmire.com/search?page=1&f.author=pujari,%20kb
2. Verify it matches the author `pujari, kb` and `pujari, K B`

**Expected behavior**
Only exact matches should be returned

**Comment by tdonohue** [comment]
Thanks for clarifying @KevinVdV .

1. I've transferred this ticket to `dspace-angular`, as the actual bug is an invalid query sent from Angular to the REST API.  @artlowel would you be able to estimate what the effort would be to simply change the request that Angular is sending (see @KevinVdV's notes above)?  My assumption is this should be **1-2hr** but I wanted to make sure I wasn't missing anything.
2. I've created a *new ticket* to describe how the REST API can better protect against this invalid query (by throwing an error instead of returning results): #3027   I've moved your estimate over to that ticket, @KevinVdV

**Comment by artlowel** [comment]
In order to fix this we need to parse the operator from the search link in the FacetValue when using a checkbox or date widget and use it in rest requests. When using the filter input we need to add the query operator.

This will take an estimated **4h**

Atmire is interested in claiming this task

**Comment by tdonohue** [comment]
Thanks for the estimate @artlowel .  Sounds reasonable.  I've added it to this ticket & reassigned back to you (for your team to work on) & moved to the "in progress" column.
