### ISSUE TITLE
Restricted bitstream access does not work when opening a new tab/window

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#924]
1. Create a new Item with an atachment
2. Add Read access to Admin user for both, Item itself and the bitstream representing attachment
3. Remove Read access to Anonymous group from item and bitstream
4. Go to Item view and press the attached file, it gets downloaded = OK
5. Right click attached item and open it in new browser tab - **Error** page (401) gets presented

Expected - if browser contains valid "dsAuthInfo" token Cookie, resource link should allow access to resource.

Details - existing solution of access to bitstream requires "shortlivedtoken" which gets fetched by a separate backend request to **DIFFERENT?** host : https://dspace7.4science.cloud/server/api/authn/shortlivedtokens
(on my local setup the shortlived token gets delivered from the same host)

This setup is either "temporary" solution or unclear why used - token gets requested from same server where bitstream is comming from, if actually needed, backend can produce the token internally ?

**Comment by tdonohue** [comment]
I'm able to reproduce this issue locally & on the demo site.

The issue appears to be that a normal file download looks like this:
1. If authenticated, first request a `/shortlivedtoken` from the backend (regardless of whether the bitstream is actually restricted or not)
2. Use that token to download the file (e.g. `http://localhost:8080/server/api/core/bitstreams/[uuid]/content?authentication-token=[shortlivedtoken]`)

When you use your browser to open the file in a new tab (right click on file & select "open link in new tab"), the first step is always skipped.  In other words, the link that opens in the new tab is simply the full REST API URL of the Bitstream, with no additional params (e.g. `http://localhost:8080/server/api/core/bitstreams/[uuid]/content`)

This same behavior also occurs when you open the link in a new window.

@artlowel and @KevinVdV : this appears to be a flaw with how `shortlivedtoken`s currently behave based on the initial implementation in https://github.com/DSpace/DSpace/pull/2783 and https://github.com/DSpace/dspace-angular/pull/716  (see also initial ticket at https://github.com/DSpace/dspace-angular/issues/631)

I'm not exactly sure how we could solve this, other than maybe via a UI-level *proxy* for all downloads (similar to what was done for Google Scholar in #868).  A proxy would mean that the newly opened/tab window would *still use* a Angular UI URL instead of attempting to go straight to the REST API. Thoughts?

**Comment by MarisArins** [comment]
Hi guys, the problem is demonstraded via new tab, but the actual problem behind it is that you cannot use this resource URL (decorated with Shibboleth callback) to include it in a mail, in another page/application.

I am pretty sure this is not a main concern of DSpace, but eventually a great feature gets crushed by this: access to authorised resources via links.

Why is the short lived token a requirement here at all ? 
We are talking about authorised user (valid dsAuthInfo in context) accessing backend to generate a token that is for some reason a must for next request to fetch bitstream from the same backend. Backend already know the requester is OK, as it used Authorization information to provide the token (so I see it).

This extra step and extra token stops this feature. If its totally mandatory, why the bitstream serving endpoint does not incorporate this token preparation internally?

**Comment by MarisArins** [comment]
e.g This opens for you ITEM page if you are pre-authorized in Shiboleth :
https://dspace-test.expertquality.lv/Shibboleth.sso/Login?target=https://dspace-test.expertquality.lv%2Fserver%2Fapi%2Fauthn%2Fshibboleth%3FredirectUrl%3Dhttps://dspace-test.expertquality.lv/items/e5cfafd0-e91d-4644-a922-671c4996093a

Similar link to bitstream will not go, as it needs token :
https://dspace-test.expertquality.lv/Shibboleth.sso/Login?target=https://dspace-test.expertquality.lv%2Fserver%2Fapi%2Fauthn%2Fshibboleth%3FredirectUrl%3Dhttps://dspace-test.expertquality.lv/server/api/core/bitstreams/0f22d88d-7e6b-46f8-81b3-cb58ae677adc/content

**Comment by tdonohue** [comment]
@artlowel and @KevinVdV :  It appears to me that setting `rewriteDownloadUrls=true` as a *default setting* would likely solve this bug (as that ensures the `shortlivedtoken` is requested even if I open the link in a new tab).  However, that setting appears to be partially broken -- as it's triggering a (seemingly unnecessary) hard refresh in the browser.

**Comment by MarisArins** [comment]
@tdonohue/@artlowel  - the "dsAuthInfo" token gets always sent to backend!
thats what browser engine does by default.

short lived token request : 
![image](https://user-images.githubusercontent.com/2697696/97777377-781b1b80-1b78-11eb-8c69-153fafdee007.png)


resource request:
![image](https://user-images.githubusercontent.com/2697696/97777401-a3056f80-1b78-11eb-957b-1e36272712d5.png)

If it contains the same JWT, there is not much of difference. Also stored in Cookie or in session variable this token expires the same. Cookie is just a default header type, so no difference of security in this regard as well.

**Comment by tdonohue** [comment]
@MarisArins : Apologies, I overlooked your response back.  My [earlier comment](https://github.com/DSpace/dspace-angular/issues/924#issuecomment-719694274) about the `dsAuthInfo` cookie was rushed...and you are **correct** of course that the `dsAuthInfo` cookie may be automatically included in the browser requests to the REST API (as that is how browsers work).

However, this behavior is exactly what can result in a [CSRF attack](https://owasp.org/www-community/attacks/csrf). If the backend blindly "trusts" the `dsAuthInfo` cookie & the browser sends it automatically on every request, then a hacker could trick someone into clicking a link that automatically sent a request to the REST API to delete or add content using their `dsAuthInfo` cookie. That's exactly what we want to avoid.

Long story short, we are working on tightening the security of the REST API to avoid this sort of behavior (see #907).  Once completed, our REST API will **not trust** any auth tokens that are sent via cookies (because we have no control over when a cookie is sent or not sent).  Instead, auth tokens must be sent via HTTP Headers to ensure they are trusted (as HTTP headers are not susceptible to a CSRF attack).  This is per recommendations of [OWASP for CSRF prevention](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html)

In any case, this is all a sidenote for this ticket.  As I described above, we must find a way to get the `shortlivedtoken` to work more appropriately in the scenarios you've documented.

@artlowel and @KevinVdV : I'd still appreciate your feedback on this[ per my comment above](https://github.com/DSpace/dspace-angular/issues/924#issuecomment-719717589).

**Comment by artlowel** [comment]
@tdonohue I don't see a way to make `shortlivedtoken` work in the scenarios described by @MarisArins. Its very nature requires that we only retrieve it right before you download. The browser can't do that automatically, it can only be added if you download through the app.

I also don't see how enabling `rewriteDownloadUrls` without change would affect this. 

To test this I've made the bitstreams test-pdf.pdf and test.zip on [this item](https://dspace7-demo.atmire.com/items/96715576-3748-4761-ad45-001646632963) only available to registered users. 
`rewriteDownloadUrls` is enabled on the demo server, but it doesn't bypass the issue @MarisArins is reporting for me. 

I can't reproduce your hard-refresh issue either. Admittedly the pdf file opens in the browser, but that's exactly what would happen if it wasn't access restricted. The zip file downloads as expected, no refreshes.

Correct me if I'm wrong but isn't the CSRF issue with cookies only relevant if the UI and rest api are hosted on different domains? If we can allow a cookie for authentication when they're on the same domain, most dspace 7 installations won't have this issue.

And for the ones that do, I guess we could modify the download proxy in the universal server to use the dsAuthInfo cookie to set the authentication header when a bitstream is downloaded, as they might need `rewriteDownloadUrls` anyway. If they don't, they can opt to keep using the `shortlivedtoken` with the shortcomings noted in this ticket, which aren't major dealbreakers in my opinion.

**Comment by tdonohue** [comment]
@artlowel : Thanks for your analysis & for proving that `rewriteDownloadUrls=true` is not a possible solution. (Sidenote: I'm no longer able to reproduce the hard refresh I had previously seen, so I'm guessing I did something wrong during those tests)

With regards to CSRF... no, despite the name, it has nothing to do with whether the backend/frontend are on the same or different servers/domains.  Here's a nice, simple explanation of CSRF: https://portswigger.net/web-security/csrf

CSRF really just requires that you are using *cookie-based* session/authentication & are tricked into clicking a link or visiting a hacked webpage.   Here's how it would easily work in DSpace regardless of whether the backend/frontend are on the same domain:
1. Suppose you login as an Admin & your session/auth info is active therefore in a `dsAuthInfo` cookie.
2. A hacker spoofs/tricks them into visiting a webpage which immediately sends a PATCH request to the backend to change their password.  (Technically, this request *might* end up blocked by CORS if a DSpace site has done a good job limiting which clients can send requests to the backend. But, for the purpose of this example, image the hacker has managed to create this webpage under a trusted domain, e.g. a student hacker who puts up a custom webpage under their university's domain.)
3. If you click on that webpage, your browser will *automatically* send along the `dsAuthInfo` cookie (as that's normal browser behavior).  If the backend trusts the cookie (it should, as the cookie is coming from the same browser it sent it to), then the PATCH action will be immediately performed.
4. At this point, the hacker has changed your password just by knowing what a valid PATCH request looks like & tricking you into clicking something. They didn't need to know your original password, as you had a trusted auth cookie active in your browser & that cookie was sent automatically to the backend without your knowledge/consent.

So, essentially, the cookie idea is insecure, unless we also enabled Spring's CSRF protection on the backend (Which isn't possible as that doesn't play well with Shibboleth, see https://github.com/DSpace/DSpace/pull/2922#issuecomment-701531443).

This is exactly why (in https://github.com/DSpace/DSpace/pull/3001) I've taken a different approach of modifying the backend to **no longer trust** auth cookies at all (except when it can verify the auth cookie is used in Shibboleth auth). Once that PR is accepted/merged, auth tokens will be required to be sent via headers at all times (except for Shibboleth alone).

All in all, I think your idea of having the download proxy *use* the stored `dsAuthInfo` cookie may be a reasonable solution here. If I'm understanding correctly, that seems like it would fix this issue if a site enables `rewriteDownloadUrls`.

**Comment by artlowel** [comment]
Thanks for the explanation. 

Doesn't the exact same problem pose itself if we use the dsAuthInfo cookie to create the header on the universal server though? Why is it secure for it to trust that cookie while it wouldn't be for a rest server on the same host?

**Comment by tdonohue** [comment]
@artlowel : Because there's not really a way for a hacker to automatically *trigger* a call to the Universal server to both tell it to *parse* that `dsAuthInfo` cookie and send it the corresponding Headers to the REST API path/command of the hacker's choice.   

So, for example, the hacker cannot tell the Universal server to send an EPerson PATCH request (to change your password to something the hacker knows) to the backend using your currently active `dsAuthInfo` cookie. The main difference here is the Universal Server is not an open REST API that you can send any request to & have the browser run that request.  The only interactions you can force in the Universal Server are the interactions available in the Angular UI (and while you can change passwords via the Angular UI, there's no way to do that programmatically via an external link / request).

But, obviously our REST API *is an open API* that anyone can send requests to (provided they pass CORS). Therefore, **if** the REST API is written to trust the `dsAuthInfo` cookie, then the hacker only needs to know the correct REST API call to trick you to click on. He doesn't need to know what is in your `dsAuthInfo` cookie (or even need to parse it himself), as your browser will send it along automatically to _any call_ to the REST API & the REST API will then automatically parse & trust it.

**Comment by benbosman** [comment]
Hi @tdonohue , @artlowel ,
I've read through this ticket in detail to identify potential other solution.

What I concluded (correct me if I'm wrong) is:

**How REST can be abused if cookies are allowed**
* Assume angular is hosted on dspace7-demo.atmire.com and REST is hosted on dspace7.4science.cloud, but a hacker creates a webpage on malware.4science.cloud
* The website malware.4science.cloud contains code e.g. to change your password.
* If the user visited dspace7-demo.atmire.com, and authenticated, they have a valid cookie in their browser for dspace7.4science.cloud. If they hereafter navigate to malware.4science.cloud, the user's browser will send the change password request to dspace7.4science.cloud combined with the cookie, and it's accepted if rest.cors.allowed-origins contains *.4science.cloud (could be configured as such if there are other sites in *.4science.cloud which will use the backend)
* This exploit also works if Angular and REST are on the same host, the Angular hostname is not relevant here (only rest.cors.allowed-origins can protect the user)

**How this can still be used without the security risk**
* Assume REST won't read the cookie, unless downloading a file
* Assume angular is hosted on dspace7-demo.atmire.com and REST is hosted on dspace7.4science.cloud, but a hacker creates a webpage on malware.4science.cloud
* The website malware.4science.cloud contains code e.g. to change your password.
* If the user visited dspace7-demo.atmire.com, and authenticated, they have a valid cookie in their browser for dspace7.4science.cloud. If they hereafter navigate to malware.4science.cloud, the user's browser will send the change password request to dspace7.4science.cloud combined with the cookie, **but REST won't read the cookie for a change password request**
* If malware.4science.cloud contains code to download the file, the user's browser will send the download file request to dspace7.4science.cloud combined with the cookie, and REST will send the file to the user, but the hacker can't access the file. They can't do anything except for causing the user to download a file to their computer for which the user has permissions

So if we allow cookie authentication in REST for file downloads only, the CSRF risk is not present because there is no relevant action for the hacker left

**Comment by tdonohue** [comment]
@benbosman : Thanks for your comments, and your overall logic is **completely correct**.  

The only risk here is if the hacker somehow uploaded that file into DSpace in the first place (which is a real risk if they are, for example, a student/staff at a university with submit privileges).  If that is true, then the scenario you laid out is still potentially dangerous, as they can *force you* to download a file...if the file you download is corrupt or a script, then they can potentially compromise your system or even write a script that can read your local cookie. (NOTE: This is definitely getting into edge case scenarios though, and technically this same scenario could be possible regardless of whether this cookie exists, e.g. if the file is public file they could trick you into downloading it without a cookie).

In any case...your approach of limiting to only _reading the cookie during a download might be reasonable_.  The primary issue becomes in the implementation of that in the REST API, as that idea currently doesn't align so well with the work in PR https://github.com/DSpace/DSpace/pull/3001.  

More specifically, in that PR, I've switched the REST API to *destroy* any auth-based cookies after reading them, making them "single use cookies" only trusted for specific scenarios (in the case of PR 3001, the only scenario allowed is a Shibboleth login).  The reason for that approach is to discourage us (DSpace developers) from any reliance on auth-based cookies, because we have Spring's built-in CSRF protection **turned off**.   Ideally, we'd have Spring's CSRF protection on, which would make auth cookie usage safer. But since that doesn't seem to be possible (cause of Shibboleth), we need to avoid auth cookie usage in the REST API as much as possible.

So, if we were to use a single-use cookie for these file downloads, that'd imply:
* The `dsAuthInfo` cookie cannot be used (as it'd be destroyed after reading it in the REST API)
* A different single-use cookie would need to be created _prior to the download request_.  This would be a scenario that is very similar to the "short lived JWT" token which already exists for restricted downloads (as that token also needs to be created prior to the actual download request). Per this ticket, that concept (of two requests for a download) doesn't work for restricted bitstreams opened in a new tab/window.

The only other option here would be to use `dsAuthInfo` without destroying it. But, that seems risky to me, as we'd need to be certain it's not accidentally used/read anywhere else in the codebase in the future. (My worry would be a future developer would decide to simply use `dsAuthInfo` again because "it's there" without understanding the risks associated with trusting that cookie in the REST API).  This is one of the reasons we chose to move towards a "short lived JWT" for file downloads & not simply use an auth cookie in https://github.com/DSpace/DSpace/pull/2783

If need be, we could discuss this in an upcoming DSpace 7 meeting. But, my opinion is still that the "easiest" fix may be to proxy this download through the Universal Server...it could make the initial request for the "short lived JWT", then send it back in the download request.

**Comment by abollini** [comment]
@tdonohue  I like the idea to limit auth cookie send to the backend single use only, nevertheless I don't see how this can help in the scenario of multiple tab described by this issue. If the user right click and open the link in a new tab (or new window) no cookie will be present here. Moreover, I guess that @MarisArins also noted a very important use case here https://github.com/DSpace/dspace-angular/issues/924#issuecomment-719651676
there is no way for a `GET` request to the REST API that fail the authz to be solved in the browser, i.e. to be redirected to the login as the WWW-Authenticate is not enough standardized to suggest things understandable by the browsers other than Basic Auth. This mean that we need an Angular URL that allow to download a single bitstream, as said by @artlowel this should be not a proxy otherwise would make the browser unresponsive and could crash for large file but instead should check the permission, allow you to authenticate (this will happen all the time that you use the direct link or the open in a new tab/window), get the short-lived-token and redirect you to the REST API.
In this way I expect also that a web crawler can extract the bitstream (angular) URL from the item page and offer that URL to the user of the search engine, it will lead to an authentication page if protected or to an automatic (temporary) redirect to the REST API

**Comment by benbosman** [comment]
I've been thinking about this thread for a while, also based on our last meeting where we were looking for alternative solutions which avoid proxying the files since that would be big disadvantage.

A solution which should be simple and solve the issue can be:
* An item page (e.g. https://dspace7-demo.atmire.com/items/42c216ca-6e08-40de-86b9-7f8c33591646) would not link to the content in REST (e.g. https://dspace7-demo.atmire.com/server/api/core/bitstreams/c4cb17fe-bf68-4864-8060-d9cd27998386/content) but rather a page in Angular (e.g. https://dspace7-demo.atmire.com/bitstreams/c4cb17fe-bf68-4864-8060-d9cd27998386/content)
* This page in Angular would not proxy the content, but would create a short-lived-token if the user is authenticated, and redirect the user to the content in REST
* Bots and anonymous users would simply open a page which redirects to REST. Using an immediate redirect, this should not affect the user experience
* Authenticated users would also open a page which creates the short-lived-token and redirects to REST with the short-lived-token. This is also supported when opening the link in a new tab

This solution should be simple to implement, support opening in new tabs, support bots, avoid proxying the data, and avoid using cookies

**Comment by artlowel** [comment]
To implement this feature in the UI:
- We'll add the page `/bitstreams/:uuid/download`
- When the page loads we'll first GET the bitstream
- if the server returns a 404, we'll redirect to the 404 page
- If the server returns a 401 or 403
	- and the user is not authenticated, they'll be redirected to the login page first, and redirected back after logging in
	- and the user is authenticated, they'll be redirected to the forbidden page
- Otherwise we'll use the canDownload feature to see if the user has the rights to download the bitstream
- If they have the rights 
	- and they're not authenticated, we simply redirect to the content url on the rest side
	- and they're authenticated, a short-lived token will be requested, and the page will redirect to the content url with the short lived token
- if they don't have the rights
	- and they're not authenticated, they'll be redirected to the login page first, and redirected back after logging in
	- and they're authenticated, they'll be redirected to the forbidden page
- We update the download-file component to use to the new page. And get rid of obsolete code regarding private downloads
- This will take an estimated **16h**



**Notes:**  
- We can only set status codes for a page when using server side rendering. When rendered server side, this download page will get a 302 (I wouldn't use 301, as that may encourage search engines to index the url it redirects to instead), but when rendered client side we can't help it being 200.
- That means we should use traditional links for file downloads, not angular's routerlinks that redirect within the framework, to ensure the download page always comes from the server.
- We will no longer need the rewriteDowloadUrls environment property added in #868, as download URLs will always be UI urls now.
- However in general search engines may not like this way of working, as our download URLs are pages (that always redirect to boot), not files.
	- an alternative might be to only use new pages for restricted bitstreams, but that will make things more complicated to implement, and to explain to users. It would also require us to keep in the rewriteDownloadUrls property

**Comment by tdonohue** [comment]
@artlowel : That sounds reasonable.  I agree that the ideal here is to remove the `rewriteDownloadUrls`... I think we should start with this approach of treating all bitstream downloads the same. We can always have Google Scholar test it out, and improve on it if they find issue with it. (If you feel we may want to bring this up with Google Scholar earlier, that's also an option -- I could ask them for a meeting, though it'd be nice if you can attend in case they want further details on the proposed new behavior.)

In any case, I'll add the **16h** estimate to this ticket and assign it to you for your team to work on.  Thanks!
