### ISSUE TITLE
Required repeatable fields get validated incorrectly in submission form

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#931]
After last changes to require repeatable items to be added with "+" button to save those there is a problem with validation.
Validation (checking mandatory fields) still check the original input fields, not the added extra elements (the one are added below original input fields)

Here is example of Author and Other Titles fields. Both have 1 element added with + sign, the original fields(do not get saved !!!) are empty, validation not passed:
![image](https://user-images.githubusercontent.com/2697696/98128530-b68a4080-1ec0-11eb-9021-f8b80b76bbce.png)

Here are the original fields filled with dummy values (do not get saved), validation passed : 
![image](https://user-images.githubusercontent.com/2697696/98128805-06690780-1ec1-11eb-90ea-703ac2b6c93e.png)

Expected :
Validation for repeatable fields check if there is at least 1 element in the associated array, no checking of original input fields

**Comment by tdonohue** [comment]
This behavior is directly related to #835 and #864.  I'm able to get the green checkbox to appear *without* filling out additional values, provided that I trigger the auto-save.  In other words, validation doesn't occur until the auto-save is triggered, so the order in which you fill out the fields currently makes a big difference.

In other words, this order works fine:
* Add an "Author" by entering a name and clicking "+"
* Add an "Other Title" by entering text and clicking "+"
* Add a "Date of Issue"
* FINALLY, add a "Title".  Editing/Changing Title always triggers "auto-save" once the field loses focus.

If you perform those steps in order, then the green checkbox appears. So, the bug here is related to when the auto-save is triggered & how the "+" button works.  This will end up being resolved by the fix to #835

**Comment by MarisArins** [comment]
@tdonohue ,

Yes Tim, your/demo site case might work... but as soon as you would add a single required field in 2nd segment of submission form, there would be another validation/save happening and on that the first segment fields would undergo validation as well and green check would be replaced by "failed" exclaimation mark unless the original fields get filled again.
This "mutually exclusive" validation cycle takes some skill to work around if there are several segments with mandatory elements!

**Comment by MarisArins** [comment]
P.S.
I removed all  "submission.autosave.metadata" values in config and it minimizes the saving/checking cycles, but once the segment is filled and I try to fill next segment, it still autosaves and accordingly cleans unsaved inputs in other segments.
For example I confirm deposit licence - autosave happens.

**Comment by tdonohue** [comment]
@MarisArins : Thanks for the addition feedback.  I still believe this ticket depends heavily on #835 being resolved (as described in that ticket).  As noted in that ticket, we are aware that auto-save is currently highly intrusive & may clear values that are currently being typed or (for multi-value fields) have not been explicitly saved by pressing "+".

I'll leave this ticket open so that we can retest when #835 is fixed to be sure this bug is also fixed.

**Comment by tdonohue** [comment]
This issue should be resolved by the solution to #971

**Comment by tdonohue** [comment]
Retested today when testing #1025 and I've verified that PR will fix this issue.
