### ISSUE TITLE
Dspace Theme is not working properly

### ISSUE THREAD

**Issue by dsipos-dev** [DSpace/dspace-angular#940]
**Describe the bug**
I had created a costume theme under the `themes` directory like dspace-angular/themes/costume-theme and added a costume designed home-news component with the proper path. After i changed the environment variable to use my costume theme, and nothing happened the old template shown up.

**To Reproduce**
1. create directory under themes ex.: themes/costume-theme
2. create a costume template with proper path ex.: themes\costume-theme\app\+home-page\home-news\home-news.component.html
3. set environment variable  `theme: {    name: 'costume-theme',  },`
4. run the code `yarn start`

**Expected behavior**
To replace the old template with the new one

As i know the main problem is the webpack replacing the template path with the costume template path is it is exist. But after an `@ngtools/webpack` run with out the webpack changes

**Comment by tdonohue** [comment]
@dsipos-dev : This is a known issue simply because Theming is not yet completed or working.  This will be fixed in #727 and #728  which are scheduled for Beta 5.  This work however cannot begin until #787 is completed, as it will change the behavior of themes slightly.

I'm going to close this ticket as a duplicate simply because it will be part of the upcoming work in #727 and #728.
