### ISSUE TITLE
External Sources cannot be limited based on metadata field

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#943]
**Describe the bug**
Discovered in review of https://github.com/DSpace/dspace-angular/pull/932#pullrequestreview-525533457

When a Lookup button is added to a metadata field (e.g. Author field), there is currently no way to limit which External Sources are searched/searchable.  

This can result in very odd/unexpected behavior like this:
1. Ensure the Author field has a Lookup button, which is the case at https://dspace7-demo.atmire.com/home
2. Click the Lookup and search PubMed for "math"
3. Select an article and click Import

Strangely, this all works...the system lets you import an Article via the Author field.  The Article never appears in the author field, but if you click Lookup again, you'll see the "Current Selection" tab lists the Article as an Author.  **This has the greatest impact on Configurable Entities as it lets you create incorrect *relationships*...in this case you are creating an Author based relationship to an Article/Publication.**

**Expected behavior**
I'd expect that there should be a way to configure which External Sources are used based on the field "type".  For example, in the case of an Author field, it only makes sense to search "Local Authors", "ORCID" and "LC Names".  

It's possible (but not necessarily required) this could be made configurable as part of the Submission configuration eventually.  But, initially we need to at least ensure you cannot

**Comment by tdonohue** [comment]
@artlowel and @benbosman : Would the two of you be willing to brainstorm a solution here?  While this isn't specific to Configurable Entities, this seems (to me) to allow you to create Entities which are unrelated to configured Entity-to-Entity relationships -- e.g. it seems incorrect to allow a submitter to create/link a Publication Entity from a field which represents an Author relationship.

**Comment by benbosman** [comment]
I was able to test this using https://github.com/DSpace/DSpace/pull/3068 with ArXiv (on the demo server only ORCID had results)
This created an item with type "Publication", and hereafter it tries to create the relationship. Angular is however aware that no such relationship can be created (an isAuthorOfPublication relationship is not possible between two Publications), and doesn't even try creating the relationship. Both Angular and REST will refuse to create such a relationship.

What can be improved here:
* Angular shouldn't display the item in the "current selection", especially because Angular is aware it refused to create the relationship. It should rather display a message that the relationship could not be created. This is a useful error independent of the other improvements below
* The `selectableRelationship` from https://github.com/DSpace/Rest7Contract/blob/main/submissionforms.md can be adjusted to create an additional property `externalsources`. This would be a list of all external sources which can be used for this field
* The submission configuration can also be used to store this list of external sources, passing it on to the REST response
* The angular UI can use this list of external sources to determine what's displayed in the overlay

The REST part of these improvements would require roughly 3 hours of work (changing the submission forms, passing it to REST, and creating tests)
I assume Angular will require a bit more work, but it's still limited. I'll leave it up to @artlowel to estimate it since he knows this code in more detail.

**Comment by artlowel** [comment]
>Angular shouldn't display the item in the "current selection", especially because Angular is aware it refused to create the relationship. It should rather display a message that the relationship could not be created. This is a useful error independent of the other improvements below

This is harder than it appears at first sight. There is no direct link between the list of selected items (which is used for both the list in the selected tab, and to determine if something is selected in any of the other tabs)  and the succeeding of the creation of the relationship because otherwise if you select something it would immediately be deselected until the rest response returns, which can take a while. To make it even more difficult there's also a debounce in between selecting an item and sending them to rest, that way if you quickly select and deselect something, no request is sent. Angular also doesn't actively 'refuse' to send the request, it simply can't find the correct relationshiptype, and if there's no type no further code is executed.

But you're right: it _is_ a problem that if the request isn't sent, or the response is an error, that the selected list isn't updated. So we should address that. This will take an estimated **12h**

Determining which external sources tabs to show based on a property in `selectableRelationship` can be done in an estimated: **8h**

So that puts the total for angular at **20h**

**Comment by tdonohue** [comment]
Thanks @benbosman and @artlowel !  That all sounds reasonable.

I'm going to keep this as one ticket for now, as it's primarily Angular work -- and we'll combine the estimates together.  So, this estimate is **23hours** (3 hrs REST, 20 hrs Angular).  Also assigning this to @artlowel as @lieven-atmire privately volunteered you both for this work.
