### ISSUE TITLE
rimraf deletes itself before yarn clean finished

### ISSUE THREAD

**Issue by cwilper** [DSpace/dspace-angular#945]
**Describe the bug**
When running `yarn clean` and not having `rimraf` installed globally, a build error like the following appears. 

```
$ rimraf node_modules
$ rimraf src/environments/environment.ts
/bin/sh: rimraf: command not found
```

**To Reproduce**
1. Don't have rimraf installed globally
2. Run yarn clean
3. You'll see a build error like the above

**Expected behavior**
Finishing without reporting an error.

**Related work**
N/A

**Comment by artlowel** [comment]
I just did a test to see whether moving the `rimraf node_modules` script to the last place would suffice, and it seems it would. It seems rimraf can in fact delete itself.

While we're at it we might as well fix the issue where `yarn run clean` fails when you haven't run `yarn install` before, because rimraf is missing. Both can be fixed in **1h**.

Atmire is interested in claiming this task

**Comment by artlowel** [comment]
I'm sorry, I missed that you already fixed it @cwilper 😄
