### ISSUE TITLE
Error when attempting to open the Content Source section of Edit collection

### ISSUE THREAD

**Issue by LucaGiamminonni** [DSpace/dspace-angular#963]
**Describe the bug**
In the "Content Source" section of Edit collection, when the user click on the checkbox to configure the collection to harvest its content an error occurs and the form to configure the harvest is not shown. 

**To Reproduce**
1. Login in the system
2. Go to Edit Collection
3. Select a collection to edit
4. Go to the Content Source section
5. Click on the checkbox with the label "This collection harvests its content from an external source"

![image](https://user-images.githubusercontent.com/16231083/101195295-81a80f80-365f-11eb-8e23-82ea7293e078.png)

**Expected behavior**
When the checkbox is clicked, the form to configure the harvest must be shown

**Comment by tdonohue** [comment]
Definitely a bug, thanks for reporting @LucaGiamminonni .  However, I'm scheduling this for 7.1, as this bug is very low priority until #761 is implemented (also scheduled for 7.1).  Currently, this "Content Source" tab is very minimal and was added as part of #506.

That said, if the fix is small here, I'm not against having this completed early -- it's just low priority currently. This will also need estimation.

**Comment by artlowel** [comment]
I think this has already been fixed as part of #961. I encountered it while testing and thought it was an issue with the PR.

**Comment by tdonohue** [comment]
@artlowel is correct.  I've verified that **this bug is fixed by #961**.  I'll update this ticket so that it'll close when #961 is merged.
