### ISSUE TITLE
Submission Form - Lookup extremely slow

### ISSUE THREAD

**Issue by TanyaHolm** [DSpace/dspace-angular#990]
I submit a new 'Article'
I use the Lookup functionality for mandatory Author field.
The lookup sometimes takes so long to display the name in form, that I think it does not work and attempt to do another Lookup.

**Comment by tdonohue** [comment]
This is mostly fixed by https://github.com/DSpace/dspace-angular/pull/984 (as that limits which external services are searched for an author lookup). That fix was recently applied to https://demo7.dspace.org/, and I'm seeing it working much faster.  That said, it's still not "speedy" as it uses an external site (e.g. ORCID) for the lookup.

I'm closing this for now as "fixed" by #984 , but we may want to still investigate ways to speed this up further.
