### ISSUE TITLE
Tests broken after Angular 10 upgrade

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#992]
Due to jasmine update it seems that is not possible to create spy on pure function imported from a module or 3rd party package. 
There are several tests (currently disabled) that use this approach by adding a spy on a decorator's function. Those need to be redesigned and rewritten. Here the list:

- src/app/+browse-by/+browse-by-switcher/browse-by-switcher.component.spec.ts
- src/app/shared/cookies/browser-klaro.service.spec.ts
- src/app/shared/mydspace-actions/claimed-task/switcher/claimed-task-actions-loader.component.spec.ts
- src/app/core/cache/builders/link.service.spec.ts
- src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
- src/app/shared/metadata-representation/metadata-representation-loader.component.spec.ts
- src/app/core/data/relationship.service.spec.ts

**Comment by artlowel** [comment]
The reason is that Typescript > 3.9 no longer allows jasmine to affect direct module exports: https://github.com/jasmine/jasmine/issues/1817

There are a few workarounds, such as lowering the target in tsconfig to es5, or using an older version of tslib. None of those are very future proof. Instead I suggest we inject any direct exports we need to spy on, and use the injected function rather than the direct import. That way we can provide a spy instead when testing. I made a proof of concept here: https://github.com/atmire/dspace-angular/commit/d92c716bb6152784822a17d2183975e36dd704f0

Doing that everywhere will take about **6h**. This is a rather high estimate because already during that proof of concept I noticed that the spies on exported functions aren't the only things wrong with the disabled tests mentioned in this issue, and everything that's wrong with them will need to be fixed in order to re-enable them.
